### ISSUE TITLE
listreceivedbyaddress returns incorrect data

### ISSUE THREAD

**Issue by richiela** [decred/dcrwallet#10]
query dcrcoin listreceivedbyaddress 0 true
-4: no transaction details could be found

This should list every address in the wallet... include minconf = 0 and includeempty=true

**Comment by jrick** [comment]
This works correctly in btcwallet.  It might be a bug inherited by the old btcwallet codebase and will be fixed during the next sync, or was introduced by a decred change.

**Comment by dajohi** [comment]
@richiela does this issue still exist with 0.3.0?

**Comment by alexlyp** [comment]
Appears to be fixed. Closing
