### ISSUE TITLE
Spending from a p2sh causes too low of fee

### ISSUE THREAD

**Issue by alexlyp** [decred/dcrwallet#1002]
Because fee estimation assumes you are spending from a p2pkh, when spending from a p2sh the fee given ends up being too low and either rejected by the daemon or accepted and relayed but then would go unmined due to miners' fee rules.  Once the priority rises enough those transaction will finally get mined.

**Comment by raedah** [comment]
Looks like it is addressed in https://github.com/decred/dcrwallet/pull/983

**Comment by jrick** [comment]
Yep, this is resolved.
