### ISSUE TITLE
spendable sstxchange is being detected as immature/expiry

### ISSUE THREAD

**Issue by raedah** [decred/dcrwallet#1013]
This issue was discovered as a result of testing with https://github.com/decred/dcrwallet/pull/963

Appears it is using the 16 block period before a ticket is eligble to vote, as the measure for if the sstxchange is usable. Sstxchange is available for spending as soon as it is mined in a block, hence why it was selected as an eligible input in the first place. The error also calls it an 'expiry' of which it is not.

2017-12-10 05:53:31.672 [ERR] TKBY: Failed to purchase tickets this round: failed to send split transaction: -1: Rejected transaction xxx: tx xxx tried to spend transaction yyy including an expiry from height 192346 at height 192348 before required maturity of 16 blocks

example sstxchange here
https://testnet.dcrdata.org/explorer/tx/389bd79e964431a6ca2576cce2c9abe777c8c34b416ddd2719cb2a8a823e2a1e

**Comment by jrick** [comment]
That error is coming from dcrd (RPC error during sendrawtransaction)

**Comment by raedah** [comment]
refiled as https://github.com/decred/dcrd/issues/945

**Comment by jrick** [comment]
Per comments in the dcrd issue, this is working as intended.  If ticket purchases do not set an expiry, these ticket purchase change outputs should be immediately spendable.  You could create ticket purchases without an expiry, but then the possibility remains that the ticket forever lingers in mempool or is included at a later time after the ticket price has dropped.
