### ISSUE TITLE
Pool voted, but wallet considered it a miss

### ISSUE THREAD

**Issue by alexlyp** [decred/dcrwallet#1014]
Report from user on slack:

> I had a vote notification from stakeminer last night, and when checked decrediton it showed as a MISS. Stakeminer showed it as voted, and when I traced the ticket through the blockchain, I saw the reward. Therefore, I rescanned on Decrediton and then it showed as a Vote. 

After rescan they saw 1 less missed and 1 more vote than it was before.

**Comment by matheusd** [comment]
Confirming I noticed this in one of my wallets. Looking at the block explorer I saw my ticket as voted, but Decrediton showed as missed. Rescanning fixed the issue.

**Comment by jrick** [comment]
was the pool script not imported?

**Comment by matheusd** [comment]
It was previously imported (meaning: I was purchasing tickets normally). When I started it this morning it wasn't on Decrediton's config.json (because I had changed networks).

**Comment by jrick** [comment]
If this bug is observed again, could you try a `gettransaction` against the vote and see if the wallet knows about it or not? Also check to make sure that dcrd is still up to date with the latest block.

**Comment by matheusd** [comment]
Will do.

**Comment by jrick** [comment]
Closing due to age.  This is probably fixed by introduction of the rescan point with the SPV changes.
