### ISSUE TITLE
Transactions from imported fail to correctly track on wallet startup

### ISSUE THREAD

**Issue by cjepson** [decred/dcrwallet#102]
RelevantTx do not seemed to be produced for imported scripts after shutting down and restarting the wallet. The issue persists even if the imported addresses are added to the rescan.

**Comment by chappjc** [comment]
Relevant meaning subsidy after stake pool votes?  Is there a workaround and/or can a patch retroactively fix it?

**Comment by cjepson** [comment]
Will have it patched shortly.

**Comment by cjepson** [comment]
Patched with dcrrpcclient patch 10.
