### ISSUE TITLE
Follow BIP 0044 and warn if number of unused addresses exceeds the gap limit.

### ISSUE THREAD

**Issue by githubsands** [decred/dcrwallet#1042]
https://github.com/decred/dcrwallet/blob/8a9a1703891b38cb6f9805f38a3a8680b7f0f7cc/rpc/legacyrpc/methods.go#L1118

**Comment by jrick** [comment]
This is done now by returning an error when the gap limit would be violated, and the comment can be removed.

**Comment by githubsands** [comment]
Completed with PR #1044
