### ISSUE TITLE
Missing wallet funds from generated seed

### ISSUE THREAD

**Issue by Stradivario** [decred/dcrwallet#1051]
Hello guys i have the same problem with my seed first i have some TYPING miss take inside my Decred Seed which is not from my side but instead the system before 5 months decided to not confirm my seed and throws error INVALID seed from more research i found TYPO miss take in my seed which is not from my side because i COPY and PASTE the seed from wallet.decred.org to my TEXT document.I think nobody wants to change typo miss take inside WALLET SEED.
So ok i import my wallet it recognize it with new TYPO added but there is no funds inside the wallet hm... it strange i have 1.7 Decred inside this wallet and when i look at my account inside https://www2.coinmine.pl my Payment address is set DsVK1vLvxkc59iN6hUpNye1wSMqBDwjVRHr and inside of it there is a 1.7 decred's https://mainnet.decred.org/address/DsVK1vLvxkc59iN6hUpNye1wSMqBDwjVRHr
So somehow my SEED forgot about this Generated wallet address and now i cannot see my 1.7 decred balance inside my wallet....

Of course i try Settings Rescan Wallets for funds nothing happen so is there any chance that i can get my small amount 1.7 Decred back to my wallet ? 

I think this issue is related with https://github.com/decred/dcrwallet/issues/106
Thank you in advance.

Best Regards,
Kristiyan Tachev

**Comment by jrick** [comment]
Are you using Decrediton?  Do you remember creating any additional accounts, and is that address from a non-default account?

**Comment by Stradivario** [comment]
No i use only wallet.decred.org didn't try Desktop application.I didn't create any additional accounts accept the one with the Seed inside and i am using only seed to access my funds.

So you are guessing that maybe i created new account and then import my seed which now i will have 2 accounts and by miss take i take the Address from non seed generated account instead from the automatically generated one ?

**Comment by jrick** [comment]
I can't provide support for the web wallet, and we will eventually phase it out of commission once we have light desktop wallets available.  In the meantime try using dcrwallet or Decrediton.  Feel free to stop by our support channel on slack/discord/matrix/etc (https://decred.org/community/) if you need realtime help.

**Comment by jrick** [comment]
Closing since this was regarding the web wallet, not dcrwallet.  Stop by our support channel if you still need help.
