### ISSUE TITLE
default should be used when an account is not specified in an rpc request

### ISSUE THREAD

**Issue by ByronAP** [decred/dcrwallet#107]
default should be used when an account is not specified in an rpc request

ex: GetNewAddress("") should be the same as GetNewAddress("default")

re: conform to bts standard

**Comment by cjepson** [comment]
That is the current way it works for getnewaddress. Which RPC commands were you referring to?

**Comment by jcvernaleo** [comment]
@ByronAP as @cjepson said, I think most RPC commands do this.  Can you point out which one or ones doesn't so I can take a look at them?
Thanks!

**Comment by jcvernaleo** [comment]
Since it has been about a month with no follow-up and we haven't been able to reproduce I'm closing this.  Feel free to reopen if there is still an issue.
