### ISSUE TITLE
Don't allow invalid minimum transaction fee

### ISSUE THREAD

**Issue by raedah** [decred/dcrwallet#108]
The minimum transaction fee is 0.01. Instead of allowing a user to set a 0 fee, and then giving them tx failures for low fee, it would be better to return an error to them when they try to set the low fee.

**Comment by cjepson** [comment]
The transaction fee threshold will be set by the daemon once that PR gets in, so it will need a way to check what this is first at the daemon level (RPC client hook?)

**Comment by jrick** [comment]
As we are making the wallet multipeer with SPV, and there is no way to check what other node's mempool policy is, I don't think this makes sense anymore.  The wallet should just do as it's told.
