### ISSUE TITLE
Decred PoS Ticket not voted since October 2017

### ISSUE THREAD

**Issue by leonalicious** [decred/dcrwallet#1082]
Good Day Folks, 

I have purchased ticket since last year October and I think it is still not being voted yet, I am curious is it stuck or lost ? same thing happens to my January Ticket.
Appreciate your guys hard effort and please investigate on this. Thank you.

**Comment by chappjc** [comment]
Please use one of the recommended chat options for support.

Also, I suggest not posting your transactions here or anywhere public.

Your October ticket is still live, but not for much longer.  It has 40960 + 256 blocks from purchase.

**Comment by leonalicious** [comment]
not really get what you mean by It has 40960 + 256 blocks from purchase, any documentation for reference please?

**Comment by dnldd** [comment]
> The PoS system rewards participants for their staking. Every Decred block has a PoS reward component that will be distributed to every ticket chosen to vote in that block. The system is designed in such a way that the average time for the ticket to be selected is 28 days. If a ticket hasn’t been selected after 40960 blocks (a bit under 5 months) it will be revoked by the system. The DCR used to purchase a ticket is returned regardless of whether or not it votes.

this info can be found here: https://docs.decred.org/faq/proof-of-stake/general/
