### ISSUE TITLE
getinfo - keypoolsize returns static 0

### ISSUE THREAD

**Issue by richiela** [decred/dcrwallet#11]
query dcrcoin keypoolrefill 100
query dcrcoin getinfo
{
  "version": 100,
  "protocolversion": 1,
  "walletversion": 4,
  "balance": 0,
  "blocks": 4306,
  "timeoffset": 0,
  "connections": 3,
  "proxy": "",
  "difficulty": 199771.58352835,
  "testnet": true,
  "keypoololdest": 1454271842,
  "keypoolsize": 0,
  "unlocked_until": 0,
  "paytxfee": 0.01,
  "relayfee": 1e-05,
  "errors": ""
}

If keypoolsize is deprecated, can we use a static 100 or something large so people dont think the keypool is empty

**Comment by jrick** [comment]
How about using the JSON null or omitting the keypoolsize result from the object?  I don't want to say 100 either.  It's not just deprecated.  We don't have a keypool.

**Comment by richiela** [comment]
omitting it is bad unfortunately since it will default to 0... I do understand why you don't want to include it... this is something we can just code in ourselves if it doesn't affect anyone else.

**Comment by cjepson** [comment]
jrick: What about just using the index of the address manager in the default account for the keypoolsize? It more or less indicates the same thing as the historical Bitcoin RPC call.

**Comment by jrick** [comment]
Not going to lie about the keypool, so closing this.
