### ISSUE TITLE
translation of web wallet in Chinese is wrong

### ISSUE THREAD

**Issue by livc** [decred/dcrwallet#1100]
in https://wallet.decred.org/ if want to receive DCR, the sentence over QR code of Chinese treat DCR as BTC:

![image](https://user-images.githubusercontent.com/11692045/38175187-f38948e2-360a-11e8-9e1d-f894ebfef760.png)

The sentence in the image means 'my bitcoin address'. So the right one should be “我的DCR地址” or something(I'm not sure if DCR has an official Chinese name).

I don't know where to feedback it so I post here.

**Comment by gravityz3r0** [comment]
I think "比特币" means bitcoin which effectively means My Bitcoin Wallet.

Decred in Chinese is known as "德信币".

So the correct translation for "My Decred Wallet" is 我的德信币地址.

**Comment by jrick** [comment]
Thanks for reporting the translation error, but this is the wrong repo.  The web wallet runs [our copay fork](https://github.com/decred/copay) not dcrwallet.
