### ISSUE TITLE
Sort rpc help list text

### ISSUE THREAD

**Issue by raedah** [decred/dcrwallet#1125]
It can be misleading that it looks like the dcrctl help output for dcrwallet is in alphabetical order but then its not. Expected behavior is to have all items sorted alphabetically.

https://github.com/decred/dcrwallet/blob/master/rpc/legacyrpc/rpcserverhelp.go

**Comment by red010b37** [comment]
@raedah - Is this some that need resolving?  I'm looking for smaller tickets to get me into the codebase and am happy to pick this one up.

**Comment by jrick** [comment]
I don't like sorting everything alphabetically, and prefer the current way that all wallet RPCs appear first, and if dcrd RPC is active, the help for all dcrd RPCs follows

**Comment by jrick** [comment]
Actually, the wallet commands themselves are out of order.  This can be fixed by alphabetizing all of the methods in this slice: https://github.com/decred/dcrwallet/blob/9d1023a/internal/rpchelp/methods.go#L23
