### ISSUE TITLE
wallet/udb/addressmanager.go:1834:12: assignment mismatch: 2 variables but 1 values

### ISSUE THREAD

**Issue by yousq** [decred/dcrwallet#1128]
when i install dcrwallet from source code(v1.20), i met this problem.

# github.com/decred/dcrwallet/wallet/udb
wallet/udb/addressmanager.go:1824:12: assignment mismatch: 2 variables but 1 values
wallet/udb/addressmanager.go:1834:12: assignment mismatch: 2 variables but 1 values
wallet/udb/addressmanager.go:2604:14: assignment mismatch: 2 variables but 1 values
wallet/udb/addressmanager.go:2614:14: assignment mismatch: 2 variables but 1 values
wallet/udb/addressmanager.go:2631:14: assignment mismatch: 2 variables but 1 values
wallet/udb/addressmanager.go:2641:14: assignment mismatch: 2 variables but 1 values
wallet/udb/addressmanager.go:2653:13: assignment mismatch: 2 variables but 1 values
wallet/udb/addressmanager.go:2663:13: assignment mismatch: 2 variables but 1 values
wallet/udb/addressmanager.go:2673:13: assignment mismatch: 2 variables but 1 values
wallet/udb/addressmanager.go:2683:13: assignment mismatch: 2 variables but 1 values
wallet/udb/addressmanager.go:2683:13: too many errors

the version of go is :
go version go1.10 linux/amd64

Is there anyone know what's the problem?

**Comment by jrick** [comment]
See the build instructions in the README.  You didn't update your vendored dependencies with dep.

**Comment by yousq** [comment]
ah~ , it worked, thanks  @jrick !
