### ISSUE TITLE
about wallet rpc command --- move

### ISSUE THREAD

**Issue by jokeryg** [decred/dcrwallet#1138]
I see the "move" command on this page,
https://docs.decred.org/advanced/program-options/

but actually use it to remind me of "-8: No help for method 'move'".

i want to know , How do I transfer money between my wallet's account?

dcrd,dcrwallet,dcrctl version : dcrinstall - 1.2.0

**Comment by jrick** [comment]
The docs are wrong.  There is no `move` method and there never will be, because the only way to move funds between accounts is to perform an on-chain transaction (`sendtoaddress`, `sendfrom`, or `sendmany`).

I'll open an issue for the incorrect docs.
