### ISSUE TITLE
build fail because of 'use of internal package not allowed'

### ISSUE THREAD

**Issue by hunjixin** [decred/dcrwallet#1141]
# failure message

hunjixin@hunjixin-K56L:~/桌面/SimpleDappApp/ImageSprits/src/dcrwallet$ go install
config.go:22:2: use of internal package not allowed
dcrwallet.go:23:2: use of internal package not allowed
dcrwallet.go:24:2: use of internal package not allowed

# go version

hunjixin@hunjixin-K56L:~/桌面/SimpleDappApp/ImageSprits/src/dcrwallet$ go version
go version go1.10.1 linux/amd64

# decwallet version

latest master

**Comment by jrick** [comment]
You are building it from the wrong location.  dcrwallet can only be built from $GOPATH/src/github.com/decred/dcrwallet
