### ISSUE TITLE
signrawtransaction: panic serving [::1]:62012: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by dmorris99** [decred/dcrwallet#1148]
Hi all, 

Installed latest Decredition couple of days ago. Running legacy RPC wallet server, and getting stack trace below when trying to sign a raw transaction. Any pointers?

many thanks

2018/05/26 22:27:54 http: panic serving [::1]:62012: runtime error: invalid memory address or nil pointer dereference
goroutine 7286 [running]:
net/http.(*conn).serve.func1(0xc04246a1e0)
        /usr/local/go/src/net/http/server.go:1726 +0xd7
panic(0xab0440, 0x1108de0)
        /usr/local/go/src/runtime/panic.go:502 +0x237
github.com/decred/dcrwallet/rpc/legacyrpc.signRawTransaction(0xc042174000, 0xa3aee0, 0xc0424f76b0, 0x0, 0x0, 0x2, 0xc042003520)
        /home/decred/go/src/github.com/decred/dcrwallet/rpc/legacyrpc/methods.go:2983 +0xacc
github.com/decred/dcrwallet/rpc/legacyrpc.lazyApplyHandler.func2(0xc042174000, 0xd74dc0, 0xc0424f7620)
        /home/decred/go/src/github.com/decred/dcrwallet/rpc/legacyrpc/methods.go:207 +0x64
github.com/decred/dcrwallet/rpc/legacyrpc.(*Server).postClientRPC(0xc042174000, 0xd74540, 0xc0421a00e0, 0xc042088200)
        /home/decred/go/src/github.com/decred/dcrwallet/rpc/legacyrpc/server.go:597 +0x38c
github.com/decred/dcrwallet/rpc/legacyrpc.NewServer.func2(0xd74540, 0xc0421a00e0, 0xc042088200)
        /home/decred/go/src/github.com/decred/dcrwallet/rpc/legacyrpc/server.go:142 +0x216
net/http.HandlerFunc.ServeHTTP(0xc042461c20, 0xd74540, 0xc0421a00e0, 0xc042088200)
        /usr/local/go/src/net/http/server.go:1947 +0x4b
github.com/decred/dcrwallet/rpc/legacyrpc.throttled.func1(0xd74540, 0xc0421a00e0, 0xc042088200)
        /home/decred/go/src/github.com/decred/dcrwallet/rpc/legacyrpc/server.go:317 +0x1c4
net/http.HandlerFunc.ServeHTTP(0xc04213c420, 0xd74540, 0xc0421a00e0, 0xc042088200)
        /usr/local/go/src/net/http/server.go:1947 +0x4b
net/http.(*ServeMux).ServeHTTP(0xc04213c3f0, 0xd74540, 0xc0421a00e0, 0xc042088200)
        /usr/local/go/src/net/http/server.go:2337 +0x137
net/http.serverHandler.ServeHTTP(0xc042174000, 0xd74540, 0xc0421a00e0, 0xc042088200)
        /usr/local/go/src/net/http/server.go:2694 +0xc3
net/http.(*conn).serve(0xc04246a1e0, 0xd74d00, 0xc042440b40)
        /usr/local/go/src/net/http/server.go:1830 +0x658
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2795 +0x282

**Comment by jrick** [comment]
You appear to be hitting this special case in the dcrd gettxout RPC:

https://github.com/decred/dcrd/blob/d7fc102c280e9c083428f09fc3e6a80b9d53c514/rpcserver.go#L3963

We will add a workaround in the wallet in order to prevent the panic, but unfortunately there's nothing we can do to obtain the data.

**Comment by dmorris99** [comment]
Thanks for the input @jrick .

FYI - not sure if I'm doing it right (first time creating a raw transaction), but my use case (below) is I think very straightforward in principle.

If there's something obviously wrong, please do let me know :) 

many thanks!

C:\Users\dom\AppData\Local\Programs\decrediton\resources\bin>dcrctl /wallet /rpcpass:dom /rpcserver:localhost:9110 /skipverify listunspent
[
  {
    "txid": "3e0bdb15dd2a338da0865f5422b976cd34737dadd276cc793ecd21b5fad45dc3",
    "vout": 7,
    "tree": 0,
    "txtype": 0,
    "address": "DsWX7y1YzMPdhSDK71tqqHxHCpxaR59PW6E",
    "account": "MINING_IN_DM",
    "scriptPubKey": "76a9143cf05a8e1ebeae216cbc35359f6bba628ba2c1b788ac",
    "amount": 0.20249371,
    "confirmations": 48,
    "spendable": true
  }
]

C:\Users\dom\AppData\Local\Programs\decrediton\resources\bin>dcrctl /wallet /rpcpass:dom /rpcserver:localhost:9110 /skipverify createrawtransaction "[{\"txid\":\"3e0bdb15dd2a338da0865f5422b976cd34737dadd276cc793ecd21b5fad45dc3\",\"vout\":0}]" "{\"DsV2C5es3sDrkZbQdaTVfwZbSvef3r8St37\":0.005}"
0100000001c35dd4fab521cd3e79cc76d2ad7d7334cd76b922545f86a08d332add15db0b3e0000000000ffffffff0120a107000000000000001976a9142c7f9985f2ebe79380924ea6a8b04ef49fc426f188ac000000000000000001ffffffffffffffff00000000ffffffff00

C:\Users\dom\AppData\Local\Programs\decrediton\resources\bin>dcrctl /wallet /rpcpass:dom /rpcserver:localhost:9110 /skipverify signrawtransaction 0100000001c35dd4fab521cd3e79cc76d2ad7d7334cd76b922545f86a08d332add15db0b3e0000000000ffffffff0120a107000000000000001976a9142c7f9985f2ebe79380924ea6a8b04ef49fc426f188ac000000000000000001ffffffffffffffff00000000ffffffff00
Post https://localhost:9110: EOF

**Comment by jrick** [comment]
That output from listunspent is in fact spent, but the wallet is unaware of this (see https://explorer.dcrdata.org/tx/3e0bdb15dd2a338da0865f5422b976cd34737dadd276cc793ecd21b5fad45dc3).  You will need to rescan to fix this.

**Comment by dmorris99** [comment]
Thanks @jrick -- this is starting to make sense to me now, thanks to you.

I must admit I hadn't RTFM as deeply as I should have.

**Comment by jrick** [comment]
Going to reopen this since you discovered that panic.  Once the fix has been approved and merged, it will be closed.
