### ISSUE TITLE
reuseaddresses to reuse more then one address

### ISSUE THREAD

**Issue by raedah** [decred/dcrwallet#116]
Right now reuseaddresses sends all SStx purchase transactions to the same address. If reuseaddresses was previously disabled, there are already many addresses generated for stake voting. It is desirable that multiple addresses can be reused, so that its not just using either 1 address or making a new address for every SStx purchase transaction.

**Comment by jrick** [comment]
reuseaddresses was deprecated and will be removed in a future version.
