### ISSUE TITLE
createtemp flag's description is outdated

### ISSUE THREAD

**Issue by vctt94** [decred/dcrwallet#1165]
The `--createtemp` flag's description is outdated, it says "Create a temporary simulation wallet (pass=password) in the data directory indicated; must call with --datadir", but datadir is being deprecated by `--appdata`. 

So it should be changed.

**Comment by red010b37** [comment]
@vctt94 can I pick this ticket up as my first dcrwallet ticker

**Comment by vctt94** [comment]
Sure @red010b37, go ahead.

**Comment by red010b37** [comment]
@vctt94 can you go ahead and close this as I see it is now merged.

Thanks Paul
