### ISSUE TITLE
dcrwallet msg for when your tx gets into a block

### ISSUE THREAD

**Issue by raedah** [decred/dcrwallet#117]
Id like dcrwallet to show a msg when my tx gets into a block. From irc, "Maybe should be debug. As it is I think dcrwallet is too loud, it's mostly supposed to serve the API"

Right now I am seeing two rows for sending a transaction. Maybe one of these could be silenced. "TMGR: Inserting unconfirmed transaction", "WLLT: Successfully sent SStx purchase transaction".

I see the point about not wanting too much noise, but without any GUI right now, there are few places to get information about whats going on and knowing if your transactions are getting in blocks is useful information.

**Comment by jrick** [comment]
> Maybe should be debug

It already is there, with the debug log level: https://github.com/decred/dcrwallet/blob/daa20214296628913c37f3fcadb26ae1804ea9e4/wtxmgr/tx.go#L647-L648
