### ISSUE TITLE
Remove Start/Stop/WaitForShutdown methods of wallet.Wallet

### ISSUE THREAD

**Issue by jrick** [decred/dcrwallet#1178]
The wallet should be usable without manually starting and stopping worker goroutines.  Currently, these goroutines are run to handle tasks such serializing transaction creation and managing the locked/unlocked states.  The API could be simplified to remove these functions by using mutexes for serialization instead of goroutines and channels.

**Comment by pcx** [comment]
@jrick Can I work on this?

After studying the related code, I understand that I will have to
- remove `Wallet.txCreator` and `Wallet.walletLocker` goroutines and the channels they listen on
- split these goroutines into multiple methods that can be called directly
- Use these new methods in places where the channels were being written to
- Synchronize the methods using mutexes

Lemme know if I missed something.

**Comment by jrick** [comment]
That's right, and in the case of walletLocker, you probably will still need to still spawn goroutines when unlocking the wallet to perform some actions after a delay.
