### ISSUE TITLE
Implement fundrawtransaction JSON-RPC

### ISSUE THREAD

**Issue by jrick** [decred/dcrwallet#1181]
This method is currently unimplemented, and should be implemented as part of the raw transaction JSON-RPC API.

The behavior should be similar to [Bitcoin Core's implementation](https://github.com/bitcoin/bitcoin/blob/ca2a23387be6e4b18a68721306c47dc4b5582a93/src/wallet/rpcwallet.cpp#L3371-L3425).  Some differences that must be accounted for are:

* The funding account must be specified as a non-optional parameter
* Address types (for change) can likely be ignored, since we have a malleability fix for normal P2PKH
* We don't have separate watching-only addresses in wallets with other private keys, so `includeWatching` makes little sense
* RBF (BIP125) isn't implemented by dcrwallet and doesn't need support in this request
* There is no fee rate estimation, so the `estimate_mode` parameter doesn't make sense
* There is no segwit distinction in Decred, so the `iswitness` parameter is unnecessary

**Comment by vctt94** [comment]
Can I get this issue?
