### ISSUE TITLE
dumpprivkey command error

### ISSUE THREAD

**Issue by guanhui07** [decred/dcrwallet#1185]
` dcrctl   -u='gF0r5BBFTEQGEhOzu7VoSVvCmuc=' -P='sAdmP6rziHH2WcRWA7cJk+fguzo=' --wallet  dumpprivkey ‘DsnMV9d1xCHnW3PhUzc12Unz6Z4WWc9TvVb’  --testnet

return error:
-5: invalid address "‘DsnMV9d1xCHnW3PhUzc12Unz6Z4WWc9TvVb’": decode failed: `decoded address is of unknown format: invalid format: version and/or checksum bytes missing``

how to deal the command return error?

**Comment by jrick** [comment]
remove the quotes around the address

**Comment by davecgh** [comment]
Also `Ds....` is an address for mainnet, not testnet.  Testnet addresses start with `Ts`.

**Comment by guanhui07** [comment]
dcrctl -u='gF0r5BBFTEQGEhOzu7VoSVvCmuc=' -P='sAdmP6rziHH2WcRWA7cJk+fguzo=' --wallet dumpprivkey TsRVQMTRzZfEABmpqDv8eKivDBkVUeG3pTR --testnet

thanks , I get the right return key  by the command

**Comment by guanhui07** [comment]
And I can't find the command from rpc api [#rpc_api_url](https://github.com/decred/dcrwallet/blob/master/rpc/documentation/api.md#balance)
@davecgh @jrick 
can you tell me ,is it exists ?
I see  all  wallet server  commands in  dcrctl  -l   ,but  many command is not   come true   in the rpc_api 

`
accountaddressindex "account" branch
accountsyncaddressindex "account" branch index
addmultisigaddress nrequired ["key",...] ("account")
addticket "tickethex"
consolidate inputs ("account" "address")
createmultisig nrequired ["key",...]
createnewaccount "account"
createrawssgentx [{"txid":"value","vout":n,"tree":n},...] votebits
createrawssrtx [{"txid":"value","vout":n,"tree":n},...] (fee)
createrawsstx [{"txid":"value","vout":n,"tree":n,"amt":n},...] amount [{"addr":"value","commitamt":n,"changeaddr":"value","changeamt":n},...]
createvotingaccount "name" "pubkey" (childindex=0)
dropvotingaccount
dumpprivkey "address"
estimatepriority numblocks
generatevote "blockhash" height "tickethash" votebits "votebitsext"
getaccount "address"
getaccountaddress "account"
getaddressesbyaccount "account"
getbalance ("account" minconf=1)
getmasterpubkey ("account")
getmultisigoutinfo "hash" index
getnewaddress ("account" "gappolicy")
getrawchangeaddress ("account")
getreceivedbyaccount "account" (minconf=1)
getreceivedbyaddress "address" (minconf=1)
getstakeinfo
getticketfee
gettickets includeimmature
gettransaction "txid" (includewatchonly=false)
getvotechoices
getwalletfee
importaddress "address" (rescan=true)
importprivkey "privkey" ("label" rescan=true scanfrom)
importpubkey "pubkey" (rescan=true)
importscript "hex" (rescan=true scanfrom)
keypoolrefill (newsize=100)
listaccounts (minconf=1)
listlockunspent
listreceivedbyaccount (minconf=1 includeempty=false includewatchonly=false)
listreceivedbyaddress (minconf=1 includeempty=false includewatchonly=false)
listscripts
listsinceblock ("blockhash" targetconfirmations=1 includewatchonly=false)
listtransactions ("account" count=10 from=0 includewatchonly=false)
listunspent (minconf=1 maxconf=9999999 ["address",...])
lockunspent unlock [{"txid":"value","vout":n,"tree":n},...]
purchaseticket "fromaccount" spendlimit (minconf=1 "ticketaddress" numtickets "pooladdress" poolfees expiry "comment" ticketfee)
redeemmultisigout "hash" index tree ("address")
redeemmultisigouts "fromscraddress" ("toaddress" number)
renameaccount "oldaccount" "newaccount"
rescanwallet (beginheight=0)
revoketickets
sendfrom "fromaccount" "toaddress" amount (minconf=1 "comment" "commentto")
sendmany "fromaccount" {"address":amount,...} (minconf=1 "comment")
sendtoaddress "address" amount ("comment" "commentto")
sendtomultisig "fromaccount" amount ["pubkey",...] (nrequired=1 minconf=1 "comment")
sendtossgen "fromaccount" "tickethash" "blockhash" height votebits ("comment")
sendtossrtx "fromaccount" "tickethash" ("comment")
sendtosstx "fromaccount" amounts [{"txid":"value","vout":n,"tree":n,"amt":n},...] [{"addr":"value","commitamt":n,"changeaddr":"value","changeamt":n},...] (minconf=1 "comment")
setbalancetomaintain balance
setticketfee fee
setticketmaxprice max
settxfee amount
setvotechoice "agendaid" "choiceid"
signmessage "address" "message"
signrawtransaction "rawtx" ([{"txid":"value","vout":n,"tree":n,"scriptpubkey":"value","redeemscript":"value"},...] ["privkey",...] flags="ALL")
signrawtransactions ["rawtx",...] (send=true)
stakepooluserinfo "user"
startautobuyer "account" "passphrase" (balancetomaintain maxfeeperkb maxpricerelative maxpriceabsolute "votingaddress" "pooladdress" poolfees maxperblock)
stopautobuyer
sweepaccount "sourceaccount" "destinationaddress" (requiredconfirmations feeperkb)
verifyseed "seed" (account)
walletinfo
walletlock
walletpassphrase "passphrase" timeout
walletpassphrasechange "oldpassphrase" "newpassphrase"
`

**Comment by jrick** [comment]
that documentation is for the grpc server, not for the json-rpc server.  dcrctl is only a json-rpc client.

**Comment by guanhui07** [comment]
thanks  and  where is  api's  documentation  for the json-rpc server
