### ISSUE TITLE
sendtoaddress should succeed if passing in empty strings to comment/comment to

### ISSUE THREAD

**Issue by richiela** [decred/dcrwallet#12]
this is nit picky, but causes a problem because comments aren't supported yet and a lot of btc libraries include all the parameters in the interface.

if sendtoaddress is called with empty strings, it should complete the transaction without throwing the error.

**Comment by jrick** [comment]
This seems reasonable.

**Comment by jcvernaleo** [comment]
@jirck is this something you would want to do upstream first?

**Comment by jrick** [comment]
Yeah it's not critical that it's fixed for the mainnet launch so i'll change this in btcwallet.

**Comment by jrick** [comment]
Fixed upstream

**Comment by jcvernaleo** [comment]
Great, thanks @jrick

**Comment by jcvernaleo** [comment]
I cherry-picked the fix from upstream so this will be fixed in the next release.
