### ISSUE TITLE
spv handle block, Txn is too big to fit into one request

### ISSUE THREAD

**Issue by raedah** [decred/dcrwallet#1236]
Appears to halt proper loading of account balances.

[WRN] SYNC: Failed to handle blocks inventoried by x.x.x.x:x: spv.HandleBlockAccouncements(): invalid operation:: wallet.ChainSwitch: Txn is too big to fit into one request

**Comment by C-ollins** [comment]
This is coming from BadgerDB file partion size. Increasing the size solves this

**Comment by raedah** [comment]
dcrandroid specific
