### ISSUE TITLE
purchasetickets attempts to use P2PK addresses

### ISSUE THREAD

**Issue by chappjc** [decred/dcrwallet#1237]
If the wallet owns an unspent p2pk output, `purchasetickets` evidently tries to use it and can throw an error:

`-4: wallet.PurchaseTickets:: txauthor.NewUnsignedTransaction: unexpected script class for credit: pubkey`

Only P2PKH and P2SH should be used in the ticket purchase, or at least P2PK not used as a ticket commitment address.  But it seems like purchasetickets should be able to use them in the split transaction without any trouble.  It does not.

To prevent funds getting "stuck" in P2PK outputs, a solution for sending them to one of the wallet's own P2PKH addresses would help.

**Comment by jrick** [comment]
Github didn't auto close this for some reason, but 1248 fixed this.  The release-v1.3 branch will be merged back into master soon, so these fixes will also become part of 1.4.
