### ISSUE TITLE
gRPC ValidateAddress returning pkh address instead of pk address

### ISSUE THREAD

**Issue by matheusd** [decred/dcrwallet#1254]
The pubKeyAddress member of the response is returning back the p2pkh address instead of the pubkey address associated with the address passed in the request.

I believe this:
https://github.com/decred/dcrwallet/blob/master/rpc/rpcserver/server.go#L1699

needs to use `String()` instead of `EncodeAddress()` so that it is compatible to the legacy rpc validateAddress endpoint.

https://github.com/decred/dcrwallet/blob/master/rpc/legacyrpc/methods.go#L3363

**Comment by jrick** [comment]
Definitely agree.  We can fix this and do a patch bump for the api.
