### ISSUE TITLE
Environment to generate gRPC bindings is well suited for a Dockerfile

### ISSUE THREAD

**Issue by jrick** [decred/dcrwallet#1267]
The current method of generating the gRPC bindings relies on protoc and protoc-gen-go both being installed in the developer's current environment, and the versions of both being correct.  It may simplify the process to have this environment specified by a Dockerfile, and for the environment to be kept up to date with the expected versions of these tools.

This would also allow us to remove the notice in the RPC documentation about how to install the correct version of protoc-gen-go (see #1253).

**Comment by matheusd** [comment]
Random thought: it might be worth it to add a check to `run_tests` to check whether there are no updates in the generated bindings vs the ones committed to source (similarly to what was being done in the gopkg.lock file).

**Comment by peterzen** [comment]
This was implemented in #1432
