### ISSUE TITLE
Improve size/fee estimation for tickets

### ISSUE THREAD

**Issue by matheusd** [decred/dcrwallet#1272]
Tickets created by the wallet currently use a fixed size estimation: 300 bytes for solo voting, 550 bytes for VSP controlled tickets. 

This slightly overestimates actual ticket sizes, which causes a slight increase in total fee amount and effective fee rate.

Ideally, the wallet should use the internal estimators to correctly account for each script type on each output to get the final ticket size estimate correctly.

**Comment by dnldd** [comment]
Will sort this out.
