### ISSUE TITLE
Wallets that do not perform address discovery do not watch addresses in the initial gap limit

### ISSUE THREAD

**Issue by jrick** [decred/dcrwallet#1297]
This is easily hit on simnet.

To reproduce:

1. Create a new simnet wallet
2. Create a new simnet dcrd using the mining address from above
3. Start both dcrd and dcrwallet but not not mine any blocks. The wallet will connect to dcrd but not perform any address discovery because only the genesis block exists.
4. Use the CPU miner to mine 2 blocks (first is a premine block and won't contain a coinbase output for the wallet).  The second coinbase transaction will not be noticed by the wallet.

**Comment by kLkA** [comment]
I'll take

**Comment by jrick** [comment]
Unsure when this was fixed, but I confirmed this is not a bug on master any longer.
