### ISSUE TITLE
walletlock RPC call fails to lock wallet

### ISSUE THREAD

**Issue by cjepson** [decred/dcrwallet#13]
It appears this issue was inherited from btcwallet.

https://github.com/btcsuite/btcwallet/blob/master/wallet/wallet.go#L695-L710

Calls to the w.lockRequests channel should cause the wallet to lock, but rather it sets the timeout to nil which causes it to never trigger the lock.

**Comment by jrick** [comment]
This has been fixed upstream.  Please cherry-pick 515cbc69ce53027afd22b3fc0ab62f3abf731cd0.

**Comment by jcvernaleo** [comment]
Thanks @jrick.

Cherry-picked on the latest master.
