### ISSUE TITLE
Add GetTicket grpc endpoint

### ISSUE THREAD

**Issue by matheusd** [decred/dcrwallet#1317]
This call should receive the ticket hash and return the information as if it were a single element of a `GetTickets` call (ie, one instance of a `GetTicketsResponse` message).

The point of this is to be able to find the respective spender (either a vote or revocation) for an arbitrary ticket. The opposite (going from a vote/revocation to a ticket hash) is easy to do, given that you can just check the appropriate outpoint of the spender transaction.

**Comment by dnldd** [comment]
Will sort this out.
