### ISSUE TITLE
walletrpc.GetTransactionResponse.GetBlockHash returns incorrect block hash

### ISSUE THREAD

**Issue by barisere** [decred/dcrwallet#1365]
Here's a snippet that shows how I'm using the package.
```go
import pb "github.com/decred/dcrwallet/rpc/walletrpc"
import "github.com/decred/dcrd/chaincfg/chainhash"

// setup connection, ...

hash, err := chainhash.NewHashFromStr(transactionHash)
// handle error
getTxRequest := &pb.GetTransactionRequest{TransactionHash: hash[:]}
getTxResponse, err := c.walletServiceClient.GetTransaction(context.Background(), getTxRequest)
// handle error
fmt.Printf("%x\n", getTxResponse.GetBlockHash())

// the following fails
blockInfo, err := c.walletServiceClient.BlockInfo(context.Background(), &pb.BlockInfoRequest{BlockHash: getTxResponse.GetBlockHash()})
// handle error
```
The block hash printed is a byte-reversed copy of `transactionHash`. It is also different from the block hash displayed on dcrdata (testnet.dcrdata.org). If I copy the block hash shown on dcrdata into the `c.walletServiceClient.BlockInfo` request, it works as expected. But if I use the value of block hash returned by the package, I get the following error.
```
rpc error: code = NotFound desc = wallet.BlockInfo: item does not exist: block header
```

Package version: github.com/decred/dcrwallet/rpc/walletrpc v0.2.0

**Comment by davecgh** [comment]
Hashes on the wire are reversed from the way they are shown.  The response is the raw bytes.  Since you're just printing it with `%x`, you're not reversing it.  Convert it to a `chainhash.Hash` first with:

```
blockHash, err := chainhash.NewHash(getTxResponse.GetBlockHash())
// handle err
fmt.Println(blockHash)
```

**Comment by jrick** [comment]
This is fixed as of github.com/decred/dcrwallet/wallet v1.1.2.
