### ISSUE TITLE
signrawtransaction should automatically import any redeemscripts that are passed

### ISSUE THREAD

**Issue by cjepson** [decred/dcrwallet#137]
It is possible to pass redeemscripts to signrawtransaction input in the legacy RPC to sign txIns using scripts offline, but the signing fails because the scripts are not first imported into the wallet.

**Comment by jrick** [comment]
I disagree that they should be automatically imported into the wallet.  That is what what importscript is for.

signrawtransaction has this dual nature of being both a way to sign transactions belonging to the wallet, as well as being a "library" for offline signing by passing all required secrets as parameters.  the RPC needs to use this data when it is passed, but it should not be added to the wallet.

Here you can see it using the provided redeem scripts, but only when additional keys have also been passed: https://github.com/decred/dcrwallet/blob/0246a18/wallet/wallet.go#L3397

If we change that to always use all passed extra values then the signatures should always be able to be created without importing the data.

**Comment by jrick** [comment]
Not sure why this wasn't closed earlier, but this isn't happening.
