### ISSUE TITLE
Dcr Wallet - Block sync loading page Redesign

### ISSUE THREAD

**Issue by theNerdyHulk** [decred/dcrwallet#1377]
What if the empty spaces below the progress bar can be used to explain some few concepts about the Decred ecosystem? So I designed this.  
There are up to 4 different pages with 10 cards each to describe different concepts about Decred.
Those design cards will keep the user informed and educated while he/she waits for the wallet to sync up to the latest blockchain state. 

![decreedd](https://user-images.githubusercontent.com/17684792/51945761-d8b77a80-241f-11e9-919b-5865b31aba41.png)

**Comment by alexlyp** [comment]
Please open this issue again in github.com/decred/decrediton

**Comment by theNerdyHulk** [comment]
> github.com/decred/decredito

Okay. Done.
