### ISSUE TITLE
Need way to force avoiding cointype upgrade after seed restore

### ISSUE THREAD

**Issue by jrick** [decred/dcrwallet#1389]
Voting wallets which use P2SH (VSPs most commonly, but also possible for solo stakers) do not have any activity on their P2PKH account addresses.  This can cause an unintentional cointype upgrade (from legacy to SLIP0044) to occur after a seed restore, causing the restored wallet to not hold any of the keys required to sign votes.

A config option to prevent the automatic cointype upgrade is probably the simplest and best solution.

**Comment by chappjc** [comment]
As a workaround, send something to an address for the default account (prior to seed restore).

**Comment by jrick** [comment]
That's a bad solution for voting wallets as they should not have any hot funds.  Fix coming soon.

**Comment by chappjc** [comment]
Yeah, but it's _a_ solution.  This was an issue for ages.
