### ISSUE TITLE
JSON-RPC Server Does not properly return WWW-Authenticate header

### ISSUE THREAD

**Issue by davecgh** [decred/dcrwallet#14]
As the title says, the JSON-RPC server should be returning a WWW-Authenticate header when it receives invalid credentials.

See the btcsuite/btcd code here for the proper handling:
https://github.com/btcsuite/btcd/blob/528ddaf23e0a68666a9992b81f978e49e2c61f5e/rpcserver.go#L3895-L3899

**Comment by jcvernaleo** [comment]
It looks like we inhereted our current behavior from btcwallet.  I opened btcsuite/btcwallet#351 with this change and once I see what @jrick says there I can get it in dcrwallet.

**Comment by jcvernaleo** [comment]
This is fixed in the latest master.
