### ISSUE TITLE
-4: not enough to purchase sstx when balance > ticket price

### ISSUE THREAD

**Issue by DavBE** [decred/dcrwallet#140]
dcrctl --wallet getstakeinfo
{
  "poolsize": 41523,
  "difficulty": 10.92212546,
  "allmempooltix": 12,
  "ownmempooltix": 0,
  "immature": 14,
  "live": 0,
  "proportionlive": 0,
  "voted": 0,
  "totalsubsidy": 0,
  "missed": 0,
  "proportionmissed": 0,
  "revoked": 0
}

dcrctl --wallet getbalance
11.87407338

dcrctl --wallet purchaseticket default 13
-4: not enough to purchase sstx

**Comment by jcvernaleo** [comment]
Is you balance in the default account or is some of it elsewhere?  You can check with:
dcrctl --wallet listaccounts

**Comment by DavBE** [comment]
dcrctl --wallet listaccounts
{
  "default": 11.87407338,
  "imported": 0
}

**Comment by DavBE** [comment]
I have a bit more now in my wallet :

dcrctl --wallet listaccounts
{
  "default": 12.41611987,
  "imported": 0
}

but still won't purchase :

dcrctl --wallet purchaseticket default 15
-4: not enough to purchase sstx

**Comment by DavBE** [comment]
running "consolidate 12" in terminal mode solved the issue.
