### ISSUE TITLE
add coin type to grpc api

### ISSUE THREAD

**Issue by raedah** [decred/dcrwallet#1422]
This was previous brought up. Creating an issue to track the outcome. There is currently no way to extract the actual coin type from dcrwallet. New wallets are 42 but older seeds can be 20.

Decrediton does talk to dcrwallet with the api and decrediton doesnt have access to know the actual coin type.

dcrlibwallet apps would be able to access the info through the dcrwallet pkgs directly though

**Comment by githubsands** [comment]
I can handle this.

**Comment by ReevesAk** [comment]
Seems #1424 has been abandoned. Want to put up a fix for this.
