### ISSUE TITLE
Enter passphrase change without it being echoed to screen

### ISSUE THREAD

**Issue by Arriu** [decred/dcrwallet#1430]
Right now the command to change the wallet passphrase is:
dcrctl --wallet walletpassphrasechange "old" "new" 
this requires both the old and new passphrase to be typed and entered visibly in the CLI.
I tried making it work with promptsecret in the following ways, but none were successful
promptsecret | dcrctl --wallet walletpassphrasechange - -
promptsecret | dcrctl --wallet walletpassphrasechange -
promptsecret | promptsecret | dcrctl --wallet walletpassphrasechange - -
It was pointed out to me by @vctt94 in Matrix that Promptsecret only accepts one argument. I'll hold off on making an issue in dcrd requesting the necessary changes to promptsecret until someone here responds that that would be the optimal approach.

**Comment by vctt94** [comment]
I can take this one

**Comment by jrick** [comment]
Nothing to change here in this repo.  Will be resolved by decred/dcrd#1705.
