### ISSUE TITLE
Add address discovery progress notification

### ISSUE THREAD

**Issue by itswisdomagain** [decred/dcrwallet#1434]
FetchMissingCFilters, FetchHeaders and Rescan have notification callback methods for reporting progress. The information provided in those Progress callbacks can be used to estimate how long each operation may take.

Can a similar provision be made for address discovery?

**Comment by jrick** [comment]
There's no (reasonable) upper bound on how many addresses might be discovered.  You could report how many have been discovered so far, but it would not be possible to implement progress bar, for example.

**Comment by jrick** [comment]
Address discovery is also not a linear search, but logarithmic.  Account discovery is currently linear, but that could also be made logarithmic if necessary.

**Comment by itswisdomagain** [comment]
I understand. Closing this issue.
