### ISSUE TITLE
Dcrwallet RPC not responding from remote machine.

### ISSUE THREAD

**Issue by nandubatchu** [decred/dcrwallet#1436]
I tried to use the following config to spin up the dcrwallet instance on Digital Ocean:
```
username=USERNAME
password=PASSWORD
appdata=<DATA_FOLDER>
rpclisten=:9110
rpcmaxclients=40
```
I am able to see that it successfully syncs with dcrd instance and am able to query the RPC endpoint via localhost. But not able to reach the specific port or RPC endpoints from remote machine.

I am using the same config file on one of the AWS machine currently which works completely fine.

**Comment by jrick** [comment]
Your configuration is correct (the RPC server is binding to all interfaces instead of just loopback).  Check your firewall?

**Comment by nandubatchu** [comment]
@jrick I don't have any firewall setup. All the ports are open.

**Comment by jrick** [comment]
Can you confirm from the logs that the RPC server is listening on all interfaces? It should read something like

> [INF] RPCS: Listening on [::]:9110

**Comment by nandubatchu** [comment]
@jrick my mistake, I did not check the ufw status. UFW (Uncomplicated Firewall) was enabled by default on the digital ocean droplet.

Thank you.
