### ISSUE TITLE
wallet cannot restore correctly from seed

### ISSUE THREAD

**Issue by imnisen** [decred/dcrwallet#1460]
https://github.com/decred/dcrwallet/blob/1da2c8bb3bf99ac34f426f49602c7a7c2107561d/walletsetup.go#L84

Hi, I want to ask why only not exported seed call `UpgradeToSLIP0044CoinType`. 
When I created a new wallet(an offline code wallet), it generated the seed "SEED1". After the wallet creation, I started the wallet service, the use dcrctl to `getmasterpubkey` from the wallet, it outputs pubkey "PK1".

Then I deleted all the dcrwallet directory and created a new a new wallet from seed "SEED1", however, after run the wallert, use dcrctl to `getmasterpubkey` from the wallet, it outputs "PK2". Here is the question, PK1 != PK2.

I want to know how to deal with this problem because I want to use "cold wallet" to sign transactions but it cannot recognize the address due to this problem. 

Thanks!

**Comment by jrick** [comment]
We always create wallets with new seeds using the SLIP0044 cointypes but for backwards compatibility with older seeds, we do not do this upgrade when a seed is imported during a restore.  When the restored wallet performs its first rescan and address discovery steps, and no transactions are found for the legacy cointype, the upgrade will be automatically performed.  This is obviously an issue for offline restored wallets as they would never trigger the upgrade.

For now you can work around this by removing the !imported condition for the upgrade, and then restore again with the modification.

This will need some discussion over the best way to handle the case for users who can not build from source for the workaround.  Two potential ways:

* Add an additional prompt during restore asking for something like "was this seed created by version *something* or earlier?" or "is this a non-SLIP0044 seed?"
* Add an RPC to perform the upgrade

**Comment by imnisen** [comment]
I understand it now.  It's quite confusing at the beginning since my wallet's master public key changed after connecting to dcrd to scan the block.

Thank you very much!
