### ISSUE TITLE
SSL wrong curve using NodeJS client

### ISSUE THREAD

**Issue by Mukul-Sharma** [decred/dcrwallet#1467]
Node Version: v10.13.0
dcrwallet version 1.4.0+release (Go version go1.11.5)

Using sample code from RPC client documentation for NodeJS client throw SSL handshake error

ssl_transport_security.cc:1233] Handshake failed with fatal error SSL_ERROR_SSL: error:1414D17A:SSL routines:tls12_check_peer_sigalg:wrong curve.

**Comment by jrick** [comment]
Remove the existing cert/keys and rerun with --tlscurve=P-256.  This should become the default (see #1461).
