### ISSUE TITLE
Allow changeable scrypt parameters

### ISSUE THREAD

**Issue by matheusd** [decred/dcrwallet#1470]
The key derivation function (`scrypt`) and parameters (`P=1, N=8, N=2^18`) used for encrypting the master keys are currently hard coded in the udb package (https://github.com/decred/dcrwallet/blob/706a9de881311469234415187904f688f6b21633/wallet/udb/addressmanager.go#L119).

Ideally, these parameters should be settable externally, so that:
  - External tests that create wallets can run using lower parameters, making them faster and less memory intensive;
  - The parameters can be upgraded (either at the user's request or automatically) if they are deemed too insecure.

In order to allow that, we need to:
  - Store the algo and parameters used in a particular wallet (in the wallet db) so that future upgrades are possible;
  - Provide a wallet-level API to set these parameters at wallet creation time;
  - Provide an address manager-level API to update these parameters;
  - (Maybe) provide a wallet-level API to change the parameters during a passphrase change or with a specific API call

The last point isn't strictly needed since we can do upgrades during any wallet unlocking operation (though we might wanna consider making this an opt-in change for end users).

This change needs to be able handle different algorithms (since we might wanna upgrade to [argon2](https://godoc.org/golang.org/x/crypto/argon2) or some other key derivation algo in the future).

**Comment by matheusd** [comment]
Unfortunately, for the moment the only way to cleanly implement this is by doing a breaking change in `udb.Initialize` (and consequently in `wallet.Create`) with an accompanying major version bump.

@jrick mentioned eventually making `udb` (and maybe `loader`?) as internal packages, so that's probably best implemented during/after that change.

**Comment by jrick** [comment]
Correct.  The only thing preventing udb from becoming internal right now is that the wallet package exposes udb types in its functions.  Most of the package is already unusable due to the walletdb buckets passed as the first parameter to db-using functions.

**Comment by jrick** [comment]
Now is a good time to work on this if you'd like, while the wallet package has not been tagged in a decred.org/dcrwallet module release.
