### ISSUE TITLE
Wallet doesn't close cleanly on ctrl+D with the "--promptpass" option

### ISSUE THREAD

**Issue by cjepson** [decred/dcrwallet#149]
Sending EOF with ctrl+D results in an infinite loop where the user must continue to try to re-enter the passphrase when --promptpass is on. Because after loader handling function in wallet/loader.go doesn't have any error handling, it's impossible to cleanly return from a failure in input and close the wallet.

**Comment by dajohi** [comment]
Not reproducible.   Was it fixed or is this a local issue?

**Comment by dajohi** [comment]
EOF just reprompts for the passphrase.  @cjepson is ok with that.
