### ISSUE TITLE
Wallet "resyncAccounts" variable can be replaced with check for whether or not wallet is unlocked

### ISSUE THREAD

**Issue by cjepson** [decred/dcrwallet#152]
https://github.com/decred/dcrwallet/blob/master/wallet/wallet.go#L115

The setting of this variable can be replaced by a check for whether or not the wallet is unlocked, instead of using an exported API.

https://github.com/decred/dcrwallet/blob/master/wallet/wallet.go#L369-L375

**Comment by jrick** [comment]
Old issue, this is already implemented.
