### ISSUE TITLE
balancetomaintain needs bounds checking

### ISSUE THREAD

**Issue by chappjc** [decred/dcrwallet#153]
Really large number for balancetomaintain is not handled well:

`balancetomaintain=99999999999999`

gives:

`[INF] WLLT: Stake mining is enabled. Votebits: 1, minimum wallet balance -9.223372036854776e+10`

**Comment by cjepson** [comment]
This was noted earlier. The NewAmount function is buggy. We're looking into fixing it.

**Comment by chappjc** [comment]
Oh, I didn't see the earlier one.  Sorry.

**Comment by cjepson** [comment]
It was in an internal office discussion iirc so you could not have known. :) No worries, we're working on fixing it and it's good to have an issue.

**Comment by jrick** [comment]
This option no longer exists.

**Comment by raedah** [comment]
it became ticketbuyer.balancetomaintainabsolute so probably applies to that
