### ISSUE TITLE
registering notify events on dcrwallet is no more working since 0.0.9

### ISSUE THREAD

**Issue by tpruvot** [decred/dcrwallet#154]
Only tested OnBlockConnected...

That still works on dcrd, i don't know if its normal... so i report here

**Comment by cjepson** [comment]
I believe @jrick removed the wallet websocket notifications on the latest release, because they are deprecated in btcwallet.

**Comment by jrick** [comment]
Not just deprecated. they were an undocumented feature (a leftover from the btcgui days).  There was also no registration.  Those notifications were sent to every websocket client unsubscribed whether they wanted them or not.  If they return to the legacy JSON-RPC API, there should be an explicit registration for them.

Notifications are documented and supported for the gRPC API if you need them.

**Comment by jcvernaleo** [comment]
So as @jrick pointed out, the current behavior is correct and the previous behavior was a relic of btcgui so I'm closing this issue.  If you have any problem with getting things working with gRPC, please feel free to open a new issue.
