### ISSUE TITLE
dcrwallet should have a transaction fees check which prevents too high fees

### ISSUE THREAD

**Issue by cjepson** [decred/dcrwallet#156]
Right now it is possible to create transactions in wallet with fees that are not logical, for example consume all the inputs. There should be a check in wallet during transaction creation to ensure that fees in the transactions are not above some threshold fees per KB. If this is the case, the transaction should be rejected.

**Comment by alexlyp** [comment]
dcrd PR https://github.com/decred/dcrd/pull/124 fixes this
