### ISSUE TITLE
Golang non-standard function names and improperly exported variables

### ISSUE THREAD

**Issue by cjepson** [decred/dcrwallet#157]
The Wallet struct in wallet/wallet.go has a number of improperly exported variables that need their own functions for accession, like "StakeMiningEnabled". The functions allowing for their accession are also improperly named, like "GetCurrentVotingInfo".

**Comment by jrick** [comment]
We'll fix these as we run into them.  A single issue covering the entire codebase about naming issues isn't terribly useful.
