### ISSUE TITLE
dialog, use existing configured _ password

### ISSUE THREAD

**Issue by raedah** [decred/dcrwallet#162]
In the following dialog, I believe it was meant to say "Use the existing configured private passphrase for"   instead of  "Use the existing configured public passphrase for"

$ ./dcrwallet --create
Enter the private passphrase for your new wallet: 
Confirm passphrase: 
Do you want to add an additional layer of encryption for public data? (n/no/y/yes) [no]: yes
Use the existing configured public passphrase for encryption of public data? (n/no/y/yes) [no]: 
Enter the public passphrase for your new wallet: 
Confirm passphrase:

**Comment by chappjc** [comment]
No that's actually asking about the public passphrase.  Specifically, it finds the walletpass setting in your dcrwallet.conf and it gives you this prompt to optionally use it instead of a new one.

**Comment by raedah** [comment]
oh ok, how about adding that to the string then.
"Use the public passphrase found in dcrwallet.conf for encryption of public data?"

**Comment by chappjc** [comment]
I guess you could make a pull request if you feel strongly, but I would also use `walletpass` in the message to further avoid confusion.
