### ISSUE TITLE
Please Help Me Revoke An Expired Ticket

### ISSUE THREAD

**Issue by gratefuldave11** [decred/dcrwallet#1640]
![decred_ticket](https://user-images.githubusercontent.com/59931468/72458030-11617880-3785-11ea-8032-714fdb0f8123.png)
I appreciate everyone's time.  . I have an expired ticket but i'm not seeing a revoke button. I recall one being there a couple weeks ago, but when i upgraded the wallet to 1.5 it seems to have disappeared.

I show current total balance 127.18 Available 6.93 Locked 120.24

I see the tree on the left.
Overview Transactions Governance Tickets > I hit tickets. > My tickets and I see three tickets. Two are green that I voted on. One is grey. When I click on that it says Transaction: with a link https://dcrdata.decred.org/tx/a40acdf8b6f09574902188f5b64b2b15cfe866746ef0f085257cd995026b9c38

I'm not seeing a revoke button anywhere. Any thoughts? I appreciate your time.

**Comment by alexlyp** [comment]
You should see a revoke button on The tickets/Purchase tab.  And if you don't you're probably in SPV mode.  Flip to full mode and let it resync and look for it there.   I'm closing this issue, since this isn't an appropriate dcrwallet issue.  Please come to the support channel at matrix.decred.org for any further help.

**Comment by gratefuldave11** [comment]
> matrix.decred.org

Thank you.  I appreciate your time.  Been trying to get past this for 3 weeks now.  Sorry if I asked in the wrong place.  matrix.decred.org does not seem to be a working link.

Back to the issue.  I don't see a revoke button. 
I clicked on settings and it says SPV disabled.
Not sure if that means i'm in full mode?

Any further assistance is greatly appreciated.  I'm just trying to get my decred to show up in Available in my wallet.

thx again for your time

Dave

**Comment by matheusd** [comment]
https://chat.decred.org/
