### ISSUE TITLE
Simplify repo module structure

### ISSUE THREAD

**Issue by jrick** [decred/dcrwallet#1641]
The current module system used in the dcrwallet repo is more of a burden than a help at times.  This is mostly due to tight coupling between the very large api surface of the wallet submodule, and other submodules which use it in public api (chain, spv, and ticketbuyer).  Each time the wallet module must be major bumped, each of these submodules must be bumped as well.  It it more logical to version these packages together as a single unit.

Due to the way Decred versions its executables, we have avoided including library code in the same module which contains the dcrwallet main package, so that it may be versioned separately without concern about breaking changes in libraries.  For now, this requirement must still be kept.  Up until now, this has been done by creating submodules in each non-internal directory under the repo root, so they are not part of the same module as the main package.  However, this causes many more modules than desired.

An alternative solution would be move library code under the decred.org/dcrwallet module, and define a submodule decred.org/dcrwallet/cmd/dcrwallet, which is versioned together with the rest of the Decred executables.  The idea here is rather than isolating the main package by individually creating submodules of its subpackages, move the package we wish to isolate deeper in the directory structure, with all other code versioned together.

To recap, the current module structure looks like:

decred.org/dcrwallet
github.com/decred/dcrwallet/chain
github.com/decred/dcrwallet/cmd/movefunds
github.com/decred/dcrwallet/cmd/sweepaccount
github.com/decred/dcrwallet/deployments
github.com/decred/dcrwallet/errors
github.com/decred/dcrwallet/lru
github.com/decred/dcrwallet/p2p
github.com/decred/dcrwallet/pgpwordlist
github.com/decred/dcrwallet/rpc/client/dcrd
github.com/decred/dcrwallet/rpc/jsonrpc/types
github.com/decred/dcrwallet/rpc/walletrpc
github.com/decred/dcrwallet/spv
github.com/decred/dcrwallet/ticketbuyer
github.com/decred/dcrwallet/validate
github.com/decred/dcrwallet/wallet
github.com/decred/dcrwallet/walletseed

and following this change, the modules would instead look like:

decred.org/dcrwallet
decred.org/dcrwallet/cmd/dcrwallet
decred.org/dcrwallet/cmd/movefunds
decred.org/dcrwallet/cmd/sweepaccount
decred.org/dcrwallet/rpc/jsonrpc/types (maybe)
decred.org/dcrwallet/rpc/walletrpc (maybe)

**Comment by davecgh** [comment]
I don't have any major objections, however, I would like to point out that it does come with a few downsides as well such as:

1. You could no longer simply go install from the root to install the main executable
2. Overrides specified in the root would no longer be applied when building the executable meaning the code the executable is built with would not match what CI is testing unless extra care is taken to ensure overrides in both places.
3. As the main `dcrwallet` module has its major bumped, it can lead to a confusing series of commands such as:
```
$ go get decred.org/dcrwallet@4.0.1
$ go install decred.org/dcrwallet/cmd/dcrwallet
$ dcrwallet -V
dcrwallet version 1.6.0-pre+dev (Go version go1.13.5 linux/amd64)
```
4. It will significantly increase the public API surface of the main `dcrwallet` module due to having a bunch of sub packages all in the same module, meaning it will very likely lead to a lot more major version bumps, which is harder for consumers of the code in addition to the previous point

**Comment by chappjc** [comment]
dcrdata is importing github.com/decred/dcrwallet/wallet/v3 (for txrules)
dcrdex is also using txrules, plus github.com/decred/dcrwallet/rpc/jsonrpc/types

**Comment by davecgh** [comment]
Since the `rpc/jsonrpc/types` modules is needed by dcrd, I would very strongly want to retain that module.  I mention this because I see it marked `(maybe)`.  I 100% don't want to have to significantly increase the dependency graph of dcrd.  I don't consume the `decred.org/dcrwallet/rpc/walletrpc` from dcrd, so that one I'm not really concerned about personally.

**Comment by jrick** [comment]
Solid points @davecgh.  In response:

1. This can be still be accomplished, but with a different command:

    `$ (cd cmd/dcrwallet && go install)`

2. The decred.org/dcrwallet/cmd/dcrwallet module can define its own overrides.

3. The versioning is already confusing because we require using the same versions for all executables across the project, where everything else has semver semantics.

4. When major bumps are unavoidable, most modules already need a major bump also due to the tight coupling.

Regarding the (maybe) modules both of you consume, those packages aren't going away.  While the module dependency graph would increase (because of transient packages), the package graph during builds and tests would not.

**Comment by jrick** [comment]
Here is an example of what I meant about the distinction between module requires and imported packages.  Without creating any submodules for those "(maybe)" packages, we see this when updating dcrctl:

```
$ pwd                      
/home/jrick/src/dcrd/cmd/dcrctl
$ go list all > /tmp/before
$ gofmt -w -r '"github.com/decred/dcrwallet/rpc/jsonrpc/types" -> "decred.org/dcrwallet/rpc/jsonrpc/types"' *.go
$ go mod edit -replace=decred.org/dcrwallet=$HOME/src/dcrwallet
$ go list all > /tmp/after
$ diff -u /tmp/{before,after}
--- /tmp/before	2020-01-16 09:21:16.000000000 -0500
+++ /tmp/after	2020-01-16 09:22:00.000000000 -0500
@@ -32,6 +32,7 @@
 crypto/tls
 crypto/x509
 crypto/x509/pkix
+decred.org/dcrwallet/rpc/jsonrpc/types
 encoding
 encoding/asn1
 encoding/base32
$ 
```

(I think the old types package is also being imported by dcrjson, which is why you don't see it removed from just listing the dcrctl packages.)

Although there are now more required modules, the actual packages used during builds and tests would not increase.  This means that although the decred.org/dcrwallet module requires projects like gRPC and bbolt, they are only requires, and because the packages from the dcrwallet module that dcrd imports do not import them, they will not affect dcrd builds.

**Comment by jrick** [comment]
I am currently debating whether the dcrwallet main package should be a separate submodule as originally specified in this issue, or be contained in the repo's module.  I see some upsides and downsides to both ways.

Upsides:

* Local file replaces will on longer be necessary.

* The dcrwallet executable can be installed from the root of the repo without cd'ing into the submodule.  As a submodule, this does not work:

    ```
    $ go install ./cmd/dcrwallet
    go: directory cmd/dcrwallet is outside main module
    ```

* It will be possible to use `go get` to build `@master`, and actually build with the code currently in master, because there will not be any local file replaces in the go.mod.

Downsides:

* Installing the wallet command through `go get` will require knowing the module's major version, as it must appear in the package path for `go get`.  This can be referenced in the repo's README, but may require one to look up the current version to use.

* The module version embedded into the executable (which is viewable with `go version -m dcrwallet`) will be the semver version.  This is mostly a cosmetic difference that most users won't see, and the reported version from `dcrwallet -V` will remain the same as before.  Some might even consider this an upside, but it does mean that if in the future, Go applications can query their own module versions, we will not be able to use this version as the `dcrwallet -V` output.

* Releasing versions of the module will require tagging the repo as `vX.Y.Z`.  These tags must follow semantic versioning, which differs from the current `vX.Y.Z` tagging scheme currently used, where the version is the "Decred release version" and is updated in lockstep with all other Decred tools.  I can see this causing confusion as it would require going back to a `release-vX.Y.Z` tagging scheme for the "Decred release version" in addition to placing semver tags on the repo.

**Comment by matheusd** [comment]
On the downsides:

What about offering `decred.org/cmd/[x] modules? They would be tagged following the "Decred release version" and would be very simple (similar to the release tool). The wallet could be a single module and we guarantee there are no local replacements in release-ready versions.

**Comment by jrick** [comment]
Correct me if i'm wrong, but wouldn't that involve moving all of the code from the main package outside of this repo? I'm not sure that's something we wish to do.

**Comment by matheusd** [comment]
`decred.org/cmd/[x]` would only have a simple shim calling the "real" main. 

Basically move this function: https://github.com/decred/dcrwallet/blob/master/dcrwallet.go#L45-L55 to call a hypothetical `decred.org/dcrwallet/v2/cmd/dcrwallet.DcrwalletMain(ctx)`.

**Comment by jrick** [comment]
It's not allowed to import main packages, so this would involve losing the main executable from this repo.  I don't see any significant difference between this and the original design described in the issue except that it moves the executable package outside of the repo.

**Comment by matheusd** [comment]
You'd have `./cmd/dcrwallet` with the same simple, shimmed main func in a main package that we'd use during development, would _not_ be a separate module (so respects all replacements in the root module of the dcrwallet repo) and calls the "real" main in either the root module (package decred.org/dcrwallet) or on a separate "pseudo-main" package (for example package decred.org/dcrwallet/(loader|main|pseudomain|exec|whatever)). 

You'd end up with two different places that can generate a "dcrwallet" binary: the `decred.org/dcrwallet` repo/module (exclusively semver tagged, via `decred.org/dcrwallet/cmd/dcrwallet`) and `decred.org/cmd/dcrwallet` (release-tagged).

**Comment by jrick** [comment]
So two main packages per tool.  I could see that working, but it might be just as confusing to users and those looking to build the project as having two tagging conventions (perhaps even more, because they would have to determine which package they want to build).  Another issue is that not all other Decred projects may be onboard with doing similar, and I don't want dcrwallet to be the only tool which follows this model.

**Comment by jrick** [comment]
One other possibility (some might call it an advantage, others may not care for it) with dcrwallet in the sole repo module is that we would not need to drop it into a subdirectory, and it would be built with the same package path as currently.

**Comment by matheusd** [comment]
> but it might be just as confusing to users and those looking to build the project...

Right, that would only be a reasonable solution if pretty much every public-facing tool used this scheme and we only prominently linked/advertised installing officially released versions via `decred.org/cmd/[x]`.

>  as having two tagging conventions

I guess this ship has sailed? I mean, we're pretty much forced to do this unless we completely disregard semver for go modules (which I don't think anyone is advocating for).

**Comment by jrick** [comment]
> I guess this ship has sailed? I mean, we're pretty much forced to do this unless we completely disregard semver for go modules (which I don't think anyone is advocating for).

No we're not going to disregard semver.

We could avoid two different tagging conventions in the same repo, by using multiple repos as you suggested.  I'm just not convinced it's really any better or worse.

**Comment by jrick** [comment]
Another argument for putting the main executable in the sole module is it becomes much clearer what versions of required modules end up as part of a build.  For example, I just looked over my own PR implementing the design described in the original issue and each module requires a different version of grpc (v1.25.1 in decred.org/dcrwallet and v1.26.0 in decred.org/dcrwallet/cmd/dcrwallet).  By only maintaining a single module in the repo, there is little room to sneak in a module upgrade or to have mismatched versions between the modules.

This advantage is only really possible when there is just one module, and defining a executable submodule or using a separate repo introduces another place for required version differences.

**Comment by jrick** [comment]
I've updated #1642 with the module consolidation discussed here today.  Testing and feedback still welcome.
