### ISSUE TITLE
wallet cannot run

### ISSUE THREAD

**Issue by Seymour-w** [decred/dcrwallet#1686]
Hi all,
  Previously backed up .db files, dcrwallet cannot run. ERROR:
2020-03-05 11:44:40.293 [INF] DCRW: Version 1.5.0-pre+dev (Go version go1.13 linux/amd64)
2020-03-05 11:44:41.340 [INF] WLLT: Opened wallet
panic: runtime error: slice bounds out of range [128:0] [recovered]
	panic: runtime error: slice bounds out of range [128:0]

goroutine 1 [running]:
main.run.func4(0xc0003f8d00)
	/home/stupool/dcrd/src/github.com/decred/dcrwallet/dcrwallet.go:175 +0x1a8
panic(0xcca140, 0xc00017e7e0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/decred/dcrwallet/wallet/v3/udb.extractBlockHeaderHeight(...)
	/home/stupool/dcrd/src/github.com/decred/dcrwallet/wallet/udb/txmined.go:473
github.com/decred/dcrwallet/wallet/v3/udb.(*Store).MainChainTip(0xc0000a85f0, 0x7f485b2f6970, 0xc00017c480, 0x0, 0x0, 0x0, 0x0, 0xc00026e0e0)
	/home/stupool/dcrd/src/github.com/decred/dcrwallet/wallet/udb/txmined.go:178 +0x197
github.com/decred/dcrwallet/wallet/v3.(*Wallet).MainChainTip.func1(0xfde620, 0xc000010048, 0xd4194a, 0x9)
	/home/stupool/dcrd/src/github.com/decred/dcrwallet/wallet/wallet.go:439 +0xa0
github.com/decred/dcrwallet/wallet/v3/walletdb.View(0xfea7c0, 0xc00017c2c0, 0xfeb380, 0xc0001cc800, 0xc000283988, 0x0, 0x0)
	/home/stupool/dcrd/src/github.com/decred/dcrwallet/wallet/walletdb/interface.go:219 +0x1e4
github.com/decred/dcrwallet/wallet/v3.(*Wallet).MainChainTip(0xc00022d340, 0xfea7c0, 0xc00017c2c0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/stupool/dcrd/src/github.com/decred/dcrwallet/wallet/wallet.go:437 +0xac
github.com/decred/dcrwallet/wallet/v3.(*Wallet).NeedsAccountsSync(0xc00022d340, 0xfea7c0, 0xc00017c2c0, 0x0, 0x1, 0x10)
	/home/stupool/dcrd/src/github.com/decred/dcrwallet/wallet/wallet.go:4416 +0x46
main.startPromptPass(0xfea7c0, 0xc00017c2c0, 0xc00022d340, 0x1, 0xc00017c201, 0xc0000b3ee8)
	/home/stupool/dcrd/src/github.com/decred/dcrwallet/dcrwallet.go:420 +0x77
main.run(0xfea7c0, 0xc00017c2c0, 0x0, 0x0)
	/home/stupool/dcrd/src/github.com/decred/dcrwallet/dcrwallet.go:243 +0x185f
main.main()
	/home/stupool/dcrd/src/github.com/decred/dcrwallet/dcrwallet.go:52 +0x81

Is this a dcrwllaet software version mismatch? Or the .db file is corrupted.
Please help me !  
Thanks!

**Comment by jrick** [comment]
Possibly corruption but can't tell from just this.  What happened is that it read an empty value of the db which should exist but clearly doesn't.  This could be corruption of the key (so the lookup is for the wrong thing) or the db itself corrupted to the point of losing the value for the key.

You should update to the latest software and try again.  If that still does not work, a reseed will be required.

**Comment by jrick** [comment]
closing due to lack of actionable info or any followup.
