### ISSUE TITLE
getaddressesbyaccount returns unused addresses from the address pool

### ISSUE THREAD

**Issue by cjepson** [decred/dcrwallet#17]
The cursor for new addresses from the default account is correctly incremented for the getnewaddress function, but it is possible to get a list of used and unused addresses from the getaddressesbyaccount. The getaddressesbyaccount call should also take into account the current cursor of the address pool and not return unused addresses. Without this, the user becomes in danger of reusing their addresses.

**Comment by dajohi** [comment]
@cjepson says this was fixed already.
