### ISSUE TITLE
Sidechains aren't loaded after startup in SPV mode

### ISSUE THREAD

**Issue by matheusd** [decred/dcrwallet#1710]
Maybe related to #1630 and #1707 

After fully starting up, if the wallet gets a sidechain, it fails to reorganize to it. Only happens in SPV mode. Restarting the wallet afterwards solves the issue. Steps to reproduce in simnet with 2 parallel nodes+wallets 

- Connect wallet A to node A and wallet B to node B (wallet B in spv mode, debuglevel=debug)
- Connect Node B -> Node A and let them sync
- Verify height (height `x`)
- Disconnect node B from node A
- Mine 2 blocks in node B (`x1 = x+2`)
- Mine 4 blocks in node A (`x2 = x+4`)
- Reconnect Node B -> Node A (B reorgs to `x2`)
- Notice the wallet logs a "Received sidechain or orphan block ... for height `x2`" but fails to actually fetch the `x..x2-1` headers and to reorganize to it.

Generating extra blocks doesn't help. Restarting the wallet fixes the issue. Running in RPC mode doesn't have this issue.

**Comment by jrick** [comment]
Well that's annoying.  Wallet's p2p package forbids sending a getheaders message after sendheaders has been sent (as the same blockheader messages are sent by peers for both synchronous block header requests and block announcements).  We might have to lift that restriction or change the protocol to push block header announcements for all of the new headers after the reorg, though I'm not sure changing the protocol is the right decision here.

cc @davecgh

**Comment by jrick** [comment]
I compared to bitcoind's net code and it looks like they do try to determine whether a peer should be sent all new headers after a chain tip change, rather than only being sent the tip header.

https://github.com/bitcoin/bitcoin/blob/312d27b11ceaacd3be75a14907f856352b7dcf48/src/net_processing.cpp#L1225-L1241

**Comment by jrick** [comment]
Well, I'm now looking through dcrd's code and not seeing why it wouldn't also be doing the same.  It sends block announcements with headers messages when blocks are accepted, not when they are connected, so it should be occurring on all valid blocks that may constitute the sidechain being reorganized to.

**Comment by matheusd** [comment]
Revisiting this since I bumped into it again and is an annoying issue when using `--spvconnect` with a single target node (since you'll never reconnect to it and thus do a getheaders again).

Here's a reproducer for it: https://github.com/matheusd/dcrwallet-spv-reorg

> It sends block announcements with headers messages when blocks are accepted, not when they are connected,

Various refactors around sync code in dcrd changed some aspects of this, but for current master, while it does send notifications on accepted blocks, it only does so when the server considers the chain _current_, and any new headers received bump up the `syncHeight` of the netsync manager, making it not consider itself current, thus dropping the notification.

Basically, [this check](https://github.com/decred/dcrd/blob/master/server.go#L2471) returns `false` for intermediate blocks during the reorg, so they are not relayed to the wallet.

Obviously, we don't just want to remove that check (or move notification to before it) since it would cause a lot of notifications during IBD. So fixing this in dcrd would require tracking more data from peers and/or adding more context to the block accepted notification (so we could differentiate between IBD and shallow-ish reorgs).

It seems to me the correct thing here would be to handle this in the wallet, and request the intermediate headers. Though as you noted earlier, this has the drawback of having to change the protocol to allow a `getheaders` to be sent after the `sendheaders` msg.

**Comment by matheusd** [comment]
Also, you don't even need a reorg to trigger this issue: having the dcrd node receive a bunch of headers at once (e.g. due to being disconnected from the network and then suddenly reconnected) already triggers it.

In my reproducer, that would be equivalent to just comment these [two lines](https://github.com/matheusd/dcrwallet-spv-reorg/blob/master/main_test.go#L79-L80).
