### ISSUE TITLE
rescanwallet performance

### ISSUE THREAD

**Issue by raedah** [decred/dcrwallet#1729]
Looking into rescanwallet performance. I see..

[TRC] WLLT: Attempted to insert SStx .... into the stake store, but the SStx already exists.

Msg's like this are shown many times. It likely takes many io operations to be searching for existing entries before inserting a new entry, and this is occurring while we are in the process of scanning from the beginning. If we started with a blank slate and added entries, there would be less time spent in confirming already existing data. Down side to this would be a lack of information being available while the rescan is proceeding.

**Comment by jrick** [comment]
The entire "stake store" was a hack tacked on and is unfit for use.  It needs to be removed.  There has been some recent-ish work towards avoiding and removing it (52ab64df13244d5b75ac8555d5664e4d03dd00d1).

**Comment by jrick** [comment]
design issues with the stake store aside, rescan performance is greatly improved on master after the update batching.  we can consider this fixed.
