### ISSUE TITLE
Add per-ticket vote preferences

### ISSUE THREAD

**Issue by jrick** [decred/dcrwallet#1736]
It would simplify the architecture of VSPs, potentially allowing for the removal of stakepoold from the stack, if the wallet was capable of recording vote preferences on a per-ticket basis.

Vote preferences in the wallet are currently configured using the RPCs:

```
$ dcrctl -l | grep votechoice
getvotechoices
setvotechoice "agendaid" "choiceid"
```

It would be possible to add an additional optional parameter to `setvotechoice` for the hash of a ticket.  This would record preferences for just that ticket when it is called to vote, and these preferences would override any global preferences currently configured.  `getvotechoices` likewise could gain an optional ticket hash parameter, in which case it would return the individual choices for that ticket, or fall back to the defaults if none are set.

This simplifies the VSP architecture by moving the responsibility of creating the votes in dcrwallet, instead of stakepoold creating unsigned votes and needing to perform RPC with the wallet to sign the transaction.

**Comment by itswisdomagain** [comment]
Can I take this up?
