### ISSUE TITLE
Unable to synchronize wallet to chain: failed to create initial waddrmgr address buffer

### ISSUE THREAD

**Issue by chappjc** [decred/dcrwallet#174]
When resyncing wallet, there is a WRN about a waddrmgr address buffer

```
[DBG] WLLT: Begin debug address scan scanning backwards from idx 3500, account 0, branch 0 Last used index found: 0    0
[WRN] WLLT: Unable to synchronize wallet to chain: failed to create initial waddrmgr address buffer for the address pool, account 0, branch 0: can not sync to lower index 20 from index 22
[INF] WLLT: The client has successfully connected to dcrd and is now handling websocket
```

**Comment by alexlyp** [comment]
Hmmm strange, are you connecting to a fully synced dcrd?

We have noticed an issue with address pools not being initialized correctly for cold wallets (connecting to chains that are empty)

**Comment by girino** [comment]
I've got this error when updating the wallet to the latest version. Rebuilding the wallet from seeds solved the issue.

To reproduce, try creating the wallet with v. 0.0.9, buiyng some tickets, then updating to 0.0.10

**Comment by chappjc** [comment]
@alexlyp, @cjepson said on IRC it was a known bug, and to make an issue.

**Comment by cjepson** [comment]
It is a bug. I accidentally forgot to duplicate some code on the second SyncAccountToAddrIndex call that handles the addrmgr being synced ahead of the pool.
