### ISSUE TITLE
connections to cspp block creating transactions via rpc

### ISSUE THREAD

**Issue by raedah** [decred/dcrwallet#1741]
It has been observed that trying to create transactions via rpc do not complete if the cspp client service is currently active on dcrwallet. In some cases it seems to block in the rpc cmds as well as the cssp client service, stopping all transactions from proceeding until dcrwallet is restarted. More context is needed on what is causing this to know if there are any workarounds, or what work is needed to not have it block rpc commands.

**Comment by jrick** [comment]
Running with the profiler (e.g. -pprof=[::1]:8080) is a good start, as you can grab all of the goroutine stacks without killing the process.  There won't be any information in this trace that would deanonymize a cspp user, except possibly how many outputs they might have currently being mixed.
