### ISSUE TITLE
rpc should not reflect invalid methods in console

### ISSUE THREAD

**Issue by degeri** [decred/dcrwallet#1756]
The RPC server should not be reflecting invalid method names.  Someone can inject some malicious or bad messages.

jsondata:

`{"jsonrpc": "1.0", "method": "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n THIS IS A BAD MESSAGE \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n", "params": ["12321321312", 0], "id": 1}`

![image](https://user-images.githubusercontent.com/41839293/84416380-6ad6b200-ac14-11ea-8adc-ad2dded856d5.png)

Either we should 

- Limit (length and allowed characters)
OR
- Reflect method name only for valid methods. And give a generic error for invalid methods.

https://github.com/decred/dcrwallet/blob/master/internal/rpc/jsonrpc/server.go#L242 ?

This is not really a risk imo. 

1. wallet rpc is almost never exposed to internet.
2. needs rpc password. 
3. requires a person to blindly trust the output.

**Comment by jrick** [comment]
It should be using the %q format string, which is the Go source code representation of the string and will be safe to print.  Newlines would appear as \n, for example.
