### ISSUE TITLE
cspp process limits

### ISSUE THREAD

**Issue by raedah** [decred/dcrwallet#1762]
ticketbuyer.limit=1
enableticketbuyer=1
mixchange=1

These settings are currently used with cspp. Limit should be set to 1 so as not to entangle multiple ticket purchases. Currently its possible for the user to set it other than one which weakens privacy. Limit of 1 should be enforced. This should be distinct from the actual number of tickets being purchased. The limit setting simply enforces that tickets should be purchased individually.

Enabling the ticketbuyer and change mixing are just boolean settings. What is needed is to be able to set how many tickets can be purchased per block (individual ticket purchases that are not entangled.)  As an extra note, floats could be used instead of whole numbers in order to have limits act within a set probability.

Cspp connections are also used for change mixing, so clear limits should be configurable for how many change mixing connections should be created at a time. This would be similar to the above mentioned setting for how many individual cspp ticket purchases to conduct per block. 

There should also be a setting for max number of connections being held open to a cspp server at one time. Im aware there is a circuitlimit setting, but this applies specifically to tor connections, not to cspp connection. Limiting open cspp connections will put an upper bound on the number of account addresses that can be used at one time.

**Comment by jrick** [comment]
Default mixed ticketbuying limit was changed by #1788.  We're not going to prevent you from using higher limits if you explicitly set them.
