### ISSUE TITLE
update help about fee increments

### ISSUE THREAD

**Issue by raedah** [decred/dcrwallet#178]
per comment, https://github.com/decred/dcrwallet/issues/171#issuecomment-208464728 , "value is also no longer used as an increment (it was in previous versions), so that help should be updated."

In the dcrwallet source tree, these are found,
$ grep 'increment used each time more fee is ' * -R
internal/rpchelp/helpdescs_en_US.go:  "infowalletresult-paytxfee": "The increm...
internal/rpchelp/helpdescs_en_US.go:  "settxfee--synopsis": "Modify the increm...
internal/rpchelp/helpdescs_en_US.go:  "setticketfee--synopsis": "Modify the increm...
rpc/legacyrpc/rpcserverhelp.go:  "paytxfee\": n.nnn,     (numeric) The increm...
rpc/legacyrpc/rpcserverhelp.go:  "settxfee":  "Modify the increm..
rpc/legacyrpc/rpcserverhelp.go:  "setticketfee":  "Modify the increm..

**Comment by alexlyp** [comment]
Gotcha

Ya I'll come up with something a bit more accurate and expressive to put there.  Thanks for the note.  A lot of the help has been lagging due to busyness elsewhere.  Hopefully get that up to snuff soon as well.
