### ISSUE TITLE
Attempting to create wallet when it already exists should display path.

### ISSUE THREAD

**Issue by davecgh** [decred/dcrwallet#18]
When attempting to create a new wallet with the `--create` when a wallet already exists, the application prints `The wallet already exists`.  This is obviously correct behavior, but I'd suggest this is changed to include the path since otherwise it can be difficult to know where the wallet lives.

So, for example:

`A wallet already exists at '/path/to/existing/wallet'`.

**Comment by jcvernaleo** [comment]
This was fixed and cherry-picked from upstream in a21e54375797c4d35201f1e41c10199bd174e72e
