### ISSUE TITLE
Mobile wallet issue !

### ISSUE THREAD

**Issue by ip-config** [decred/dcrwallet#1827]
Hello Decred.
I get this error message from the android wallet.
![decred](https://user-images.githubusercontent.com/12597726/90839824-b5815280-e358-11ea-92ee-03096c8aeb29.png)
could someone help 
regards

**Comment by raedah** [comment]
Wrong repo. Its over here https://github.com/planetdecred/dcrandroid

**Comment by ip-config** [comment]
Thank you

**Comment by ip-config** [comment]
> Wrong repo. Its over here https://github.com/planetdecred/dcrandroid

Thank you for your fast support,
