### ISSUE TITLE
payment of 0 is dust

### ISSUE THREAD

**Issue by raedah** [decred/dcrwallet#186]
-32603: -22: TX rejected: transaction --- is not standard: transaction output 0: payment of 0 is dust

I set settxfee 0, then used sendtoaddress and put in the entire balance of my wallet. The result  looks like it is trying to create a change output with the amount zero. The expected behavior for this case would be a transaction with no change output.

**Comment by jrick** [comment]
What version of the wallet are you running?

**Comment by raedah** [comment]
I am on Version 0.0.10-alpha.

Also note, when I change the sendtoaddress amount so that its not the entire amount in my wallet, I get this error which looks valid.
-32603: -22: TX rejected: transaction --- has 0 fees per kb which is under the required threshold amount of 1000000

**Comment by jrick** [comment]
That last error is expected.  You set a transaction relay fee of 0, but the mempool standard rules require transactions to pay at least 1e6 atoms (DCR 0.01) per kB of transaction.

**Comment by raedah** [comment]
Also interesting, attempting to send the entire wallet amount while using a valid txfee, returns a similar but different error.

-32603: transaction output is dust

**Comment by jrick** [comment]
The send{from,many,toaddress} RPCs are not intended to be used to sweep all outputs to a new, single output, as that requires slightly different transaction creation logic due to the way fees are calculated.  This functionality needs to be provided in a new RPC.

**Comment by cjepson** [comment]
-32603: -22: TX rejected: transaction --- is not standard: transaction output 0: payment of 0 is dust

The old version of wallet incorrectly added unspendable zero-value outputs to the wtxmgr. This is fixed in the latest version, but you will need to dropwtxmgr or restore from seed.

**Comment by jrick** [comment]
That's an output created by the latest wallet, not a transaction spending a previous output with a zero value.

**Comment by alexlyp** [comment]
PR #193 is a the cherry picked commit from btcwallet

**Comment by cjepson** [comment]
Oh, okay. Nice work.

**Comment by alexlyp** [comment]
#193 merged.  Closing issue
