### ISSUE TITLE
Getting new address every block

### ISSUE THREAD

**Issue by mverrilli** [decred/dcrwallet#190]
I have redundant wallets set up for stake mining.  Since upgrading to 0.1.0, I am seeing 1 new address allocated for every connected block. This is burning through many addresses. The pattern is as follows: 

```
18:49:37 2016-04-19 [INF] WLLT: Connecting block 00000000000004cef8fa6e6d04e05d5bac9138254d7baadd0fef7684dbd0d0e3, height 20765
18:49:37 2016-04-19 [DBG] WLLT: Get new address for branch 1 returned DsSomeAddressHere (idx 189) from the address pool
18:49:37 2016-04-19 [DBG] WLLT: Closing address batch for pool branch 1, next index 190
18:49:37 2016-04-19 [DBG] WLLT: Get new address for branch 1 returned DsSomeOtherNewAddressHere (idx 190) from the address pool
```

**Comment by alexlyp** [comment]
PR #191 fixes this issue.

If you can build from source this issue will be resolved.  The release that includes this should be out later this week or early next.
