### ISSUE TITLE
Expiry on tickets does not work if pool address is blank

### ISSUE THREAD

**Issue by cjepson** [decred/dcrwallet#197]
Passing a blank string should disable pool addresses, but still allow the user to set expiry. Right now it doesn't.

> purchaseticket default 1000 0 SsXieYaiuKSwQJ5niKdqp9bnzQeMGoxyoyP 3 "" 0 500
-5: Invalid address "\"\"": decode failed with `decoded address is of unknown format: invalid format: version and/or checksum bytes missing`

**Comment by alexlyp** [comment]
Fixed in #198
