### ISSUE TITLE
Add a way to disapprove blocks

### ISSUE THREAD

**Issue by matheusd** [decred/dcrwallet#1970]
This would be useful for simnet tests that involve using a real voting dcrwallet without having to hack around a new binary.

Some alternatives (possibly gated to only work on !mainnet):

- Add an RPC that can set the block approved voting bit for all blocks 
- Add an RPC that can set the voting logic to disapprove a specific block hash 
- Add an RPC that can set the voting logic to disapprove the _next_ (n?) block(s) to appear

**Comment by jrick** [comment]
we certainly want to be able to set rules/logic about what blocks to disapprove of (even on mainnet) but so far there haven't been any attempts to best define how we should do that.  The best idea so far has been single config settings which then run hardcoded logic (e.g. a setting to disapprove empty blocks if local mempool has txs).

**Comment by jrick** [comment]
If the goal is to simply encounter some disapproved blocks on simnet, maybe it should just be a percentage setting, where a random choice is made whether to approve or disapprove.  This would also facilitate voting control for all blocks by using 0 or 100%.

Of course something like this should only be allowed on simnet, and possibly testnet, but never mainnet.

**Comment by matheusd** [comment]
Right, I opened this specifically aiming to track that capability for {sim,test}net stuff, not the more general policies for mainnet. 

Using a percentage works for me, as long as I can modify it within a running wallet via an rpc/grpc call.

**Comment by JoeGruffins** [comment]
I would like to add this if no one is working on it.

**Comment by JoeGruffins** [comment]
@matheusd 
Is to disapprove a block the same as voting with a certain bit set? Would that bit be the last one here in the `VoteBits.Bits` which is `0x0001` and setting that to zero? I tried setting that on simnet but couldn't tell that any blocks were disapproved. It did affect the `votebits` in the header.

**Comment by jrick** [comment]
That's correct.

Did you run simnet past svh?

**Comment by JoeGruffins** [comment]
> Did you run simnet past svh?

Probably not. Will see what height that is... Using the dcrdex simnet harness, and it sometimes has trouble going too far/high, so may finally try to figure out what that is along the way.

**Comment by JoeGruffins** [comment]
Actually, yeah. Is 144 by default on simnet? I'll put up a pr doing this anyhow...
