### ISSUE TITLE
`sendtomultisig` underestimating tx size

### ISSUE THREAD

**Issue by matheusd** [decred/dcrwallet#1972]
```$ dcrctl --wallet --testnet sendtomultisig default 1 '[...]'```

Resulting tx:

https://testnet.dcrdata.org/tx/d45e8533d6f694adfe159d66674a2a0f756bb7411f704ae001de11a33b397cde

Estimated size was 217 bytes while actual size was 249 bytes (so the fee is lower than relay fee).

**Comment by JoeGruffins** [comment]
I would like to work on this.
