### ISSUE TITLE
Deadlock detected during tests

### ISSUE THREAD

**Issue by matheusd** [decred/dcrwallet#1975]
Seems to be a mutex logic race leading to a deadlock between rescanning and generating addresses.

Sample error:
https://zerobin.net/?d780b120a958ed23#IUTGr04rD+CBMKfNP7HDyxcEr93HbLd7L+ZITP14L1s=

**Comment by jrick** [comment]
This could be the same as #1984, and since this paste was deleted/expired, let's focus on the other issue.
