### ISSUE TITLE
A balancetype of "all" for getbalance does not work correctly.

### ISSUE THREAD

**Issue by davecgh** [decred/dcrwallet#2]
When issuing a `getbalance` RPC call with the `balancetype` set to `all`, the balance does not include unconfirmed coins in the balance as it should.

```bash
$ dcrctl --wallet getbalance "default" 0
1080.99029897
$ dcrctl --wallet getbalance "default" 0 all
1076.13881383
```

**Comment by cjepson** [comment]
Fixed in #104
