### ISSUE TITLE
purchaseticket blocked by invalid 0 amount output tx

### ISSUE THREAD

**Issue by raedah** [decred/dcrwallet#200]
Ive seen several reports of people trying to purchase stake tickets and getting this error.
"[ERR] WLLT: PurchaseTicket error returned: -22: TX rejected: tried to spend zero value output from input 50e256b7b0b4a631a0f25cb1984c850f6933b6440b5abec51d8392062ad05c06, idx 2"

What looks suspicious about the transaction, or this case
https://mainnet.decred.org/tx/50e256b7b0b4a631a0f25cb1984c850f6933b6440b5abec51d8392062ad05c06
is that it is trying to create utxos in the amount of 0 which as far as I know should not be valid.

**Comment by cjepson** [comment]
Zero-value UTXOs are value, just not spendable. This is a normal ticket. It has the mandatory change outputs zeroed. 

>[ERR] WLLT: PurchaseTicket error returned: -22: TX rejected: tried to spend zero value output from input 50e256b7b0b4a631a0f25cb1984c850f6933b6440b5abec51d8392062ad05c06, idx 2

That's from an older version of the wallet inappropriately adding zero value outputs to the UTXO set.

**Comment by ZeroASIC** [comment]
This looks like another case of issue 128 (https://github.com/decred/dcrwallet/issues/128).  I am also having this issue, but I rebuilt everything from dcrd and then imported my wallet from seed again. Now I don't get the -22 error, but I haven't purchased any tickets in the last 8 hours.  Hopefully that  resolved the issue for me.

**Comment by alexlyp** [comment]
This was fixed in #278
