### ISSUE TITLE
can't send decred

### ISSUE THREAD

**Issue by posa88** [decred/dcrwallet#2025]
I can't send my decred, with error: data.length exceed 256 bytes limit. Got: 256
I try to ask for help from ledger support but they seems can't help me.
Plz help..

**Comment by jrick** [comment]
This isn't related to dcrwallet and there is nothing the dcrwallet developers can do to diagnose this issue.

Ledger may not have been able or willing to help you, but I still believe they are the persons to ask.

**Comment by jrick** [comment]
closing for aforementioned reason.
