### ISSUE TITLE
mixing err halts further mixing

### ISSUE THREAD

**Issue by raedah** [decred/dcrwallet#2031]
The error seen is,
[ERR] TKBY: wallet.MixAccount:: wallet.MixOutput(xxx): read *messages.BR (dicemix.go:233): unexpected EOF
after which no further mixes occur despite blocks being connected.

The error does not always halt further mixing. In cases where mixing was halted, the error is observed as the last msg found from the mixer in the logs.

**Comment by raedah** [comment]
still seeing this on v1.6.3
[ERR] TKBY: wallet.MixAccount:: wallet.MixOutput(xxx:x): proxy dial tcp x.onion:5760: general failure                                                         
[ERR] TKBY: wallet.MixAccount:: wallet.MixOutput(xxx:x): xxx:x: read *messages.CM (dicemix.go:441): unexpected EOF

**Comment by vieirapedro** [comment]
i'm on v.1.6.3, got this error today 
not sure what cause it, but i moved DCR from default to unmixed using the option to "send to self" and tried to start mixer after, maybe this transaction wasn't confirmed when i started the mixer.

2022-01-17 15:57:15.456 [ERR] TKBY: wallet.MixAccount:: wallet.MixOutput . ..... .. : send *messages.PR (dicemix.go:198): EOF

can you guide how should i fix this?

Thanks
