### ISSUE TITLE
purchaseticket create send/receive transactions since 0.1.0

### ISSUE THREAD

**Issue by tpruvot** [decred/dcrwallet#204]
Even worst than before... here is the (unreadable) junk created after purchasing tickets

listtransactions

> [
>     {
>         "account": "",
>         "address": "Tcp6gfnibhCH53ngTcNQ9BZuWpmJ1MJMXo8",
>         "amount": -172.35112704,
>         "blockhash": "00000000037642822ae896f80edef0218782b18d1b10c006459a625b4df587cb",
>         "blocktime": 1461386466,
>         "category": "send",
>         "confirmations": 6,
>         "fee": -3.0e-6,
>         "time": 1461386359,
>         "timereceived": 1461386359,
>         "txid": "61c44d56ceb75d2dfb8246e99fd36a950957ef3ee6f461c47cda7edc6409f0b5",
>         "vout": 0,
>         "walletconflicts": []
>     },
>     {
>         "account": "imported",
>         "address": "Tcp6gfnibhCH53ngTcNQ9BZuWpmJ1MJMXo8",
>         "amount": 172.35112704,
>         "blockhash": "00000000037642822ae896f80edef0218782b18d1b10c006459a625b4df587cb",
>         "blocktime": 1461386466,
>         "category": "receive",
>         "confirmations": 6,
>         "time": 1461386359,
>         "timereceived": 1461386359,
>         "txid": "61c44d56ceb75d2dfb8246e99fd36a950957ef3ee6f461c47cda7edc6409f0b5",
>         "vout": 0,
>         "walletconflicts": []
>     },
>     {
>         "account": "",
>         "amount": 0,
>         "blockhash": "00000000037642822ae896f80edef0218782b18d1b10c006459a625b4df587cb",
>         "blocktime": 1461386466,
>         "category": "send",
>         "confirmations": 6,
>         "fee": -3.0e-6,
>         "time": 1461386359,
>         "timereceived": 1461386359,
>         "txid": "61c44d56ceb75d2dfb8246e99fd36a950957ef3ee6f461c47cda7edc6409f0b5",
>         "vout": 1,
>         "walletconflicts": []
>     },
>     {
>         "account": "",
>         "address": "TsR28UZRprhgQQhzWns2M6cAwchrNVvbYq2",
>         "amount": 0,
>         "blockhash": "00000000037642822ae896f80edef0218782b18d1b10c006459a625b4df587cb",
>         "blocktime": 1461386466,
>         "category": "send",
>         "confirmations": 6,
>         "fee": -3.0e-6,
>         "time": 1461386359,
>         "timereceived": 1461386359,
>         "txid": "61c44d56ceb75d2dfb8246e99fd36a950957ef3ee6f461c47cda7edc6409f0b5",
>         "vout": 2,
>         "walletconflicts": []
>     },
>     {
>         "account": "",
>         "address": "Tcp6gfnibhCH53ngTcNQ9BZuWpmJ1MJMXo8",
>         "amount": -172.35112704,
>         "blockhash": "00000000037642822ae896f80edef0218782b18d1b10c006459a625b4df587cb",
>         "blocktime": 1461386466,
>         "category": "send",
>         "confirmations": 6,
>         "fee": -3.0e-6,
>         "time": 1461386359,
>         "timereceived": 1461386359,
>         "txid": "e52507e9c1f6bb96ba5eaa32faea53ee32b8c7cbf399f67cc5deb58a1496c06a",
>         "vout": 0,
>         "walletconflicts": []
>     },
>     {
>         "account": "imported",
>         "address": "Tcp6gfnibhCH53ngTcNQ9BZuWpmJ1MJMXo8",
>         "amount": 172.35112704,
>         "blockhash": "00000000037642822ae896f80edef0218782b18d1b10c006459a625b4df587cb",
>         "blocktime": 1461386466,
>         "category": "receive",
>         "confirmations": 6,
>         "time": 1461386359,
>         "timereceived": 1461386359,
>         "txid": "e52507e9c1f6bb96ba5eaa32faea53ee32b8c7cbf399f67cc5deb58a1496c06a",
>         "vout": 0,
>         "walletconflicts": []
>     },
>     {
>         "account": "",
>         "amount": 0,
>         "blockhash": "00000000037642822ae896f80edef0218782b18d1b10c006459a625b4df587cb",
>         "blocktime": 1461386466,
>         "category": "send",
>         "confirmations": 6,
>         "fee": -3.0e-6,
>         "time": 1461386359,
>         "timereceived": 1461386359,
>         "txid": "e52507e9c1f6bb96ba5eaa32faea53ee32b8c7cbf399f67cc5deb58a1496c06a",
>         "vout": 1,
>         "walletconflicts": []
>     },
>     {
>         "account": "",
>         "address": "TsR28UZRprhgQQhzWns2M6cAwchrNVvbYq2",
>         "amount": 0,
>         "blockhash": "00000000037642822ae896f80edef0218782b18d1b10c006459a625b4df587cb",
>         "blocktime": 1461386466,
>         "category": "send",
>         "confirmations": 6,
>         "fee": -3.0e-6,
>         "time": 1461386359,
>         "timereceived": 1461386359,
>         "txid": "e52507e9c1f6bb96ba5eaa32faea53ee32b8c7cbf399f67cc5deb58a1496c06a",
>         "vout": 2,
>         "walletconflicts": []
>     },
>     {
>         "account": "",
>         "address": "Tcp6gfnibhCH53ngTcNQ9BZuWpmJ1MJMXo8",
>         "amount": -172.35112704,
>         "blockhash": "00000000037642822ae896f80edef0218782b18d1b10c006459a625b4df587cb",
>         "blocktime": 1461386466,
>         "category": "send",
>         "confirmations": 6,
>         "fee": -3.0e-6,
>         "time": 1461386359,
>         "timereceived": 1461386359,
>         "txid": "cb9db63c5683c4b8a194726dd874621cbd507414237fd83d0d44c52cc3848da0",
>         "vout": 0,
>         "walletconflicts": []
>     },
>     {
>         "account": "imported",
>         "address": "Tcp6gfnibhCH53ngTcNQ9BZuWpmJ1MJMXo8",
>         "amount": 172.35112704,
>         "blockhash": "00000000037642822ae896f80edef0218782b18d1b10c006459a625b4df587cb",
>         "blocktime": 1461386466,
>         "category": "receive",
>         "confirmations": 6,
>         "time": 1461386359,
>         "timereceived": 1461386359,
>         "txid": "cb9db63c5683c4b8a194726dd874621cbd507414237fd83d0d44c52cc3848da0",
>         "vout": 0,
>         "walletconflicts": []
>     },
>     {
>         "account": "",
>         "amount": 0,
>         "blockhash": "00000000037642822ae896f80edef0218782b18d1b10c006459a625b4df587cb",
>         "blocktime": 1461386466,
>         "category": "send",
>         "confirmations": 6,
>         "fee": -3.0e-6,
>         "time": 1461386359,
>         "timereceived": 1461386359,
>         "txid": "cb9db63c5683c4b8a194726dd874621cbd507414237fd83d0d44c52cc3848da0",
>         "vout": 1,
>         "walletconflicts": []
>     },
>     {
>         "account": "",
>         "address": "TsR28UZRprhgQQhzWns2M6cAwchrNVvbYq2",
>         "amount": 0,
>         "blockhash": "00000000037642822ae896f80edef0218782b18d1b10c006459a625b4df587cb",
>         "blocktime": 1461386466,
>         "category": "send",
>         "confirmations": 6,
>         "fee": -3.0e-6,
>         "time": 1461386359,
>         "timereceived": 1461386359,
>         "txid": "cb9db63c5683c4b8a194726dd874621cbd507414237fd83d0d44c52cc3848da0",
>         "vout": 2,
>         "walletconflicts": []
>     },

**Comment by cjepson** [comment]
This is intentional, for efficiency due to the design of the staking system. The automatic ticket purchasing is being overhauled and pushed to a separate program.

https://forum.decred.org/threads/dd-7-v0-1-0-04-18-16.3158/#post-18476

**Comment by jrick** [comment]
I don't see a bug here.  listtransactions is useless but that was always the case.
