### ISSUE TITLE
When a too high fee transaction is submitted, wallet receives the wrong error message

### ISSUE THREAD

**Issue by cjepson** [decred/dcrwallet#205]
Daemon: 
>14:02:08 2016-04-23 [ERR] RPCS: Failed to process transaction daf491d1c19fef8f32814590d509363912133390061dc0a2b20bb9d71f1550a0: transaction daf491d1c19fef8f32814590d509363912133390061dc0a2b20bb9d71f1550a0 has 300000 fee which is above the allowHighFee check threshold amount of 29600

Wallet:
> purchaseticket default 9999
> -4: sendrawtransaction failed: the client has been shutdown

**Comment by alexlyp** [comment]
Fixed in #224
