### ISSUE TITLE
getstakeinfo missed reports high

### ISSUE THREAD

**Issue by raedah** [decred/dcrwallet#206]
After coming back online, and running rebroadcastmissed, the "missed" amount shows twice as many as is true. May correspond with "Error encountered attempting to create revocation using ticket, -22: TX rejected: already have transaction."  After the revoke transactions complete, "missed" returns to the correct value. 

  "missed": 8,
  "revoked": 8

  "missed": 12,
  "revoked": 10

  "missed": 10,
  "revoked": 10

**Comment by cjepson** [comment]
Known bug, it reports artificially high when revocations are in the mempool.

**Comment by raedah** [comment]
Can also be noted that this bug will also skew "proportionmissed".
