### ISSUE TITLE
If a SStx is rejected at the wallet level, the initial consolidating transaction shouldn't be sent

### ISSUE THREAD

**Issue by jyap808** [decred/dcrwallet#207]
Referring to the changes in 0.1.0.

If a SStx is rejected at the wallet level, the initial consolidating transaction shouldn't be sent.

Log lines:

```
00:11:07 2016-04-25 [INF] TMGR: Inserting unconfirmed transaction 560a0945e6513d29137f8046f23cf84eceb28b8bed27bba1eb260330b51b0cd2
00:11:07 2016-04-25 [WRN] WLLT: Failed to send raw transaction: -22: TX rejected: transaction c5d5f64b01609376fbcdb4f33f6aa467ff3bd625f658d8686c86bf01e9fdc0a9 has 300000 fee which is above the allowHighFee check threshold amount of 29500
```

Log lines are from Testnet where multiple tickets were bought at once. In this case the ticket which consolidates fees is created and sent to the network.  The subsequent attempt at purchasing a SStx fails.

This behavior creates a redundant and annoying initial consolidating transaction since the original purpose of the user was to buy tickets.

**Comment by cjepson** [comment]
This would be better behavior, but it would take some retooling the current API to do.

**Comment by jrick** [comment]
This is impossible to do in SPV mode (transactions published over wire protocol can not be rescinded, without being double spent, and some nodes may accept the tx while others reject).  It could be done in the RPC sync mode but would require new dcrd RPCs and the network backend interface would not be possible to describe both backends.

**Comment by jyap808** [comment]
This isn’t such an issue now since there isn’t fee competition with the revised stake fee algo.
