### ISSUE TITLE
JSON-RPC validateaddress method should show HD derivation path

### ISSUE THREAD

**Issue by jrick** [decred/dcrwallet#2074]
This is particularly useful to determine the branch and child index of any address derived for an HD account.

**Comment by chappjc** [comment]
On that note, getbalance should really show the derivation path accounts, esp. considering legacy coin types being possible and accounts corresponding to imported xpubs looking like regular (non-"imported") accounts.

**Comment by JoeGruffins** [comment]
I would like to work on this if noone else is. Is this just for rpc methods, or also grpc? The grpc method already has some extra data, the account number, internal/external, and the index. Perhaps that's enough? We can assume the rest at this point in time. Should the rpc response have the same fields, or just one? Should they be the same data types, int, bool, int?
