### ISSUE TITLE
dcrusername/dcrpassword in sample-wallet.conf needs a 'd' added

### ISSUE THREAD

**Issue by toddfries** [decred/dcrwallet#21]
$HOME/.dcrwallet/dcrwallet.conf:88: unknown option: dcrusername

works fine as dcrdusername and dcrdpassword

**Comment by jcvernaleo** [comment]
@toddfries I can't seem to find the problem.  When I look at sample-wallet.conf it looks correct to me:
https://github.com/decred/dcrwallet/blob/master/sample-dcrwallet.conf#L86
https://github.com/decred/dcrwallet/blob/master/sample-dcrwallet.conf#L87

Could you take another look and see if the incorrect names are still there (in case I'm looking in the wrong place or something)?  Thanks.

**Comment by jcvernaleo** [comment]
Confirmed on irc with @toddfries that this is no longer an issue.  Closing.
