### ISSUE TITLE
listtransactions lists "phantom transactions" if funds have been sent within the wallet

### ISSUE THREAD

**Issue by kriptor** [decred/dcrwallet#216]
Encountered on v0.1.1 testnet.

If I send DCR to another address within the local wallet then after calling listtransactions it feels like there are some kind of "invisible transactions" there.

Actual history of my local wallet:
txid:063221486436dc1db17cf9a69f7c481f51693e8b33caee55dd2e787e25b9f2d4 ... **1st tx** (received 10 DCR from a guy on Decred forum)
txid:0dae564d9c907169ce7a8fc8ead2ee22d38cb67ae74d53ee66ecd2236da82467 ... **2nd tx** (sent 1 DCR to the address inside my local wallet)
txid:02b9a97435d18c275085867943cf02dba6656255de80c72072fffba7f10e4e8d ... **3rd tx** (sent 0.5 DCR to the address inside my local wallet)
txid:09be7567b3f5d7d1d1921e74def0257ef6cd72404037dad6a0f1920477398d34 ... **4th tx** (sent 0.75 DCR to online wallet)
txid:b70b52e3ff649cd01a4911d29117b50171bc1bf8baf798921bebac2eb9f37e26 ... **5th tx** (received 0.74 DCR from online wallet)

Problems when using listtransactions:
1. "Duplication" of transactions in the list. The only non-duplicated transaction is the **4th tx** (txid:09be7567b3f5d7d1d1921e74def0257ef6cd72404037dad6a0f1920477398d34). If the logic behind should be that one part (sender or receiver) must be external to the wallet to not see "duplicate" transactions then why is the **5th tx** (txid:b70b52e3ff649cd01a4911d29117b50171bc1bf8baf798921bebac2eb9f37e26) duplicated?
2. According to my experimentation with count/from params it looks like there are 3 "phantom transactions" at the end (chronologically) of my transaction list.

These are transactions returned using various count/from parameters. Transactions are in exact order as outputed by dcrctl (complete JSON was intentionally omitted for clarity reasons):

dcrctl --wallet listtransactions '*' 10000 0
txid:b70b52e3ff649cd01a4911d29117b50171bc1bf8baf798921bebac2eb9f37e26
txid:b70b52e3ff649cd01a4911d29117b50171bc1bf8baf798921bebac2eb9f37e26
txid:09be7567b3f5d7d1d1921e74def0257ef6cd72404037dad6a0f1920477398d34
txid:02b9a97435d18c275085867943cf02dba6656255de80c72072fffba7f10e4e8d
txid:02b9a97435d18c275085867943cf02dba6656255de80c72072fffba7f10e4e8d
txid:0dae564d9c907169ce7a8fc8ead2ee22d38cb67ae74d53ee66ecd2236da82467
txid:0dae564d9c907169ce7a8fc8ead2ee22d38cb67ae74d53ee66ecd2236da82467
txid:063221486436dc1db17cf9a69f7c481f51693e8b33caee55dd2e787e25b9f2d4
txid:063221486436dc1db17cf9a69f7c481f51693e8b33caee55dd2e787e25b9f2d4

dcrctl --wallet listtransactions '*' 1 0
returns empty list

dcrctl --wallet listtransactions '*' 2 0
returns empty list

dcrctl --wallet listtransactions '*' 3 0
returns empty list

dcrctl --wallet listtransactions '*' 4 0
txid:b70b52e3ff649cd01a4911d29117b50171bc1bf8baf798921bebac2eb9f37e26
txid:b70b52e3ff649cd01a4911d29117b50171bc1bf8baf798921bebac2eb9f37e26

dcrctl --wallet listtransactions '*' 5 0
txid:b70b52e3ff649cd01a4911d29117b50171bc1bf8baf798921bebac2eb9f37e26
txid:b70b52e3ff649cd01a4911d29117b50171bc1bf8baf798921bebac2eb9f37e26
txid:09be7567b3f5d7d1d1921e74def0257ef6cd72404037dad6a0f1920477398d34

dcrctl --wallet listtransactions '*' 6 0
txid:b70b52e3ff649cd01a4911d29117b50171bc1bf8baf798921bebac2eb9f37e26
txid:b70b52e3ff649cd01a4911d29117b50171bc1bf8baf798921bebac2eb9f37e26
txid:09be7567b3f5d7d1d1921e74def0257ef6cd72404037dad6a0f1920477398d34
txid:02b9a97435d18c275085867943cf02dba6656255de80c72072fffba7f10e4e8d
txid:02b9a97435d18c275085867943cf02dba6656255de80c72072fffba7f10e4e8d

dcrctl --wallet listtransactions '*' 7 0
txid:b70b52e3ff649cd01a4911d29117b50171bc1bf8baf798921bebac2eb9f37e26
txid:b70b52e3ff649cd01a4911d29117b50171bc1bf8baf798921bebac2eb9f37e26
txid:09be7567b3f5d7d1d1921e74def0257ef6cd72404037dad6a0f1920477398d34
txid:02b9a97435d18c275085867943cf02dba6656255de80c72072fffba7f10e4e8d
txid:02b9a97435d18c275085867943cf02dba6656255de80c72072fffba7f10e4e8d
txid:0dae564d9c907169ce7a8fc8ead2ee22d38cb67ae74d53ee66ecd2236da82467
txid:0dae564d9c907169ce7a8fc8ead2ee22d38cb67ae74d53ee66ecd2236da82467

dcrctl --wallet listtransactions '*' 8 0
txid:b70b52e3ff649cd01a4911d29117b50171bc1bf8baf798921bebac2eb9f37e26
txid:b70b52e3ff649cd01a4911d29117b50171bc1bf8baf798921bebac2eb9f37e26
txid:09be7567b3f5d7d1d1921e74def0257ef6cd72404037dad6a0f1920477398d34
txid:02b9a97435d18c275085867943cf02dba6656255de80c72072fffba7f10e4e8d
txid:02b9a97435d18c275085867943cf02dba6656255de80c72072fffba7f10e4e8d
txid:0dae564d9c907169ce7a8fc8ead2ee22d38cb67ae74d53ee66ecd2236da82467
txid:0dae564d9c907169ce7a8fc8ead2ee22d38cb67ae74d53ee66ecd2236da82467
txid:063221486436dc1db17cf9a69f7c481f51693e8b33caee55dd2e787e25b9f2d4
txid:063221486436dc1db17cf9a69f7c481f51693e8b33caee55dd2e787e25b9f2d4

dcrctl --wallet listtransactions '*' 1 3
txid:b70b52e3ff649cd01a4911d29117b50171bc1bf8baf798921bebac2eb9f37e26
txid:b70b52e3ff649cd01a4911d29117b50171bc1bf8baf798921bebac2eb9f37e26

dcrctl --wallet listtransactions '*' 1 4
txid:09be7567b3f5d7d1d1921e74def0257ef6cd72404037dad6a0f1920477398d34

dcrctl --wallet listtransactions '*' 1 5
txid:02b9a97435d18c275085867943cf02dba6656255de80c72072fffba7f10e4e8d
txid:02b9a97435d18c275085867943cf02dba6656255de80c72072fffba7f10e4e8d

dcrctl --wallet listtransactions '*' 1 6
txid:0dae564d9c907169ce7a8fc8ead2ee22d38cb67ae74d53ee66ecd2236da82467
txid:0dae564d9c907169ce7a8fc8ead2ee22d38cb67ae74d53ee66ecd2236da82467

dcrctl --wallet listtransactions '*' 1 7
txid:063221486436dc1db17cf9a69f7c481f51693e8b33caee55dd2e787e25b9f2d4
txid:063221486436dc1db17cf9a69f7c481f51693e8b33caee55dd2e787e25b9f2d4

All but one (the **5th tx**) "duplication" can actually be understood as transaction within the wallet has dual nature - one is the 'send' and the other the 'receive' part.

**Comment by alexlyp** [comment]
I've just pushed a PR that should fix this.

As you may have noticed there are "duplicate" tx, but they are just more than 1 vout for that txid.  With that in mind, now when you listtransactions "*" n 0, you would get all vins/vouts of the most recent n tx.  This also includes transactions in the mempool (and would be listed first)
