### ISSUE TITLE
panic on CFilterV2

### ISSUE THREAD

**Issue by raedah** [decred/dcrwallet#2167]
2022-06-16 03:46:46.165 [WRN] DLWL: Failed to handle headers announced by 89.212.19.49:9108: spv.handleBlockAnnouncements(89.212.19.49:9108): I/O error:: remotepeer(89.212.19.49:9108).CFilterV2(000000000000000006507c1af936c17d43e7e6dfa79c5b750ed9847f52a1c424): peer appears stalled
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x821b59]

goroutine 300862 [running]:
decred.org/dcrwallet/v2/wallet/udb.(*Store).ExtendMainChain(0xed9847f52a1c424?, {0x1dfd358?, 0xc0052e0400}, 0xc00277c270, 0x0)
        /home/user/go/pkg/mod/decred.org/dcrwallet/v2@v2.0.2-0.20220505152146-ece5da349895/wallet/udb/txmined.go:273 +0x679
decred.org/dcrwallet/v2/wallet.(*Wallet).extendMainChain(0xc002c705a0, {0x1df5278, 0xc0036d7c80}, {0x18160c4, 0x12}, {0x1df81c8, 0xc00052e358}, 0x19?, 0x0?, {0x0, ...})
        /home/user/go/pkg/mod/decred.org/dcrwallet/v2@v2.0.2-0.20220505152146-ece5da349895/wallet/chainntfns.go:37 +0x113
decred.org/dcrwallet/v2/wallet.(*Wallet).ChainSwitch.func1({0x1df81c8, 0xc00052e358})
        /home/user/go/pkg/mod/decred.org/dcrwallet/v2@v2.0.2-0.20220505152146-ece5da349895/wallet/chainntfns.go:160 +0x890
decred.org/dcrwallet/v2/wallet/walletdb.Update({0x1df5278, 0xc0036d7c80}, {0x1df5588, 0xc00289e240}, 0xc0005cfbf0)
        /home/user/go/pkg/mod/decred.org/dcrwallet/v2@v2.0.2-0.20220505152146-ece5da349895/wallet/walletdb/interface.go:249 +0x195
decred.org/dcrwallet/v2/wallet.(*Wallet).ChainSwitch(0xc002c705a0, {0x1df5278, 0xc0036d7c80}, 0xc0025822e8, {0xc00052e148, 0x1, 0x1}, 0x0)
        /home/user/go/pkg/mod/decred.org/dcrwallet/v2@v2.0.2-0.20220505152146-ece5da349895/wallet/chainntfns.go:104 +0x2da
github.com/planetdecred/dcrlibwallet/spv.(*Syncer).getHeaders(0xc0025b4500, {0x1df5278, 0xc0036d6080}, 0xc00416ca80)
        /home/user/go/pkg/mod/github.com/planetdecred/dcrlibwallet@v1.7.0/spv/sync.go:1384 +0xaaa
github.com/planetdecred/dcrlibwallet/spv.(*Syncer).startupSync(0xc0025b4500, {0x1df5278, 0xc0036d6080}, 0xc00416ca80)
        /home/user/go/pkg/mod/github.com/planetdecred/dcrlibwallet@v1.7.0/spv/sync.go:1454 +0x170
github.com/planetdecred/dcrlibwallet/spv.(*Syncer).connectToCandidates.func1.2()
        /home/user/go/pkg/mod/github.com/planetdecred/dcrlibwallet@v1.7.0/spv/sync.go:579 +0x37
created by github.com/planetdecred/dcrlibwallet/spv.(*Syncer).connectToCandidates.func1
        /home/user/go/pkg/mod/github.com/planetdecred/dcrlibwallet@v1.7.0/spv/sync.go:578 +0x578

**Comment by jrick** [comment]
This isn't dcrwallet; we don't have a logger subsystem called DLWL.  Have you determined this is not an issue with dcrlibwallet?
