### ISSUE TITLE
Web Wallet defaults zero balance

### ISSUE THREAD

**Issue by Bitnee** [decred/dcrwallet#2185]
Referencing Poolin earnings, web Wallet earnings void to zero.
Ridiculous.
Consider this a main staggery as Bytom allows for such withdraw via Antpool.
Absolute disgrace.
China in for the win as per usual.
Catch me with the new Decred wallet address.
Recover address Dso8FyaBmvEBYuaYLwFvV6kzdz8qHSKGBYD

**Comment by jrick** [comment]
doesn't sound like this is a dcrwallet issue. closing.
