### ISSUE TITLE
-32603: insufficient funds: transaction requires 2 Coin input but only 25 Coin spendable

### ISSUE THREAD

**Issue by alexlyp** [decred/dcrwallet#22]
User has spendable/mature coins, but unable to sendtoaddress "addr" 2.

Though they were able to successfully send with sendfrom Main "addr" 2.

Appears that an alternative account is being created and is not usable under current sendtoaddress conditions.

**Comment by jrick** [comment]
`// sendtoaddress always spends from the default account, this matches bitcoind`

However, i took another look at bitcoin core and this doesn't seem to be the case with the current code.  It appears to spend coins from any account.

I don't want to change this behavior in btcwallet (comingling of funds, etc.) but feel free to change this for dcrwallet if you want.  sendfrom will work with any single account, but it won't be able to spend using every account (like how `*` can be used in some bitcoind requests).

**Comment by richiela** [comment]
sendfrom shouldn't be required... if we really must send from one account, this causes unnecessary tx's because we'll have to move funds from user accounts to the default account etc.  Again, please make behavior match bitcoin.

**Comment by ocminer** [comment]
I can confirm this as well, its very annoying

**Comment by codyf86** [comment]
Just posted a new issue but purchase ticket is doing the same thing :(

**Comment by tpruvot** [comment]
**consolidate** !!! (yes im a doctor who fan ^^)

**Comment by cjepson** [comment]
Accounts fixed in #104. Transaction fees may still occasionally be an issue, but this should be a bit better now.

**Comment by alexlyp** [comment]
This appears to have been fixed with updates to tx creation and txauthor package from btcwallet.

And with new splitTx in ticket purchases, there is a streamlined output usage
