### ISSUE TITLE
getinfo - balance and getbalance return wrong values after a send*

### ISSUE THREAD

**Issue by richiela** [decred/dcrwallet#23]
Balance is wrong after a successful send.  It fixes it self after blocks confirm.

**Comment by jrick** [comment]
It's not wrong.  We treat your own change outputs no differently than any other change output.

**Comment by richiela** [comment]
How is it not wrong?  If i have 25 coins.. i send 2 coins... i do a getinfo.. .my balance tells me i have 0 balance.  It should tell me i have 23 balance.  Are you suggesting that I have to wait X number of blocks before I can check my balance to get an accurate read?

**Comment by jrick** [comment]
If you have 1 UTXO with 25 output value, and you spend it sending 2 coins elsewhere and 23 coins back to yourself as a change output (let's ignore fees for simplicity), those 23 coins are **not confirmed**.  They can be spent again with minconf=1 once they are mined in a block.

Use `getbalance accountname 0` to show your unconfirmed balance, or `sendfrom accountname addr amount 0` to spend unconfirmed coins.

**Comment by richiela** [comment]
this deviates from bitcoin behavior.  btc will always report change back to you from you as part of your balance.  is there a way to get a 0 conf balance from the wallet?

**Comment by chappjc** [comment]
@richiela I believe you are looking for <code>getbalance accountname minconf balancetype</code>.  The treatment of balancetype is [here](https://github.com/decred/dcrwallet/blob/master/rpcserver.go#L1724).  The [help description for `getbalance`](https://github.com/decred/dcrwallet/blob/master/internal/rpchelp/helpdescs_en_US.go#L62) is

`"getbalance-balancetype": "The type of balance to return, 'spendable', 'locked', 'all', or 'fullscan'"`

I think this is what you are after. For example `getbalance default 1 all`.

**Comment by richiela** [comment]
That doesn't work either... get balance default 0 all returns the same thing as getinfo.

**Comment by codyf86** [comment]
This RPC command is also ignoring the specified account and returning the value for the total wallet, just like purchasetickets and the other RPC commands listed in issues.

--wallet getbalance default 256 spendable
13.3819809

There is 13.xx dcr spendable in the total wallet, but 0 spendable in default account atm and it still returns the total spendable.

**Comment by richiela** [comment]
Is there any update on this? we need a way to send a payment, and then check the the balance to ensure it is accurate.

**Comment by cjepson** [comment]
Use 'get balance default 0 spendable' NOT 'get balance default 0 all'. There's a bug in the 'all' flag that needs to be fixed. See https://github.com/decred/dcrwallet/issues/2

**Comment by cjepson** [comment]
getbalance should be fixed in #104.
