### ISSUE TITLE
stakepooluserinfo returning "live" for tickets that are immature. 

### ISSUE THREAD

**Issue by mverrilli** [decred/dcrwallet#237]
Example on testnet (won't last forever, but as of this post it is immature): 

https://testnet.decred.org/tx/34773fa69f5c62b3d3d531cb07a6a84f5f1832b6d8431a4cbe7b4a1673d2b325

From stakepooluserinfo: 
```
    {
      "status": "live",
      "ticket": "34773fa69f5c62b3d3d531cb07a6a84f5f1832b6d8431a4cbe7b4a1673d2b325",
      "ticketheight": 71599,
      "spentby": "0000000000000000000000000000000000000000000000000000000000000000",
      "spentbyheight": 0
    },
```

**Comment by cjepson** [comment]
That field is "liveorimmature".. IIRC the string "live" was just used to be smaller or indicate that it will eventually become live
