### ISSUE TITLE
gettransaction does not populate the account field properly

### ISSUE THREAD

**Issue by richiela** [decred/dcrwallet#24]
dcrcoin gettransaction 60fbd3092222d26c887188358436d5158c3d7d7ab695782d35dadc66a0f72f71
{
  "amount": 0.95,
  "confirmations": 24,
  "blockhash": "0000000000005843ea1b5122d75d0f6415c9b37ebb9258dd5b5ba7b67f856315",
  "blockindex": 0,
  "blocktime": 1454981933,
  "txid": "60fbd3092222d26c887188358436d5158c3d7d7ab695782d35dadc66a0f72f71",
  "walletconflicts": [],
  "time": 1454981888,
  "timereceived": 1454981888,
  "details": [
    {
      "account": "",
      "address": "DsYrr6HAiyceXwvfzhYk1WCHxLctokGjEUM",
      "amount": 0.95,
      "category": "receive",
      "vout": 0
    }
  ],
  "hex": "01000000010855c1022575bc9608b929d79d599a8dcecd3b71a3374ebb52857561af42fb1d0100000000ffffffff02c095a9050000000000001976a914569bac4b9c765c5aa2ace4d56f75e38a3c61896a88ac222305010000000000001976a914786d11b73005815d283c6d1e6ce0e28b8586eb1788ac000000000000000001ffffffffffffffff00000000ffffffff6b4830450221009c53bcb55bf79aac1744176e4f9cd1364e87f551c1e5d11edf14cb1aba88e0f402201e64684a2c7ee343b7e737069777c2350031965b6da001648b2b4f7ac168029d012103b0c45f1190b0b6309b134e57b5ca6a10dd0bf76e66e4f72418c522e2fdc2266c"
}

the same transaction using listtransactions
  {
    "account": "3ed3b1bd-c1aa-4a49-ac3e-d60bb7a1ef01",
    "address": "DsYrr6HAiyceXwvfzhYk1WCHxLctokGjEUM",
    "amount": 0.95,
    "blockhash": "0000000000005843ea1b5122d75d0f6415c9b37ebb9258dd5b5ba7b67f856315",
    "blocktime": 1454981933,
    "category": "receive",
    "confirmations": 25,
    "time": 1454981888,
    "timereceived": 1454981888,
    "txid": "60fbd3092222d26c887188358436d5158c3d7d7ab695782d35dadc66a0f72f71",
    "vout": 0,
    "walletconflicts": []
  },

**Comment by jrick** [comment]
This is a bug.  I'll fix it in btcwallet first.

**Comment by jcvernaleo** [comment]
This was fixed in a0e5863 (which was a cherry-picked from @jrick commit for btcsuite/btcwallet#360)
