### ISSUE TITLE
change '[ERR] WLLT: Notifying unmined tx notification' to debug

### ISSUE THREAD

**Issue by raedah** [decred/dcrwallet#242]
via irc
woot: This is using master. Anything I should be scared of? :p
jrick: known issue and it's mostly harmless. there's a broken assumption somewhere but i have yet to track it down. it just logs the error but continues as if nothing is wrong
jrick: also only matters right now if you're using the grpc api
jrick: we could make it a debug instead

**Comment by chappjc** [comment]
But if you are using gRPC, wouldn't you like an error?

**Comment by raedah** [comment]
Could also be resolved by fixing the broken assumption that causes the error. Need more info on what that is.

**Comment by cjepson** [comment]
fixed in #246
