### ISSUE TITLE
not enough arguments in call to txscript.NewEngine

### ISSUE THREAD

**Issue by chappjc** [decred/dcrwallet#249]
```
# github.com/decred/dcrwallet/wstakemgr
go/src/github.com/decred/dcrwallet/wstakemgr/stake.go:749: not enough arguments in call to txscript.NewEngine
```

I think https://github.com/decred/dcrd/commit/e310d1dac5bbe57d8c3bf05ac5b57402d81f3ac1 broke this.

**UPDATE**: Note that this was not with glide.  There is no issue when using glide.

**Comment by jrick** [comment]
Yes, glide is not just recommended.  It is required to ensure dependencies (even our own) don't change without us being able to fix their usage.

**Comment by chappjc** [comment]
Realized it after I posted.  Should I closed or is the something that needs to be addressed anyway?

**Comment by jrick** [comment]
Nah i just forgot to close it when i posted earlier.
