### ISSUE TITLE
listscripts should work for a watching-only wallet

### ISSUE THREAD

**Issue by chappjc** [decred/dcrwallet#255]
With a watching-only wallet, it is not permitted to `listscripts`.  However, you may `importscript`.

```
$ dcrctl.exe -C dcrctl-watcher.conf listscripts
-4: address manager is watching-only
```

`listscripts` should be able to list scripts from the unencrypted stores.

**Comment by vctt94** [comment]
I believe this is not an issue anymore

**Comment by jrick** [comment]
listscripts is gone.
