### ISSUE TITLE
wallet looks broken after recreating from seed

### ISSUE THREAD

**Issue by stintel** [decred/dcrwallet#270]
After recreating my wallet from seed, it looked completely broken. I am starting my wallet as a systemd user service, and what appears in the logs is only this:
```
11:03:49 2016-06-14 [INF] DCRW: Version 0.1.5-beta
11:03:49 2016-06-14 [INF] RPCS: Listening on 127.0.0.1:29110
11:03:49 2016-06-14 [INF] RPCS: Listening on [::1]:29110
11:03:49 2016-06-14 [INF] DCRW: Attempting RPC client connection to localhost:9109
11:03:49 2016-06-14 [INF] CHNS: Established connection to RPC server localhost:9109
11:03:50 2016-06-14 [INF] WLLT: Opened wallet
```
Commands to that wallet fail:
```-1: Chain RPC is inactive```
And the process is using 30-60% CPU.

The problem is that after recreating the wallet from seed, dcrwallet asks the passphrase when you start it the first time. This is new behavior I did not see before. Starting dcrwallet manually instead of running it as a systemd user service showed this:
```
*** ATTENTION ***
Since this is your first time running we need to sync accounts. Please enter
the private wallet passphrase. This will complete syncing of the wallet
accounts and then leave your wallet unlocked. You may relock wallet after by
calling 'walletlock' through the RPC.
*****************
Enter private passphrase:
```
After entering it once, I was able to start the wallet as a systemd user service again.

It would be nice if:
* that ATTENTION message would be written to the log file
* dcrctl -wallet walletpassphrase XXXX could also be used to enter the passphrase for the first time

**Comment by alexlyp** [comment]
So due to the way we are currently syncing accounts/addresses in wallet this is a needed step.

Obviously not ideal, but it will require quite a bit of surgery to fix.  We have been kicking around various solutions to not require this step.  

We decided against putting the ATTENTION in the logger so it would stand out to users on the CLI more than a log message.
