### ISSUE TITLE
Cannot create wallet from seed

### ISSUE THREAD

**Issue by kargakis** [decred/dcrwallet#279]
Tried with 0.1.5 and 0.1.3 with no luck. I had to go back to 0.0.1 to make it work. Not sure when exactly did this regress.

Also now that I recreated with a 0.0.1 wallet, when starting 0.1.5 I get this error message and the process exits:
```
[ERR] DCRW: the specified stake store/manager does not exist in db
```
What am I supposed to do now?

**Comment by kargakis** [comment]
I cannot even start with 0.0.1
```
[ERR] DCRW: recorded version 2 is newer that latest understood version 1
```
Error messages are too cryptic

**Comment by chappjc** [comment]
I would backup and delete all wallet.db files, and try again with 0.1.5.  Also  set debuglevel=debug to get to the bottom of it.

**Comment by kargakis** [comment]
Why do I need to backup wallet.db files? Note that leveldb got corrupted somehow, I couldn't start dcrd, and I opted in recreating everything from scratch.

**Comment by alexlyp** [comment]
What is happening when you create from seed on 0.1.5 or 0.1.3?

**Comment by kargakis** [comment]
The wallet just hangs forever without returning any message.

**Comment by chappjc** [comment]
When creating from seed, a new wallet.db needs to be created.  Delete any that might be there already.

**Comment by kargakis** [comment]
@chappjc I will try once again when I get back home but I am sure I was trying to create from seed without having any existing wallet.db. I remember creating .dcrwallet manually and adding my config. I thought about having all the blockchain synced and I tried once I had it but with the same result.:/

**Comment by alexlyp** [comment]
dcrwallet --create 
So you enter in your seed and press enter, and it does nothing?

Maybe try hitting enter again.  We added an extra return there to help with copy/pasting seed in.

You should see Creating the wallet...

**Comment by kargakis** [comment]
The second enter did the trick. Thanks for all the help guys! Sincerely, if you can keep something out of this is that user experience needs some work here.
