### ISSUE TITLE
Seed prompt for --create can't handle extra whitespace

### ISSUE THREAD

**Issue by jrick** [decred/dcrwallet#29]
See http://play.golang.org/p/nNtX7BaIsC for why.

**Comment by cjepson** [comment]
I don't know if that's actually a bug. dcrctl is the same way. I can see if making the program more difficult to use for new users. Maybe we should prune extra spaces before splitting.

**Comment by davecgh** [comment]
I would suggest pruning all leading, trailing white space and merging all interior white space to a single space.
