### ISSUE TITLE
Minimum wallet balance for stake mining doesn't seem to work...

### ISSUE THREAD

**Issue by mverrilli** [decred/dcrwallet#30]
...or doesn't work the way I expected. 

I see this in my log: 

07:16:20 2016-02-10 [INF] WLLT: Stake mining is enabled. Votebits: 1, minimum wallet balance 50

However, all of my dtc were spent on a ticket and it seemed to ignore the minimum wallet balance. 

In case it helps, this is the transaction: 
https://mainnet.decred.org/tx/7e8487b7b81f37b8b5cfb7042be539872962815e443233eaf08ad797ad5d71ae

**Comment by Erovyr101** [comment]
This transaction is correct and your minimum balance is respected.  This transactions shows 
INPUT:
DsgGcYPsFnSSW8PbFaSy2ky1WUuCgZWo6bV  your address which contain 282.63795424 DCR

OUTPUT
DsXD7BcMWWrotMZUMTxEVMmfmf62RXdxxK4  your ticket at 2 DCR value
DskNSwHN4x82XqtFZZAeNjHfQVzrL2QHihC   your change  of 280.58795424 DCR that is being returned to you

However,  You will not see the change appear in your wallet until the transaction has been confirmed in a block. (92 confirmation now so you got your change back a while ago)

Also keep in mind that if you enable auto mining, when the change comes in, your wallet can immediately purchase a new ticket with the 280..... DCR address available and once again your balance will show 0 until  the now 278 DCR change is returned to you.

If you your funds are split over multiple addresses in your wallet, only one of them will be used for purchases and only that portion will be subject to a block validation before the change is returned.

**Comment by mverrilli** [comment]
Got it, sorry... I did not understand how that works... but I think I get it now. Thanks so much.
