### ISSUE TITLE
gRPC server reports incorrect balances when funds are locked by tickets

### ISSUE THREAD

**Issue by jrick** [decred/dcrwallet#314]
These should be included in the total balance, and separate locked_balance fields added to the messages.  This needs to be addressed for both the WalletService.Balance and WalletService.Accounts RPCs, since both report the total balance incorrectly.

**Comment by raedah** [comment]
by the title, looks like this was resolved by https://github.com/decred/dcrwallet/pull/843

**Comment by jrick** [comment]
Should be.  New issues should be opened for any remaining balance reporting problems.
