### ISSUE TITLE
Account and address discovery should not occur when a wallet is created with a new seed (still required for restored seeds)

### ISSUE THREAD

**Issue by jrick** [decred/dcrwallet#320]
This will improve the UX when creating a brand new wallet because there will be less waiting.  Addresses will be able to be immediately generated since wallet won't need to search the entire blockchain for previous address usage.

**Comment by vctt94** [comment]
Can  I work on this issue?

**Comment by jrick** [comment]
certainly

**Comment by jrick** [comment]
A separate file seems reasonable, but it makes more sense to indicate when a new random wallet was created instead of an imported seed.  In this case, the initial sync can be skipped and the file deleted for future wallet starts.

One other possible issue we need to consider is that between the wallet creation and the first startup of this wallet, the seed could have already been imported to another wallet and used, so it is not always certain that no address/account discovery will be needed for every user, but in the majority of cases it won't be a problem.

**Comment by jrick** [comment]
Copying some of my thoughts from 1105:

* This should be tracked by the DB.

* It should track the wallet's birthday for newly created wallets.  This has the additional benefit of allowing us to avoid rescans and address/account discovery for blocks between the genesis block and the birthday date.
