### ISSUE TITLE
add address argument to consolidate 

### ISSUE THREAD

**Issue by chappjc** [decred/dcrwallet#321]
The `consolidate` function would benefit from an optional address argument to be used as the change address.  This could avoid a subsequent send in many cases.

Something like the following:

```
consolidate numInputs ("account") ("address")

Consolidate numInputs many UTXOs into a single output in the wallet or an optional address.

Arguments:
1. numInputs (numeric, required)  Number of UTXOs to consolidate as inputs
2. account (string, optional)     Account to pick unspent outputs from, and for tx out when
   no address specified
3. address (string, optional)     Address to pay.  Default is obtained via getnewaddress from
   the account's address pool

Result:
"value" (string) Transaction hash for the consolidation transaction
```

This would seem to require modifying the inputs to `compressWallet` and adding logic around `addrFunc()`.  https://github.com/decred/dcrwallet/blob/master/wallet/createtx.go#L734

**Comment by chappjc** [comment]
https://github.com/decred/dcrwallet/pull/323
https://github.com/decred/dcrd/pull/317

**Comment by alexlyp** [comment]
PR merged, issue resolved
