### ISSUE TITLE
rescan broken on reorgs

### ISSUE THREAD

**Issue by dajohi** [decred/dcrwallet#335]
Starting dcrwallet

16:25:24 2016-09-01 [INF] WLLT: Started rescan from block 0000000003bf2d6c8088784005029c7c6a8a8df9e4067aa7bed05f9103d8c3ec (height 153407) for 367334 addresses
16:25:30 2016-09-01 [ERR] WLLT: Rescan for 367334 addresses failed: -5: Error getting block: block 0000000003bf2d6c8088784005029c7c6a8a8df9e4067aa7bed05f9103d8c3ec is not in the main chain
16:25:30 2016-09-01 [WRN] WLLT: Unable to synchronize wallet to chain: -5: Error getting block: block 0000000003bf2d6c8088784005029c7c6a8a8df9e4067aa7bed05f9103d8c3ec is not in the main chain
16:25:30 2016-09-01 [INF] WLLT: The client has successfully connected to dcrd and is now handling websocket notifications

and it sits...

**Comment by jrick** [comment]
Please reopen if you see this again.  0.6 introduced entirely new rescan code.

**Comment by chappjc** [comment]
I had a testnet wallet that tried to rollback thousands of blocks and eventual gave up.  Had to recreate from seed.  The errors were different to what @dajohi is reporting here however.  I can dig up the old wallet.db and possible the logs if it's of interest.

**Comment by jrick** [comment]
That sounds like a different issue.  Could you open a new one for that?
