### ISSUE TITLE
Change 'expiry' and 'comment' parameter order on 'purchaseticket' command

### ISSUE THREAD

**Issue by JasonSome** [decred/dcrwallet#337]
Currently, because of the order in the command "purchaseticket",

`purchaseticket "fromaccount" spendlimit (minconf=1 "ticketaddress" numtickets "pooladdress" poolfees expiry "comment")`

one cannot specify expiry without listing pooladdress and that is a huge problem, since it is required that poolfees is non-zero...

I propose that the order of the parameters change, so that we have:

`purchaseticket "fromaccount" spendlimit (minconf=1 expiry "comment" "ticketaddress" numtickets "pooladdress" poolfees)`

and a comment can be made without a ticketaddress/pooladdress having to be present. Generally, the idea would be that ticketaddress and pooladdress are left last.

**Comment by jrick** [comment]
Changing this order is a breaking change.  I would prefer to see options in a JSON object (so that order does not matter) but this would also be better introduced as a new RPC instead of changing purchaseticket.
