### ISSUE TITLE
wtxmgr upgrade path from version 1 to 2 was erroneously removed

### ISSUE THREAD

**Issue by jrick** [decred/dcrwallet#357]

**Comment by jrick** [comment]
For those hitting this issue after upgrading to the 0.5.0 release, try using the previous 0.4.0 release to perform the upgrade, and then switch back to 0.5.0.

**Comment by chappjc** [comment]
What version was the first using the upgraded wtxmgr?

**Comment by jrick** [comment]
After further investigation, this is not due to removing the upgrade path, but rather that there was never an upgrade path in the first place.  Version 2 was backwards compatible with version 2, but there was never a version bump (there must be, or older software can corrupt the db in the newer format than it knows how to deal with).

@chappjc downgrading the wallet to upgrade the db won't work after all.  We will commit a fix and reroll a new release with the patch.
