### ISSUE TITLE
glide update didn't.

### ISSUE THREAD

**Issue by jrick** [decred/dcrwallet#363]
For some reason in #361 glide downgraded dcrd from 4c838e82b5110af8b69b34a81e2cbc224e5888fa to 717040c9453370196efb0a3706c83f17456cc374.  I verified after a `glide cc` (clear cache) that `update` grabbed the latest master as it should have done.

We'll leave it for now and will update dcrd to the actual latest code after a few more required dcrd PRs land.

**Comment by chappjc** [comment]
I've also noticed glide up not advancing master, but I'm not experienced with glide so I assumed pebkac.  I had to delete glide.lock in dcrwallet to get it to change the sha for dcrrpcclient.
