### ISSUE TITLE
balance out of sync with redundant pos wallets

### ISSUE THREAD

**Issue by raedah** [decred/dcrwallet#367]
Dcrwallet does not notice ticket purchase transactions it owns when the ticket buying is happening on a seperate remote instance, but they appear after a rescan.
This bug is a show stopper. Makes redundant solo PoS mining unreliable.
Verified since dcrwallet 0.5.0

Full dcrwallet config directory is synced from box1 to box2.
Box1 is running enablevoting and enableticketbuyer.
Box2 is running enablevoting.

- Number of live tickets on Box2 to will continue to fall while out of sync.
- Total balance on Box2 (getbalance * 0 all) drops with every ticket purchase.

- Recreating the wallet from seed, or doing a rescan brings everything back in sync, but it will quickly go out of sync when new tickets are purchased.
- After rescanning, Box2 will register a small amount of new tickets in the getstakeinfo immature count before it goes out of sync untill the next rescan.

- wallet index counts are same on both boxes.
- **amount in "[TRC] TMGR: ... many utxos found in database" are different on Box1 and Box2**

- Box2 marks addresses used only for redeemed tickets it knows about.
```
[DBG] TMGR: Marking transaction ... output 2 (x.x Coin) spendable
[DBG] WLLT: Marked address ... used
```

- Box1 marks addresses used for unconfirmed transactions related to purchases.
```
[INF] TMGR: Inserting unconfirmed transaction ...
[DBG] WLLT: Marked address ... used
```
- Box1 marks addresses used for sstx transactions.
```
[INF] TMGR: Inserting unconfirmed transaction ...
[DBG] WLLT: Marked address ... used
[INF] WLLT: Successfully sent SStx purchase transaction ...
```
- Box1 marks addresses used for mined transactions.
```
[DBG] TMGR: Marking unconfirmed transaction ... mined in block ...
[DBG] WLLT: Marked address ... used
```
- Box1 marks addresses used for sstx transactions again?
```
[INF] TKBY: Purchased ticket ... at stake difficulty ... (... fees per KB used)
[DBG] WLLT: Marked address ... used
[TRC] STKM: Attempted to insert SStx ... into the stake store, but the SStx already exists.
```

- Box2 SOMETIMES shows "[INF] TMGR: Inserting unconfirmed transaction ..." for new purchases
- Box2 SOMETIMES shows "[DBG] TMGR: Marking unconfirmed transaction ... mined in block" for new purchases
- Box2 does NOT show "[DBG] WLLT: Marked address ... used" for these cases.

**Comment by raedah** [comment]
fwiw, one box is amd64 and the other is arm.

**Comment by raedah** [comment]
Did it again, confirmed the issue can be recreated. Funds disappear with each ticket purchase.

**Comment by chappjc** [comment]
Have you tried with txindex or addrindx enabled?

**Comment by raedah** [comment]
@chappjc I have not. Do those take a lot of resources and downtime to generate? Not sure why it would have any effect here either.

**Comment by chappjc** [comment]
Just a few minutes.  No reason other than I have them enabled and have not seen this, and it's a recent change.

**Comment by raedah** [comment]
@chappjc I tried your suggestion, no difference.

**Comment by raedah** [comment]
Also seeing now that the number of live tickets is falling as well on box2, which reduces its usefulness as a redundant PoS box.

**Comment by raedah** [comment]
This persists in 0.6.0.  Thought the initial upgrade to 0.6.0 caused a rescan which brought the wallet up to date, it quickly fell behind again with all new tickets that were bought.

**Comment by raedah** [comment]
I have recreated this again on two other machines. Both are amd64 this time, so it has nothing to do with the arm rasp pi I was using before. 

It seems that the second box was noticing the ticket purchases and showing them in the immature count for some time, but then it stopped as if it went out of sync, and back to the behavior described above in this issue.

**Comment by raedah** [comment]
I am trying to glean more info here from the debug output. Open to other suggestions on tracking it down. This bug is a pain as it makes redundant PoS mining unreliable. Show stopper.

**Comment by raedah** [comment]
I continue to see "[INF] TMGR: Inserting unconfirmed transaction ..." on box2, so it does notice the transactions. But it does not recognize it as its own because it subtracts it from the total balance (getbalance * 0 all) and does not add it to the getstakeinfo immature count. Another point is that it does not happen with all tickets, but instead after roughly a dozen tickets that do make it to the immature count, then goes out of sync.

**Comment by raedah** [comment]
The work around for this as is follows, thx to @chappjc .
This needs to be done after any tickets are bought using Box1.
- On Box1 get the value returned from 'accountaddressindex default 1'
- Set Box2 to that value using 'accountsyncaddressindex default 1 thevalue'
- Run 'rescanwallet' on Box2.
- Run 'getstakeinfo' on Box2 and verify that the proportionlive is the now the same on Box2 as it is on Box1.

**Comment by jrick** [comment]
This should be fixed as of the 1.0.0 release, which watches for future address usage to prevent two wallets with the same gap limit from getting out of sync.  Please reopen if still an issue.

**Comment by yinhm** [comment]
I believe I still have this problem, or related. 

I have two wallets migrated from old version, all two wallets have many addresses.  I have the same setting as OP, one for voting and purchasing, the other are voting only.

I noticed inconsistent wallet balance info after some purchasing actions, the log says:
```
21:48:37 2017-05-09 [ERR] TKBY: One or more tickets could not be purchased: -32603: tried to spend zero value output from input f6a2a36..........................................., idx 1
```

The wallet will not correct itself, so what I do is restart dcrd, then do a rescan, usually begin from the low ticket price window.

The two wallets are all experienced this issue, thought they are not guaranteed to happen after ticket purchasing or after the whole purchasing window.

**Comment by raedah** [comment]
This issue is reoccurring for me as well. Restoring from seed will solve it temporarily till it occurs again. @yinhm manually advancing the indexes can help you, use accountaddressindex  and accountsyncaddressindex

**Comment by raedah** [comment]
This issue seems to be a separate consequence of https://github.com/decred/dcrwallet/issues/776
