### ISSUE TITLE
ticketbuyfreq should buy up to the specified value.

### ISSUE THREAD

**Issue by dajohi** [decred/dcrwallet#377]
ticketbuyfreq should buy up to the specified number of tickets between blocks.  It currently seems that it works by buying tickets when you have enough funds to buy the total number of tickets.

**Comment by alexlyp** [comment]
Will leave this open, but because we have deprecated the --enablestakemining option (which starts this old auto buying) ticketbuyfreq will be deprecated too

**Comment by jrick** [comment]
To clarify, it already is deprecated because it is a feature for the deprecated auto ticket buyer.

**Comment by alexlyp** [comment]
this has been deprecated.  closing
