### ISSUE TITLE
listtransactions show in double the sent coins

### ISSUE THREAD

**Issue by tpruvot** [decred/dcrwallet#39]
One for real sent amount and another one with the input bloc time, seems to be "spent transactions"

I was unable to filter them easily except for mined/generated coins. "category": "send" and "generated": true

**Comment by tpruvot** [comment]
![basic-receive-resend](https://cloud.githubusercontent.com/assets/145119/13198617/27311ed4-d80e-11e5-9b2b-d7bcf16f059c.png)

**Comment by alexlyp** [comment]
After review, this is not a bug or an enhancement request.  The dump appears to be working as expected.

2 Sends and 1 Receive.  First send it the amount to an external address, second send it the change being sent back from usage of the previous utxo.  You should be able to group by txid then from there send/receive parsing
