### ISSUE TITLE
RPC calls needed for setting enablestakemining and balancetomaintain

### ISSUE THREAD

**Issue by cjepson** [decred/dcrwallet#4]
The wallet is currently lacking the ability to adjust these parameters from the RPC.

**Comment by chappjc** [comment]
Is there currently any way to ween off of PoS without these calls, besides shutting down dcrwallet?

**Comment by cjepson** [comment]
Yes, to disable ticket price just turn ticketmaxprice to below the minimum price with the RPC. To disable stake mining in general, including voting, use 'setgenerate 0' through the wallet RPC.

**Comment by chappjc** [comment]
Thanks @cjepson, -- `setgenerate 0` was what I was after.

**Comment by toddfries** [comment]
The original topic title still bears useful consideration. What if I realy want to change the balancetomaintain so instead of maintaining 50DCR I maintain 1DCR ?

**Comment by jcvernaleo** [comment]
balancetomaintain was added with #120

**Comment by jcvernaleo** [comment]
As pointed out above, get/setgenerate enables/disables stakemining when sent to wallet.  So I think everything in the issue is taken care of.  But please reopen if there is something that is still missing.
