### ISSUE TITLE
JSON-RPC server needs API to trigger rescans

### ISSUE THREAD

**Issue by jrick** [decred/dcrwallet#405]
Due to the limitations of JSON-RPC, and that we want it to be usable from dcrctl, it won't support all the same features as the gRPC version (no streaming of progress notifications in particular), but it should at least be possible to begin the rescan.

While we want to move away from dcrctl being *the* tool that command line users use to interact with the wallet, this is the current state of things, so we should make this feature available to them.  It's also useful as a dev feature.

**Comment by raedah** [comment]
yes, id like to be able to do a rescan. Also, how about a -rescan command line option? like bitcoind.

**Comment by jrick** [comment]
All interaction with the wallet is done over rpc.  We're not adding a rescan mode to dcrwallet itself.

**Comment by jrick** [comment]
https://github.com/decred/dcrwallet/blob/master/docs/force_rescans.md can go away when this is done.
