### ISSUE TITLE
remove goclean.sh in favor of running tests directly from travis config

### ISSUE THREAD

**Issue by jrick** [decred/dcrwallet#453]
The output on travis sucks when everything is run from a single command (goclean.sh).  If these commands are run directly from the travis config the output will be much nicer and each command's output can be collapsed individually.

**Comment by jcvernaleo** [comment]
I think I said this on irc but I do not like the idea of dropping goclean.sh.  By using it from a script I can actually run the tests that travis will run in one command rather than having multiple things to copy and paste out of the .travis.yml.

**Comment by jrick** [comment]
my bad, I might have misread your comment the other day.  thought you were ok with this change.

we'll just suffer through the awful output for now
