### ISSUE TITLE
Purchase ticket <account> <amount> ignores account

### ISSUE THREAD

**Issue by codyf86** [decred/dcrwallet#46]
Sorry this is a better place for this issue than dcrd maybe. Delete issue in dcrd if need be.

Many people cannot purchase PoS tickets because it ignores the account you specify and tries to use default. Also looks like the move command is broken.

C:\Program Files\Decred>dcrctl -u -P --wallet purchaseticket CodyF86 2
-4: not enough to purchase sstx

C:\Program Files\Decred>dcrctl -u -P --wallet listaccounts
{
"CodyF86": 30.50512524,
"default": 0,
"imported": 0
}

C:\Program Files\Decred>dcrctl -u -P --wallet move CodyF86 default 10
-1: Request unsupported by dcrwallet

**Comment by cjepson** [comment]
Fixed in #104.
