### ISSUE TITLE
Changes to ticket buying and voting config settings

### ISSUE THREAD

**Issue by jrick** [decred/dcrwallet#468]
Supersedes #464.

After discussion with @alexlyp we want the following changes:

* add --enableticketbuyer config setting to turn on the new ticket buyer
* add --enablevoting config setting to turn on voting (and revocations)
* deprecate --enablestakemining with a warning message.  When set, ~~both --enableticketbuyer and~~ --enablevoting will be turned on, since these are the features the old option enabled.
  (update: only turn on the voter.  the new ticket buying uses a different algorithm and should be opt-in)
* rip out the old ticket purchasing logic.  It should not be used together with the new ticket buyer.

**Comment by jrick** [comment]
Along with this, we should decide what to do with the RPCs that query and set the ticket purchasing options.  Currently they query the wallet's old ticket buyer, and this information is wrong since it does not apply to the new purchaser.

**Comment by jrick** [comment]
Will remove them.  We want to add RPCs to change the parameters of the new purchaser for the next release, and being able to design a new and clean API will be beneficial here.

**Comment by chappjc** [comment]
Say I just use purchaseticket, then how will I set the fees?

**Comment by jrick** [comment]
New plan after more discussion with @alexlyp and @behindtext:

* add --enableticketbuyer config setting to turn on the new ticket buyer
* add --enablevoting config setting to turn on voting (and revocations)
* keep the old ticket purchasing logic.  It can not be used together with the new ticket buyer.  The old buyer is only enabled with --enablestakemining and is disabled in favor of the new buyer if --enableticketbuyer is set.
* deprecate --enablestakemining with a warning message.  When set, it should also print which ticket buyer it will use, depending on the --enableticketbuyer setting.
* keep all current RPCs.  They will only affect the old ticket purchaser.
