### ISSUE TITLE
ticketbuyer: remember purchases made during stake window

### ISSUE THREAD

**Issue by tuxcanfly** [decred/dcrwallet#485]
The new ticketbuyer feature does not write down purchases made to a file or db, so it always picks up from scratch when restarted. For reference, `dcrticketbuyer` writes this data to a file called `purchases.csv` and picks up where it left. We might need to write the db in this case rather than a csv file.

**Comment by raedah** [comment]
Id rather we just remove the highpricepenalty feature. I think its rather pointless.

**Comment by raedah** [comment]
the purchase tracking was for the ticket queue which has been removed in https://github.com/decred/dcrwallet/pull/501 .  This can be closed.
