### ISSUE TITLE
log mined transactions

### ISSUE THREAD

**Issue by raedah** [decred/dcrwallet#487]
We are currently showing things like
18:00:04 2016-12-26 [INF] TMGR: Inserting unconfirmed transaction ....
18:00:04 2016-12-26 [INF] WLLT: Successfully sent SStx purchase transaction ...

When a new block comes in, I would like to see information about my transactions that are included in a block.

For example it could look like this,
17:53:34 2016-12-26 [INF] WLLT: Connecting block ..., height 93051
18:00:04 2016-12-26 [INF] TMGR: Confirmed transaction .... in block
18:00:04 2016-12-26 [INF] TMGR: Confirmed SStx purchase transaction .... in block
18:00:04 2016-12-26 [INF] TMGR: Confirmed vote .... in block

**Comment by jrick** [comment]
Logs for attached blocks now include the number of relevant wallet transactions from the block.
