### ISSUE TITLE
insufficient funds: 4 but only 4.043, even though settxfee to 0.01

### ISSUE THREAD

**Issue by alexlyp** [decred/dcrwallet#50]
User jdavidof from freenode reports that they received the following err:

`-32603: insufficient funds: transaction requires 4 Coin input but only 4.04366253 Coin spendable`

even after using:

`dcrctl --wallet settxfee 0.01`

they subsequently tried to send 3.99 and it was successfully sent:
https://mainnet.decred.org/tx/ec1a97aef09a6f22d459fc8fd8fdb713613b66b149f946bcae06950968908831

**Comment by ocminer** [comment]
i can confirm this

**Comment by tpruvot** [comment]
the newer versions have a consolidate command to "repack" all your unspent blocks and fix this issue
