### ISSUE TITLE
ticketbuyer: use latest ticketmaxprice, balancetomaintain

### ISSUE THREAD

**Issue by tuxcanfly** [decred/dcrwallet#510]
The config options `TicketMaxPrice` and `BalanceToMaintain` can be updated via RPC using `SetTicketMaxPrice` and `SetBalanceToMaintain` respectively. `ticketbuyer` should be updated to query these from the wallet rather than using the initial ones from config.

Also, since these two config options belong to `[Ticket Buyer Options]`, they should be considered to be moved there along with a Deprecation warning as necessary.

Thanks @raedah

**Comment by dnldd** [comment]
This issue has been resolved and should be closed.
