### ISSUE TITLE
Check 0.7.0 performance on RasberryPi ( or any arm more generally) 

### ISSUE THREAD

**Issue by alexlyp** [decred/dcrwallet#519]
Think it's good to start getting a baseline of performance numbers across various architectures and OSes.  So when people ask does it run on X, we can supply relatively accurate numbers.

**Comment by jcvernaleo** [comment]
For wallet, what would you consider to be the appropriate test?  Just a fresh wallet syncing up to a totally synced up daemon or something else?

**Comment by alexlyp** [comment]
I'd think a successful test would be to have a new wallet and fetch all headers and then be able to send/receive a few tx.  I don't expect rasPi wallets to be able to handle thousands of addresses and ticketpurchasing/voting.  At least not yet.  But would be good to confirm that people can spin up a wallet on a rasPi and successfully submit basic tx if need be

**Comment by jcvernaleo** [comment]
Sounds good.  When the IBD finishes someday I'll do that.

**Comment by raedah** [comment]
I am running on a RaspPi 3 no problems. The RaspPi 3 is going to be faster then a RaspPi 2.
(1.2GHz 64-bit quad-core ARMv8 CPU) vs (900MHz quad-core ARM Cortex-A7 CPU)

**Comment by jcvernaleo** [comment]
On the rpi2B, created a fresh wallet, and it took 21m for it to download headers and full rescan on mainnet.

**Comment by jrick** [comment]
@jcvernaleo is that running both dcrd and dcrwallet on the same rpi or was dcrd on another machine?  would be good to have both data points.

**Comment by jcvernaleo** [comment]
Same machine but I didn't start the wallet up until dcrd was all synced up so at least it wasn't doing much at the time.  I can repeat with the daemon on another box (amd64, I don't feel like waiting for a second rpi to do a full download).

**Comment by jcvernaleo** [comment]
@jrick I retried as you asked with a fresh mainnet dcrwallet on the rpi and a fully synced daemon on a fast linux box.  Headers and rescan took 8m.

**Comment by jcvernaleo** [comment]
Fresh wallet sync for testnet (both on the rpi) took 1h3m.

**Comment by jcvernaleo** [comment]
Also, send and receive tx works as expected on the rpi so I think that covers all that we want and I'm closing the issue.  Feel free to reopen if there are any additional numbers anyone thinks would be useful.
