### ISSUE TITLE
balance reporting discrepancy causes error

### ISSUE THREAD

**Issue by raedah** [decred/dcrwallet#521]
ticketbuyer is reporting a higher spendable balance,
`15:00:16 2017-01-10 [DBG] TKBY: Current spendable balance at height 245054 for account 'default': 333.91656516 DCR`

ref: https://github.com/decred/dcrwallet/blob/master/ticketbuyer/buyer.go#L365-L369

then what dcrctl shows,
```
> getbalance
22.59846163

```
Because of this, ticketbuyer is trying to purchase tickets with the funds. 
Dcrwallet strangely gives this error, when something about not enough funds is expected.

```
14:57:27 2017-01-10 [ERR] TKBY: Failed to purchase tickets this round: -22: TX rejected: orphan transaction 08ec1639a2adad70fb20777257e5a2b8de029c5cff950806ecec2994dea47693 references outputs
of unknown or fully-spent transaction 1629e656fe12bda7ebf048d5b2a83bc60bad3977de4f46478f00598b206c9f03

```

**Comment by raedah** [comment]
possibly this https://github.com/decred/dcrwallet/issues/314

**Comment by raedah** [comment]
In addition, funds seem to have disappeared from my testnet wallet when this error was triggered.

**Comment by raedah** [comment]
Anyone who uses  ticketbuyer.spreadticketpurchases  from https://github.com/decred/dcrwallet/pull/502 will hit this issue at the end of the window when they use up all their funds.

**Comment by dajohi** [comment]
Can you test with #544 ?

**Comment by hb9xar** [comment]
Here, still reporting different spendable values on testnet (dcrwallet ticketbuyer vs dcrctl getbalance)
- dcrwallet (ticketbuyer):
22:27:13 2017-02-06 [DBG] TKBY: Spendable balance for account 'default': 19511.12798622 DCR

- dcrctl --wallet getbalance
      "spendable": 18635.28495298,

**Comment by raedah** [comment]
For me, it is no longer reproducible with the new getbalance

**Comment by raedah** [comment]
I am seeing this again, running the latest code.

**Comment by raedah** [comment]
What I am seeing now is the msg
[ERR] TKBY: Failed to purchase tickets this round: insufficient funds available to construct transaction

After that error occurs, I see the Available and Spendable funds decrease in value, though the log does not show any transactions were created. The Total funds in this case remains the same.

**Comment by n1000** [comment]
Any update on this @raedah ? I'm seeing a similar error message, but I have not tried any of these fixes yet (still on the official 0.8.2 release).

**Comment by n1000** [comment]
I'm not sure if I'm getting the same error message (will check it next time I reproduce the issue), but I definitely see a balance discrepancy issue that is fixed with a wallet recreation & rescan.

In my case, I have "extra" funds before a rescan.

I'm running 1.0.1.

"lockedbytickets", and "votingauthority" are identical before and after rescan, but "spendable" increases by ~1.3 % (slightly under-reporting before scan), and "total" decreases by ~20% (grossly over-reporting before scan).

**Comment by raedah** [comment]
This is likely a variation of https://github.com/decred/dcrwallet/issues/776

**Comment by raedah** [comment]
Is no longer occurring. Closing.
