### ISSUE TITLE
Wallet not resending unmined transactions on startup

### ISSUE THREAD

**Issue by jrick** [decred/dcrwallet#535]
As discovered while reviewing #534, Wallet.resendUnminedTxs appears to never be called in the current code.  This function is responsible for resending unmined transactions when the wallet connects to the dcrd server and has finished rescanning all new blocks on the chain.

Before just adding it back, we should look through git history first and see why this function call was removed, whether it was an accident or if it was to prevent some bug (and introduced another bug in its place).

**Comment by dajohi** [comment]
Fixed by #542
