### ISSUE TITLE
invalid tickets remain in stakepooluserinfo result even after ticket spent

### ISSUE THREAD

**Issue by chappjc** [decred/dcrwallet#540]
`stakepooluserinfo` will list invalid tickets that are already spent. In the case I am looking at, the tickets were spent by a ssgen. I don't recall adding the invalid tickets manually to the pool so I believe the user let their wallet vote using the import script.

invalid tickets that are voted, missed, or expired should be removed from the stakepool user info

Issue originally created as https://github.com/decred/dcrstakepool/issues/77

**Comment by jrick** [comment]
Can you describe what you mean by "invalid" tickets?

**Comment by chappjc** [comment]
Tickets that end up in the `"invalid"` category of the stakepooluserinfo result.  These are tickets that did not pass the requirements to be voted on by the pool (fee amount, fee address) but for which the wallet has an applicable redeemscript.

**Comment by jolan** [comment]
Looks like this was fixed in ea7c468d2f4193b7841dda27efe71ff5c8e2fefe but since you opened the issue a few months after the commit, maybe it doesn't work properly?

**Comment by chappjc** [comment]
I don't think that addresses the case when the ticket is *not* added.  Eventually the ticket is missed or the owner votes on it or the owner revokes.  Past the point when the ticket is called to vote, it should be removed from stakepool ticket database entirely (obviously not put in missed).

**Comment by jolan** [comment]
Oops, right.  I guess I didn't read the issue description too well.

**Comment by chappjc** [comment]
It seems that spent tickets no longer appear in the "invalid" array from stakepooluserinfo.  Closing.
