### ISSUE TITLE
Weird Json error when trying to creating wallet

### ISSUE THREAD

**Issue by pedrotst** [decred/dcrwallet#543]
Every time I try to create a wallet I have the error shown in the picture below

![decred wallet error](https://cloud.githubusercontent.com/assets/6591091/22604894/b9adb892-ea34-11e6-9126-d700d1cb7c1b.png)

**Comment by jrick** [comment]
That is actually https://github.com/decred/copay not dcrwallet, and we're aware of the issue but haven't gotten around to fixing it yet.  It used to only affect edge (https://github.com/decred/copay/issues/6) but now it seems to happen on every browser that is not Chrome/Chromium.
