### ISSUE TITLE
Security of --walletpass 

### ISSUE THREAD

**Issue by Chocanto** [decred/dcrwallet#545]
Hey !

Like `--promptpass`, I wonder if it is possible to **create a new parameter** that would allow the user to write his passphrase for master public key via a prompt.

Without this option, I always have to execute my command in a shell and then remove the command from my bash history in order to keep my password secret.

**Comment by jcvernaleo** [comment]
One trick you can use (in bash at least, I don't think it works in ksh) is to have a single space at the start of your command.  That prevents it from being saved to the history.  So run it as:
```
 dcrwallet --some options
```
instead of
```
dcrwallet --someoptions
```

**Comment by jrick** [comment]
@jcvernaleo wonder if that depends on something in your bash configuration, tried it here and I still see it listed in `history` and searchable with `C-r`.

**Comment by Chocanto** [comment]
Thank you for this advice, that's also a good idea !
But you may agree with me that it is the exact opposite of user-friendly. And anything that is not user-friendly in security leads to insecurity :/

@jrick Works for me (bash, Ubuntu)

**Comment by jcvernaleo** [comment]
@jrick I have a hell of a lot in my .bashrc so it is always possible.  Not as bad as my .emacs, but close.

**Comment by jrick** [comment]
@Chocanto be aware that even with it not saved in shell history, arguments are visible to all users on the system.  Check the output of `ps aux`.

**Comment by Chocanto** [comment]
@jrick Yes, and I'm pretty sure that we can find dozen of way to read a password given clear using command parameter. That's why I requested this feature :smiley:

I will try to see if I can write this up

**Comment by onyx4** [comment]
I was shocked personally that this is the default method for entering your passphase to unlock the wallet.  The command line argument will also show briefly under the ps output and in /proc under Linux as cmdline arguments for the process.   Users by default will have the bash history saved, if someone grab your files, they can easily see your bash history and unlock your wallet.  There should be an interactive method for unlocking the wallet that doesn't require a command line.

**Comment by jrick** [comment]
It was intended to be put in the config file.  The config file and command line options are the same, so that meant it was also changeable on the cli.

**Comment by Chocanto** [comment]
I don't think that storing the public passphrase in a simple config file is better thank using the command line.
I agree with you for the private passphrase != public passphrase, but if anyone (with enough knowledge) can access to this passphrase, what is the aim of defining a public pass to protect public data ?

**Comment by jcvernaleo** [comment]
I'd argue that you shouldn't use your wallet on a multiuser system anyway so if someone has access to the unencrypted filesystem with your wallet you likely have bigger problems anyway.

**Comment by Chocanto** [comment]
Yes you are right :) 
But I am more afraid by users putting one of their "main" password (it's a very bad practice, yes, but the majority of users are not security experts...) into a config file or a command parameter.

**Comment by jrick** [comment]
To be totally honest the option is not very useful.  I personally never use it, and it wasn't added to the software at my request either.

1. Transactions are not saved encrypted, only addresses and pubkeys.  So if you do a bit of correlation you can figure out the addresses anyways.
2. We use a key/value database.  When keys must also be encrypted, this dramatically complicates DB design and results in tons of inefficiencies.
3. As you have noted, there is not a good mechanism to input the public passphrase, except if the wallet is opened over the gRPC server, in which case the passphrase can be entered as a request parameter to the open wallet method.

It would be better to do all public data encryption at the filesystem level rather than encrypting individual keys and values in the database itself.

**Comment by chappjc** [comment]
Yeah, doing this on a multiuser system is madness, so file system permission serve the purpose well enough.

@Chocanto true about switching the passwords.  Happened a lot on the forum a while ago

**Comment by Chocanto** [comment]
Well, you can't juste remove a feature like that, so maybe the only solution is to do complete encryption with a better input like you suggested ?

**Comment by jrick** [comment]
I'll bring it up with the team so we can decide what to do about it.  However I don't expect the feature to go away, especially since that would prevent anyone that has enabled the feature from accessing their wallets.
