### ISSUE TITLE
occasional messages about wallet reconnecting to dcrd

### ISSUE THREAD

**Issue by chappjc** [decred/dcrwallet#550]
I'm testing with --notls and I've noticed the wallet does this occasionally now:

    [INF] CHNS: Established connection to RPC server localhost:9109

Maybe a few times overnight.  I don't ever recall seeing this before. The connections are usually rock solid.

Running master for dcrd and dcrwallet from a few days ago.  It may have nothing to do with --notls, but it seems likely.

**Comment by jrick** [comment]
Probably fixed by #612, please reopen with more details if this still occurs.
