### ISSUE TITLE
need to adjust walletinfo RPC for stake pool safety check

### ISSUE THREAD

**Issue by jolan** [decred/dcrwallet#555]
The stake pool ensures that the result of the walletinfo RPC has "stakemining": true in it when starting up to ensure that the wallets are properly configured.

enablevoting causes "stakemining" to be set to false where as the deprecated enablestakemining sets it to true.

This incompatibility needs to be rectified before enablestakemining can be properly deprecated and removed.

**Comment by onyx4** [comment]
I noticed that too when using the new options for enabling voting. Will this prevent from stake mining or it's just cosmetic ?

**Comment by jrick** [comment]
"Stake mining" was ambiguous.  It was split up into two config options, one for buying tickets, and one for voting on live tickets and revoking missed/expired ones.  Both of these options are functional, but `walletinfo` does not return any info about these options.

The new options are not cosmetic.  The new --ticketbuyer option enables entirely new ticket purchasing code that was ported from dcrticketbuyer. and it replaces the old ticket buying that was enabled from --enablestakemining.
