### ISSUE TITLE
RPC reconnect creates two conflicting instances of ticket buyer

### ISSUE THREAD

**Issue by raedah** [decred/dcrwallet#558]
Here is the RPC disconnect

06:45:06 2017-02-11 [ERR] CHNS: Timeout waiting for session RPC
06:45:06 2017-02-11 [INF] DCRW: Attempting RPC client connection to localhost:9109
06:45:06 2017-02-11 [INF] CHNS: Established connection to RPC server localhost:9109
06:45:06 2017-02-11 [INF] WLLT: Beginning a rescan of active addresses using the daemon. This may take a while.
06:45:06 2017-02-11 [INF] WLLT: Wallet voting enabled
06:45:06 2017-02-11 [INF] WLLT: Please ensure your wallet remains unlocked so it may create stake transactions
06:45:06 2017-02-11 [INF] TKBY: Starting ticket buyer

I was using custom trace msgs which started spitting out double to the logs.
TKBY failure msg repeats every block that gets connected.

07:08:26 2017-02-11 [INF] WLLT: Connecting block 00000...5e8c, height 106543
07:08:26 2017-02-11 [TRC] TKBY:  idxDiffPeriod 127, windowPeriod 739
07:08:26 2017-02-11 [TRC] TKBY:  idxDiffPeriod 127, windowPeriod 739
07:08:26 2017-02-11 [ERR] TKBY: Failed to purchase tickets this round: Failed to calculate average ticket price amount: the client has been shutdown

**Comment by tuxcanfly** [comment]
This should be fixed in #532.

**Comment by jrick** [comment]
Closing since the referenced PR should have fixed this.
