### ISSUE TITLE
ticketbuyer.minfee gets ignored

### ISSUE THREAD

**Issue by karamble** [decred/dcrwallet#560]
My config files had included the minfee:
`ticketbuyer.minfee=0.23`

but the ticketbuyer purchased with 0.01 in the first block of the pricewindow:

`04:16:30 2017-02-13 [INF] TKBY: Purchased ticket XXXXX at stake difficulty 34.37657635 (0.01 fees per KB used)`

**Comment by raedah** [comment]
I dont see any reason why this would occur. Set logging to debug mode to get more information. I will dial up my minfee and see if I can duplicate.

**Comment by dajohi** [comment]
@karamble can you run with --debuglevel debug to see if any additional logs show up regarding the fee?

**Comment by dajohi** [comment]
@karamble Can you give https://github.com/decred/dcrwallet/pull/648 a try?

**Comment by dajohi** [comment]
Possibly fixed by #648.  Reopen if still an issue.
