### ISSUE TITLE
Total balance

### ISSUE THREAD

**Issue by ghost** [decred/dcrwallet#564]
I want to see total balance and sum of spendable balances of all accounts in the wallet, like it was before, when I used these calls:
```
dcrctl --wallet getbalance "*" 0 all
dcrctl --wallet getbalance "*" 0 spendable
```

**Comment by Dyrk** [comment]
Right now I use this formula to calculate my total balance:
```
sum(total) + sum(immaturecoinbaserewards) + sum(immaturestakegeneration) + ownmempooltix * stake_difficulty
```
