### ISSUE TITLE
Disappearing funds which only come back with restore from seed

### ISSUE THREAD

**Issue by raedah** [decred/dcrwallet#569]
Disappearing funds which only come back with restore from seed.
Always accompanied by  
[ERR] TKBY: Failed to purchase tickets this round: cannot get address info: address not found
Occurs when funds in wallet are low, but not empty.

Here is the trace log, though Im not seeing any other helpful lines here.

> 
> 19:51:30 2017-02-15 [DBG] WLLT: Get new address for branch 1 returned TskzBoDSHycNV7wCVgJXgs4D4tkVNbRaw4B (idx 33960) from the address pool
> 19:51:30 2017-02-15 [TRC] CHNS: Sending command [loadtxfilter] with id 50890
> 19:51:30 2017-02-15 [TRC] CHNS: Received response for id 50890 (result null)
> 19:51:30 2017-02-15 [DBG] WLLT: Closing address batch for pool branch 1, next index 33961
> 19:51:30 2017-02-15 [TRC] CHNS: Sending command [getstakedifficulty] with id 50891
> 19:51:30 2017-02-15 [TRC] CHNS: Received response for id 50891 (result {"current":53.66732232,"next":53.66732232})
> 19:51:30 2017-02-15 [DBG] WLLT: Get new address for branch 1 returned TsWCwPpVtga3UaSEXAD8NksKm6wAoFLpo2Z (idx 33961) from the address pool
> 19:51:30 2017-02-15 [TRC] CHNS: Sending command [loadtxfilter] with id 50892
> 19:51:30 2017-02-15 [TRC] CHNS: Received response for id 50892 (result null)
> 19:51:30 2017-02-15 [DBG] WLLT: Get new address for branch 1 returned TsmmKQhP86NSHM32cTFVrxJMvAN1RYfZBG4 (idx 33962) from the address pool
> 19:51:30 2017-02-15 [TRC] CHNS: Sending command [loadtxfilter] with id 50893
> 19:51:30 2017-02-15 [TRC] CHNS: Received response for id 50893 (result null)
> 19:51:30 2017-02-15 [TRC] CHNS: Sending command [sendrawtransaction] with id 50894
> 19:51:31 2017-02-15 [TRC] CHNS: Received response for id 50894 (result "10238941768daf98b3a309b9bab9fc2711b6ced81d4db323520ee780e4fe70c9")
> 19:51:31 2017-02-15 [INF] TMGR: Inserting unconfirmed transaction 10238941768daf98b3a309b9bab9fc2711b6ced81d4db323520ee780e4fe70c9
> 19:51:31 2017-02-15 [TRC] CHNS: Received notification [relevanttxaccepted]
> 19:51:31 2017-02-15 [DBG] WLLT: Marked address TsWCwPpVtga3UaSEXAD8NksKm6wAoFLpo2Z used
> 19:51:31 2017-02-15 [DBG] WLLT: Marked address TsmmKQhP86NSHM32cTFVrxJMvAN1RYfZBG4 used
> 19:51:31 2017-02-15 [DBG] WLLT: Get new address for branch 1 returned Tsfo5qE1gwP8AHu1RpBXABQpJJF9h7tsEmb (idx 33963) from the address pool
> 19:51:31 2017-02-15 [TRC] CHNS: Sending command [loadtxfilter] with id 50895
> 19:51:31 2017-02-15 [TRC] CHNS: Received response for id 50895 (result null)
> 19:51:31 2017-02-15 [DBG] WLLT: Closing address batch for pool branch 1, next index 33964
> 19:51:31 2017-02-15 [ERR] TKBY: Failed to purchase tickets this round: cannot get address info: address not found
> 19:51:31 2017-02-15 [INF] TMGR: Inserting unconfirmed transaction 10238941768daf98b3a309b9bab9fc2711b6ced81d4db323520ee780e4fe70c9
> 19:51:36 2017-02-15 [TRC] CHNS: Received notification [spentandmissedtickets]
> 19:51:36 2017-02-15 [TRC] CHNS: Received notification [spentandmissedtickets]
> 19:51:36 2017-02-15 [TRC] CHNS: Received notification [blockconnected]
> 19:51:36 2017-02-15 [TRC] CHNS: Received notification [winningtickets]
> 19:51:36 2017-02-15 [INF] WLLT: Connecting block 0000000006256ebb45630197a2efd2f89dfc29a984cfdf1663cbcd8c67777907, height 271057
>

**Comment by raedah** [comment]
Seems it may be related to this other error that also occurs in the same conditions.

11:06:24 2017-02-17 [ERR] TKBY: Failed to purchase tickets this round: -22: TX rejected: orphan transaction 914f28ed424cc6ba983ec91e282e430eb6e48bb6bbe1988d33edfb7a310fc5c4 references outputs of unknown or fully-spent transaction 9828c46c6abee504e14c42256b2346b188d8cd60ad2c8c6a3d2c4369f8c8c940

**Comment by dajohi** [comment]
`$ dcrctl --wallet --testnet gettransaction 9828c46c6abee504e14c42256b2346b188d8cd60ad2c8c6a3d2c4369f8c8c940`

does that exist?

If so, `$ dcrctl --testnet sendrawtransaction hash`

That may fix it.. but there is a lingering bug.

**Comment by raedah** [comment]
> gettransaction 9828c46c6abee504e14c42256b2346b188d8cd60ad2c8c6a3d2c4369f8c8c940
{
  "amount": 0,
  "fee": 0.00621,
  "confirmations": 0,
  "blockhash": "",
  "blockindex": 0,
  "blocktime": 0,
  "txid": "9828c46c6abee504e14c42256b2346b188d8cd60ad2c8c6a3d2c4369f8c8c940",
  "walletconflicts": [],
  "time": 1487346977,
  "timereceived": 1487346977,
  "details": [
    {
      "account": "",
      "amount": -496.5000985,
      "category": "send",
      "fee": 0.00621,
      "vout": 0
    }
  ],
  "hex": "010000000315e67dd169dfcec9cfbb25c471e39d5ed2169fc74c8f5bf966f0669d879204510200000000ffffffffcd616f99679b3022eb55d2ced158694d288b934a253a3c0544488f3db5429f290200000001ffffffffff26af4297269c55ec10c0b251a228a9d43c2c167c63d055cda4a319c396763d0200000000ffffffff03c04c089d0000000000001976a91430a05a0d3183f165a6c6e4cbe285b55bd7ce1c8a88acc04c089d0000000000001976a91430a05a0d3183f16
5a6c6e4cbe285b55bd7ce1c8a88acb2f344550a00000000001976a91483cf89598b0a80925a2b0b61d05b5cf59b6c251888ac000000000000000003ffffffffffffffff00000000ffffffff6a4730440220642664ca7994523150310c3dd108dcdb936b7f3dab2ccbad072e212edfe74645022063732089edb54b5528f1e74aab8535882fba8e77909cc69d669643e9ec8c368c012102fb27eade5697ef364e4976b7fe4905a64456b19b7f67e39a5ca68af618f3b0f5ffffffffffffffff00000000ffffffff6b483045022100f62ea8245bfd636ada94449e7e43fb64f7a0a5b74a7a908b77c710c14fffc192022035fcd4438fd39efa8aaaf2013caa27e3b4fe435f91a2415d91f9d65082727ae9012103d58e92aca51b8eb7309e2b48b263070bc7278cd3d7c6d459a066f5eea4c9e97affffffffffffffff00000000ffffffff6b483045022100d09c0ebb46250d2ac41aec654fccdadce6a31ab5a521009e559a1152355fbdf302205dbd9fc33e88af89df35f1c4572269734612c343273373463f746ce3af079494012103424d4a53249122e59b57ba319ae44e46e58958ec7d225278d18487c5c3830ac7"         


> sendrawtransaction 010000000315e67dd169dfcec9cfbb25c471e39d5ed2169fc74c8f5bf966f0669d879204510200000000ffffffffcd616f99679b3022eb55d2ced158694d288b934a253a3c0544488f3db5429f290200000001ffffffffff26af4297269c55ec10c0b251a228a9d43c2c167c63d055cda4a319c396763d0200000000ffffffff03c04c089d0000000000001976a91430a05a0d3183f165a6c6e4cbe285b55bd7ce1c8a88acc04c089d0000000000001976a91430a0
5a0d3183f165a6c6e4cbe285b55bd7ce1c8a88acb2f344550a00000000001976a91483cf89598b0a80925a2b0b61d05b5cf59b6c251888ac000000000000000003ffffffffffffffff00000000ffffffff6a4730440220642664ca7994523150310c3dd108dcdb936b7f3dab2ccbad072e212edfe74645022063732089edb54b5528f1e74aab8535882fba8e77909cc69d669643e9ec8c368c012102fb27eade5697ef364e4976b7fe4905a64456b19b7f67e39a5ca68af618f3b0f5ffffffffffffffff00000000ffffffff6b483045022100f62ea8245bfd636ada94449e7e43fb64f7a0a5b74a7a908b77c710c14fffc192022035fcd4438fd39efa8aaaf2013caa27e3b4fe435f91a2415d91f9d65082727ae9012103d58e92aca51b8eb7309e2b48b263070bc7278cd3d7c6d459a066f5eea4c9e97affffffffffffffff00000000ffffffff6b483045022100d09c0ebb46250d2ac41aec654fccdadce6a31ab5a521009e559a1152355fbdf302205dbd9fc33e88af89df35f1c4572269734612c343273373463f746ce3af079494012103424d4a53249122e59b57ba319ae44e46e58958ec7d225278d18487c5c3830ac7      
                                                                                                                                                                                                                                                                               9828c46c6abee504e14c42256b2346b188d8cd60ad2c8c6a3d2c4369f8c8c940

**Comment by raedah** [comment]
transaction just mined
https://testnet.decred.org/tx/9828c46c6abee504e14c42256b2346b188d8cd60ad2c8c6a3d2c4369f8c8c940
and some of the disappeared funds have returned

**Comment by raedah** [comment]
In other cases, using  sendrawtransaction  shows me another error of "-22: TX rejected: orphan transaction ... references outputs of unknown or fully-spent transaction ..." over again for each depth. A chain of failed transactions referencing each other.

**Comment by raedah** [comment]
I kept stepping back through the chain until I got to this error.

-22: TX rejected: transaction 9f6f9161c4536dfd43ce2a5fbc8db7d4c2d71888499ea05a5f25228f5f00f291 has not enough funds to meet stake difficuly (ticket diff 5231976979 < next diff 15589073160)

**Comment by raedah** [comment]
Is no longer occurring. Closing.
