### ISSUE TITLE
Next generation SDiff

### ISSUE THREAD

**Issue by raedah** [decred/dcrwallet#574]
Price change percentage would correspond with percent change in ticket pool size.
Example, pool target size is 40960. Maximum tickets purchased in a window is 144 * 20 = 2880. Tickets redeemed in that window is 144 * 5 = 720. So actual ticket increase is 2880 - 720 = 2160.  pool size 40960 + added tickets 2160 = 43120.  
New window pool size 43120 divided by last window pool size 40960 = 1.0527
So 5.27% would be the maximum price increase in a window when all possible ticket purchase slots are filled.
If no tickets were bought then the target pool size of 40960 would fall by 144 * 5 = 720 to 40240.
New window pool size 40240 divided by last window pool size 40960 = 0.982%, which is a maximum 1.75% decrease in ticket price from the last window when no tickets are bought.

So, a ticket price of 50 DCR could adjust up 5.27% to 52.63 DCR, or adjust down 1.75% to 49.12 DCR.

I have modeled this here
https://play.golang.org/p/QSV4ssuZ4O

**Comment by raedah** [comment]
I have modeled this here
https://play.golang.org/p/gn_mI2Uo-L

**Comment by raedah** [comment]
I have modeled this here
https://play.golang.org/p/gn_mI2Uo-L

**Comment by alexlyp** [comment]
This should be in decred/dcrd. Please close and reopen there
