### ISSUE TITLE
Watch for transactions involving future addresses, synchronize with other wallets sharing seed and generating addresses

### ISSUE THREAD

**Issue by jrick** [decred/dcrwallet#580]
There should be a mechanism for watching for transactions involving addresses beyond the last created address (in both the internal and external bip0044 account branches, not just external as bip0044 says).

The reason to also watch for internal addresses is that we want to do this lookahead as a way to watch out for address use by other wallets sharing the same seed so we can keep them automatically in sync.

The amount of addresses that should be looked ahead is equal to the address gap, 20.  If both wallets respect the address gap, there is no way for them to get out of sync.  Conversely, if one wallet generates addresses beyond that address gap without address use in any address before it, synchronization is not guaranteed.

**Comment by raedah** [comment]
should solve https://github.com/decred/dcrwallet/issues/367
