### ISSUE TITLE
setticketvotebits sets the extended vote bits and allows the vote version to be incorrectly specified or cleared

### ISSUE THREAD

**Issue by jrick** [decred/dcrwallet#581]
This is observable with the current implementation of the testnet stakepool and the vote bits for the hard fork demo.  The vote version should never ever be set by the user.

We may want to simply remove the get/setticketvotebits RPCs, but this will have to wait until the stakepool no longer relies on it for storing user vote bits.  Until then, and if we decide on removing these, I am ok with a quick hack that hardcodes the extended vote bits.

**Comment by alexlyp** [comment]
We have currently made it so wallets in stakepool mode disregard any existing extend vote bits that we saved in the db.  This will ensure proper vote versions are set for votes from stakepools.  Stakepool users can still set their options for yea/nay on previous blocks and yea/nay/abstain for agendas.

**Comment by jrick** [comment]
Fixed by #583.
