### ISSUE TITLE
older blocks are sent to ticketbuyer when syncing chain

### ISSUE THREAD

**Issue by raedah** [decred/dcrwallet#595]
When reconnecting your node and dcrd is syncing up the latest blocks, all these new blocks are sent to the ticketbuyer causing it try and buy tickets for blocks that are already passed, and attempting to do a lot of purchases back to back if its several blocks. The correct behavior should be to detect if these are older blocks that are not the tip of the chain, and to not send the block to ticketbuyer for processing if that is the case.

**Comment by jrick** [comment]
are you talking about blocks that are being reevalutaed during a rescan, or are you doing the dcrd IBD and wallet is attaching blocks like normal (not doing the sync to dcrd)?

**Comment by raedah** [comment]
when dcrd is offline for a period, and then on reconnect a large series of blocks are attaching like normal

**Comment by raedah** [comment]
Worth noting that if dcrd and dcrwallet are loading for the first time, and dcrd is catching up lots of blocks, only the most recent block is sent to the ticketbuyer which is the correct behavior. The bad behavior happens with a network failure when the ticketbuyer is already running. When the network reconnects, lots of blocks are sent to the ticketbuyer.
