### ISSUE TITLE
ticketbuyer.maxpricescale

### ISSUE THREAD

**Issue by karamble** [decred/dcrwallet#626]
One of the users complained about not beeing able to use the ticketbuyer.

Log Output: 
`17:06:46 2017-03-21 [INF] TKBY: Not buying because the next window estimate 111.17760141  DCR is higher than the scaled max price 106.8617475  DCR`

The `maxpricescale` parameter is no longer in the dcrwallet.conf samples, but it looks like it have to be adjusted to enable the ticketbuyer as seen in that logfile output. I just suggested to add:

`ticketbuyer.maxpricescale=3.0` 

Aftwerwards it worked.

Eather add it into the sample.conf of dcrwallet or realy remove it and mark it obsolete.

https://github.com/decred/dcrwallet/blob/master/ticketbuyer/buyer.go#L76

**Comment by alexlyp** [comment]
This has been classified as DEPRECATED:
https://github.com/decred/dcrwallet/blob/master/config.go#L185

along with PriceTarget

They will remain included for a release or 2 then removed entirely.

Closing
