### ISSUE TITLE
Failed to find vote in blockchain while generating stake info...

### ISSUE THREAD

**Issue by dyarkovoy** [decred/dcrwallet#633]
Getting these messages repeatedly and dcrwallet doesn't attempt to purchase tickets:

18:28:19 2017-03-29 [TRC] WLLT: Failed to find vote in blockchain while generating stake info (hash 240e8045295fca1e99f88bc0204bfeb89b76a2dc278e64df41483b76c8ec09df, err %!s(<nil>))

Can be fixed by recreating the wallet from the seed, but then again after a couple of days the problem reoccurs. Running the latest 0.8.2 version.

**Comment by jrick** [comment]
Any errors in logs before that?

**Comment by dyarkovoy** [comment]
before I recreated the wallet last time, if I remember correctly, there was another message -  "Failed to find ticket in blockchain ..." with similar ending. No other errors as far as I can see.
