### ISSUE TITLE
Feature Request: Specify wallet location

### ISSUE THREAD

**Issue by Neurosploit** [decred/dcrwallet#64]
To me it feels very weird that I can only have a single wallet on my machine in a fixed place. Is it possible to have the option for me to specify the wallet location so I can have multiple wallets on one machine in the location I prefer? I can imagine that some households have multiple users using the same account both wanting to have their own wallet.

**Comment by chappjc** [comment]
datadir already does this.

**Comment by Neurosploit** [comment]
Okay so I need to pass in the datadir on every command? Or will it remember it until I specify it again.

**Comment by chappjc** [comment]
You can put it into a config file, and use --configfile.
