### ISSUE TITLE
'walletpassphrase sekrit 0' should not be undone by walletpassphrase with a timeout

### ISSUE THREAD

**Issue by jrick** [decred/dcrwallet#664]
The wallet should instead remain unlocked until an explicit walletlock is performed.

**Comment by jcvernaleo** [comment]
Agreed.

**Comment by jolan** [comment]
I've also noticed 'walletpassphrase wrongsekrit 0' will re-lock the wallet rather than just throwing an error that the wallet is already unlocked for the specified time.  Not sure if that should be a separate issue.

**Comment by jrick** [comment]
@jolan i added an extra log for that case, if it was unlocked before and a wrong passphrase caused it to be locked, that is now logged.

**Comment by jolan** [comment]
Yeah I saw that, thanks.  I think that is good enough, at least now it's not silently locked.
