### ISSUE TITLE
getnewaddress returns previously issued address

### ISSUE THREAD

**Issue by richiela** [decred/dcrwallet#68]
I have no repro but we have seen dcrd return previously used addresses when calling getnewaddress multiple times.  

in this case, the counter looked to be rolled back 4 addresses (ie, i called getnewaddress 4 times before getting an address that wasn't previously used).

**Comment by cjepson** [comment]
Will look into this today. I think it's an issue with unsafe access to the address pool.

**Comment by chappjc** [comment]
Repeats here to.  Only seen one actually.  From the same wallet on the same machine.

**Comment by cjepson** [comment]
Issue seems to be that there is no BatchFinish() call after calling the respective GetNewAddress function. Normally this isn't an issue, but if a transaction fails for any reason it will reset the counter to before the GetNewAddress call. Will have a patch for this shortly.
