### ISSUE TITLE
RPC ports listed in help are for Bitcoin instead of Decred

### ISSUE THREAD

**Issue by davecgh** [decred/dcrwallet#7]
Reported by `simple` on IRC.

I confirmed it as well:

```bash
$  dcrwallet -h
...
  /c, /rpcconnect:          Hostname/IP and port of dcrd RPC server to connect
                            to (default localhost:18334, mainnet:
                            localhost:8334, simnet: localhost:18556)
...
      /rpclisten:           Listen for RPC/websocket connections on this
                            interface/port (default port: 18332, mainnet: 8332,
                            simnet: 18554)
...
```

The correct ports should be as follows:
```
dcrd:
mainnet: 9109
testnet: 19109
simnet: 18556

dcrwallet:
mainnet: 9110
testnet: 19110
simnet: 18557
```

Also, the dcrd simnet port looks to be the same as it is for btcd.  It should be changed to something unique for decred as well.

**Comment by jcvernaleo** [comment]
I fixed the text.  Thanks for catching that.

As for the simnet port, I'm going to change both to 19556 and 19557 to not overlap but also to remain symmetric.  Both of these changes will be in the next release.
