### ISSUE TITLE
getstakeinfo needs performance improvements

### ISSUE THREAD

**Issue by jrick** [decred/dcrwallet#706]

**Comment by jrick** [comment]
#709 improved this by quite a bit but there is still more work that should be done.  Namely there needs to be a way to get the 0th input values of votes without deserializing the entire transaction.

**Comment by tpruvot** [comment]
I know its not exactly related to performances, but imo this rpc result should include the staking/voting status (like walletinfo)

**Comment by jrick** [comment]
@tpruvot No i don't want to add anything more to this RPC, it is already doing too much and is poorly named.  getstakestatistics would be better name for what this RPC is used for.  info can mean anything you want it to mean.

**Comment by jrick** [comment]
Regarding improving the performance of this RPC, with the new existsmissedtickets will go a long way.  This means dcrd will no longer need to send every missed ticket ever to the wallet and the wallet won't have to go searching through them to see if any are owned by the wallet.
