### ISSUE TITLE
Sweeping utxos/accounts/wallets

### ISSUE THREAD

**Issue by jrick** [decred/dcrwallet#733]
There are situations where a user may want create an on-chain transaction that moves as much value as possible in a transaction, rather than specifying the exact intended amount to send.

Possible usecases include spending a single UTXO, multiple specific UTXOs, all UTXOs of a single account, and perhaps even all UTXOs from a wallet (this last one would correlate accounts).

This is similar to and can replace the existing consolidate RPC.

**Comment by jrick** [comment]
As a side note, sweeping accounts is already possible with the gRPC method [WalletService.ConstructTransaction](https://github.com/decred/dcrwallet/blob/master/rpc/documentation/api.md#constructtransaction) by using the `ALL` selection policy, not proving any outputs in the `non_change_outputs` field, and using the destination address as the custom change address.

**Comment by chappjc** [comment]
`consolidate` does this too, using the output address argument

**Comment by chappjc** [comment]
Haha, just read the last part of the issue description.  Oops
