### ISSUE TITLE
Add gRPC API to watch for and notify transaction confirmations

### ISSUE THREAD

**Issue by jrick** [decred/dcrwallet#752]
Consumers of the gRPC API have requested a way to watch for the confirmation status of a transaction without subscribing to all transaction and block notifications and doing the work themselves to verify that a transaction got mined and so many other blocks were attached without it being reorged.  An RPC that implements this functionality on the wallet's end would be preferred to making the client do the work.

I propose an RPC that with the following API:

```
rpc ConfirmationNotifications (ConfirmationNotificationsRequest) returns (stream ConfirmationNotificationsResponse);

message ConfirmationNotificationsRequest {
    bytes tx_hash = 1;
    int32 stop_after = 2;
}
message ConfirmationNotificationsResponse {
    int32 confirmations = 1;
}
```

A request will specify a single transaction hash to watch and a maximum number of confirmations to watch before the stream is closed.  The hash must be of a relevant wallet transaction.  A stream of confirmations is returned so the current number of confirmations can be notified to the client.  A response message should be sent for the very last confirmation result before the stream is closed.  If a wallet transaction is removed from the wallet (e.g. due conflicting with a mined double spend) the value -1 will be returned by the response stream and the stream will be closed.  If the RPC is called on a transaction that already has more than stop_after confirmations, a single result with the current number of confirmations will be sent, and then the stream will close.

**Comment by marcopeereboom** [comment]
Any reason we would not batch these instead of sending 1 request per tx_hash?

**Comment by jrick** [comment]
Can't return multiple streams.

Batching is also, in general, unnecessary due to gRPC's architecture, where all messages are sent over a single channel.  Batching is much more necessary in the HTTP JSON-RPC server to prevent unnecessary connections.

**Comment by jrick** [comment]
I'm open to other suggestions for how the RPC should look though.

**Comment by marcopeereboom** [comment]
Well I agree with the gist I am just a little apprehensive when introducing chatter.  That said, I prefer this over not having it.  So by all means go ahead and get this done so that I can use it :-)

**Comment by jrick** [comment]
There are ways we could reduce it, e.g.:

```
rpc ConfirmationNotifications (stream ConfirmationNotificationsRequest) response (stream ConfirmationNotificationsResponse);

message ConfirmationNotificationsRequest {
    repeated bytes tx_hashes = 1;
    int32 stop_after = 2;
}
message ConfirmationNotificationsResponse {
    message TransactionConfirmations {
        bytes tx_hash = 1;
        int32 confirmations = 2;
    }
    repeated TransactionConfirmations confirmations = 1;
}
```

**Comment by marcopeereboom** [comment]
I like that.  Would you mind explaning why we can't do this on the way in too?

**Comment by jrick** [comment]
not sure what you mean, the request is already a stream, and the message is a repeated (array) of hashes.

**Comment by marcopeereboom** [comment]
Oh I missed that.  Derp.  So yes, I like that with the repeated bits.

**Comment by jrick** [comment]
Ok, i'll go with that but need to figure out how it will deal with corner cases.  with an API like this i would expect responses to be sent once every time the best chain tip changes, but more messages would need to be sent when a request comes in for a tx way beyond stop_after.  Also need to figure out if the stream automatically closes when no more watched txs exist, or if the client should close it when it is finished.

**Comment by jrick** [comment]
Development happening at https://github.com/jrick/btcwallet/tree/confntfns
