### ISSUE TITLE
Update flags to allow for default spread ticket purchases

### ISSUE THREAD

**Issue by alexlyp** [decred/dcrwallet#755]
Due to the way flags operate we must switch usage of SpreadTicketPurchases to NoSpreadTicketPurchases.  Now we can default it to false (which is equal to SpreadTicketPurchases=true).

This will deprecate SpreadTicketPurchases and be a breaking change

**Comment by jrick** [comment]
My mistake, this isn't a breaking change after all due to the deprecation of the option rather than its removal.
