### ISSUE TITLE
Ticketbuyer maxpricerelative looks low after testnet sdiff algo updated.

### ISSUE THREAD

**Issue by alexlyp** [decred/dcrwallet#759]
Observed maxpricerelative going too low after the new sdiff kicked in.  May have something to do how past ticket prices are calculated.

But in general with the new sdiff algo ticketbuyer ticket price targeting needs an update due to no more major swings.

**Comment by alexlyp** [comment]
@raedah thoughts on changes we can do to ticketbuyer to accomodate the more accurate ticket price algorithm?

**Comment by alexlyp** [comment]
After looking at data of sdiff, this was most likely due to an especially low period in sdiff, so the average was abnormally low.

45361 , 4.52234839
45505 , 1.13058709
45649 , 0.57565195
45793 , 0.77150476
45937 , 3.08601904
46081 , 12.34407616

-- NEW SDIFF BEGIN -- 

46225 , 17.79130847

**Comment by alexlyp** [comment]
I'm going to leave this issue open to discuss possible changes to ticketbuyer decision making with the new algo.

**Comment by raedah** [comment]
I dont expect to see the testnet behavior above occurring on mainnet. Im not aware of any other settings that will need immediate tweaking, but once we get some live results we can probably refine a few of the defaults. After the new sdiff kicks in, I expect the avg price calculation might become more useful then it has been. May even bring over options from the dynamic stabilizer branch to further reduce volatility.

**Comment by alexlyp** [comment]
sdiff has been seen to be acting as expected on testnet.  closing issue
