### ISSUE TITLE
I'd like to move the user folder.

### ISSUE THREAD

**Issue by zimmah** [decred/dcrwallet#771]
As usual, decred dumps a lot of stuff in C:\Users.   
My C:\ drive is intentionally kept small and reserved for the OS. Therefore, there is no space for all the decred stuff there.    
How can I move this stuff to a different drive?

**Comment by jrick** [comment]
--appdata

**Comment by zimmah** [comment]
Thanks for the quick response, but I'm not very technical. Do you mean I have to run launcher.exe with the -appdata command line? I assume followed by a space and a path where I want the data to go?   
So run launcher.exe --appdata "D:\folder\" ?    
    
Is that correct?    
If it's not correct, can you please give instructions a noob can understand?

**Comment by jrick** [comment]
--appdata is a dcrwallet option, and launcher.exe is part of paymetheus not dcrwallet...

paymetheus does not support changing the appdata directory.

Your best option would be to run dcrd yourself from the command line (setting --appdata to another drive) and then either using dcrwallet also on the command line with a different --appdata, or running paymetheus in the default location.

These options also only modify the locations that blockchain and user data is written, not the installer's install locations.  Those can't be changed.

**Comment by zimmah** [comment]
so --appdata is an argument to dcrd.exe?

**Comment by jrick** [comment]
yes

```
PS C:\Users\jrick> dcrd -h
Usage:
  C:\Users\jrick\Go\bin\dcrd.exe [OPTIONS]

Application Options:
  /A, /appdata:               Path to application home directory
                              (C:\Users\jrick\AppData\Local\Dcrd)
...
```

**Comment by zimmah** [comment]
Ok thanks, I will try that.
