### ISSUE TITLE
Ticketbuyer tries to spend funds that do not exist, creates failing transaction loop

### ISSUE THREAD

**Issue by raedah** [decred/dcrwallet#776]
This is a re-occurance of earlier bugs https://github.com/decred/dcrwallet/issues/569 , https://github.com/decred/dcrwallet/issues/547 and https://github.com/decred/dcrwallet/issues/521

This occurred on a wallet that was built from seed using dcrwallet v1.0.1

"[ERR] TKBY: Failed to purchase tickets this round: -32603: orphan transaction xxx references outputs of unknown or fully-spent transaction xxx"

I used gettransaction and sendrawtransaction to get through the hierarchy of failed transactions.

"orphan transaction xxx references outputs of unknown or fully-spent transaction xxx"

which brought me to

"transaction xxx has not enough funds to meet stake difficuly (ticket diff 3925329204 < next diff 3982285161)"

**Comment by jrick** [comment]
I will need some more details to debug this.  It is a double spend but i have not yet been able to track down the cause.

Can you check the outputs of the 'fully-spent transaction" and then make sure that your wallet has these outputs?  Can you provide logs of when each of these were created?

Was this running 1.0.1 release or a dev version?

**Comment by raedah** [comment]
This was 1.0.1. It looks to me like this was a ticket purchase that happened near the end of the window and for whatever reason it is not getting invalidated at the window switch over. I will try and get the logs you asked for, but will have to wait to duplicate it.

**Comment by yinhm** [comment]
This happened to me again, 

```
15:01:15 2017-06-05 [INF] WLLT: Connecting block 000000000000011e911ecb7b095a9bf67eff123214904f7bcf42a1ddce656a82, height 139468
15:01:18 2017-06-05 [ERR] TKBY: One or more tickets could not be purchased: -32603: orphan transaction XXX references outputs of unknown or fully-spent transaction XXX
15:01:18 2017-06-05 [ERR] TKBY: Failed to purchase tickets this round: -32603: orphan transaction XXX references outputs of unknown or fully-spent transaction XXX
```

I checked that  "unknown or fully-spent transaction" on the mainnet, it seems like a coin split if I interpreted it correctly.

The next thing I do is rescan from a recent block(before the split) to fix it.

**Comment by lbiazao** [comment]
I'm having the same issue I have tried to send transaction in the end of the cycle while buying tickets and trying to send the remaining decreds to another wallet:
https://github.com/decred/decrediton/issues/420
Any help how to fix the wallet issue?

**Comment by lbiazao** [comment]
Following some help from Emilio Man I have recreated the wallet from the seed and the wallet started working properly again.

**Comment by yinhm** [comment]
Alright, what I said do a rescan fix it previous is false. 
What really happened is that fee over my limit, so it did not happen right away.
It happened this round, a wallet restart and rescan fixed it. And my balance seems correct now.

**Comment by raedah** [comment]
"[DBG] TKBY: Available funds of", 
is reporting a different number that is higher then what getbalance shows for "spendable".
getbalance "spendable" is lower then what TKBY shows as available.

"[DBG] TKBY: Available funds of " 
is lower then
"[DBG] TKBY: Usable balance for account 'default' after purchases"
After purchases should be lower, but instead it is higher.
This is not the case before the bug occurs. 
Before the bug, the before purchase value is higher as it should be.
https://github.com/decred/dcrwallet/blob/master/ticketbuyer/buyer.go#L871-L872

This is the first occurrence in the logs. I dont see anything special here.
[ERR] TKBY: One or more tickets could not be purchased: -32603: tried to spend zero value output from input xxxx, idx 0
[DBG] TKBY: Usable balance for account 'default' after purchases: xx.xx DCR
[ERR] TKBY: Failed to purchase tickets this round: -32603: tried to spend zero value output from input xxxx, idx 0

./dcrctl --wallet getrawtransaction xxx
./dcrctl --wallet sendrawtransaction xxx
-32603: transaction already exists

**Comment by raedah** [comment]
I am able to reproduce this consistently. It is occurring when the ticketbuyer tries to buy tickets when there are not enough funds available to buy tickets. dcrctl getbalance is showing funds have been exhausted, but ticketbuyer debug logs show a larger 'Available funds', so ticketbuyer is trying to buy. This creates the failed transaction that becomes an orphan, causing all further transactions to fail. I am going to raise balancetomaintainabsolute and see if that functions as a work around from triggering the condition.

**Comment by raedah** [comment]
Any user who lowers the default balancetomaintainrelative to 0 will encounter this error. It results in invalid orphan transactions in the wallet db, which cause all further transactions to fail. The resolution is to rebuild the wallet from seed.

**Comment by jrick** [comment]
@raedah Thanks for continuing to investigate this, but i'm confused about one thing.  How are we creating transactions at all when there is not enough spendable outputs to use for inputs?

**Comment by jrick** [comment]
I also don't see a way, at least in the latest master branch, that the send would fail and that the ticket purchase would still be performed.  The transaction is only created in a view, and then an update is performed when sending.  If the transaction is invalid, this step will fail, and the update that added the transaction will also be rolled back.  https://github.com/decred/dcrwallet/blob/5a416aee8cc06a4d35b3de00bb529b14e4ab7cfa/wallet/createtx.go#L385

**Comment by raedah** [comment]
Perhaps the failure is not actually an orphan tx. It could just be a continuing bad input selection. Ticketbuyer is attempting to perform the purchase because it sees available funds, but then it fails, because when it goes to do the split transaction it errors with ' tried to spend zero value output from input'. But at this point, even if real funds do become available, ticketbuyer will continue to hit this same error.

I do not know what causes the balances to skew. After rebuilding from seed, they are initially identical.

**Comment by jrick** [comment]
I'm pretty sure the cause is a double spend.  When all of a transaction's outputs are spent, the transaction is no longer recorded in the utxo index at all and lookups using it will fail.  This is why the error messages say "fully-spent or unknown" because the tx might have never existed, or it could have been fully spent already.  If it was fully spent, this indicates a double spend.

**Comment by raedah** [comment]
noting that ticket buyer gets balance here
https://github.com/decred/dcrwallet/blob/master/ticketbuyer/buyer.go#L557

which calls this code
https://github.com/decred/dcrwallet/blob/master/wallet/wallet.go#L1632-L1646

which calls this code
https://github.com/decred/dcrwallet/blob/master/wallet/udb/txmined.go#L3717-L3743

**Comment by raedah** [comment]
I have confirmed that the balance skewing happens when ticketbuyer beings purchasing tickets. No failed transactions have occured at this point.

**Comment by raedah** [comment]
The difference in the amount grows in proportion to the number of tickets purchased. The growth of the difference always around 0.3 - 0.7 DCR which is around where the fee being paid is. 

Since restoring from seed will fix the balance until purchasing tickets begins to skew it again, this must be an issue with data that is being written to the wallet db (when the ticketbuyer is used), rather then simply an error calculating the balance after the data is read.

**Comment by gravityz3r0** [comment]
Just to add, ticketbuyer may not be entirely a culprit as I am using CLI manual purchase and still facing this problem occasionally.

**Comment by raedah** [comment]
Is no longer occurring. Closing.
