### ISSUE TITLE
When consolidating, max transaction size is 85k (expected 100k)

### ISSUE THREAD

**Issue by mverrilli** [decred/dcrwallet#786]
This doesn't seem to be a problem, really... just unexpected. I'm logging it because I am actually having a different issue to report that may or may not be related to how the size is calculated. I'll add a link to it later. 

Basically, if doing a consolidate on a lot of transactions... it will cap the size of the consolidation transaction to 85k when I expected it to be 100k.

**Comment by alexlyp** [comment]
Also related to tx size calculation.

Due to size overestimation, the consolidation transactions were given too high of fee (and thereby do not match what is set in settxfee (RelayFee)

Fixed in #788
