### ISSUE TITLE
listtransactions need to populate "account" label

### ISSUE THREAD

**Issue by richiela** [decred/dcrwallet#8]
We assign GUIDs to address to make sure not only the address matches, but the guid matches as extra security.  listtransactions doesn't properly populate the field.

query dcrcoin validateaddress "TsXfyM6SLS1JhqXDds58YGoMEQuuyMdQj7X"
{
  "isvalid": true,
  "address": "TsXfyM6SLS1JhqXDds58YGoMEQuuyMdQj7X",
  "ismine": true,
  "pubkeyaddr": "TkKmN6PYmKy6Q7qMhJmqtFUc5Yrnx2CRMAdd2KFwhrJL4WDEohWBG",
  "pubkey": "026b1bc6c1c7068f09771ffcad32b3b53da33e0f9545c760d970c4ce49ba2661d7",
  "iscompressed": true,
  "account": "d25f76a6-da7b-456c-b615-dee68d859362"
}

 query dcrcoin listtransactions
[
  {
    "account": "",
    "address": "TsXfyM6SLS1JhqXDds58YGoMEQuuyMdQj7X",
    "amount": -50,
    "category": "send",
    "confirmations": 0,
    "fee": -0.01,
    "time": 1454270237,
    "timereceived": 1454270237,
    "txid": "647a664a1b8c01d27ba7b9bbe619c1413b83abd4928ff798d40dfa3a353e6bdb",
    "vout": 1,
    "walletconflicts": []
  },
  {
    "account": "",
    "address": "TsXfyM6SLS1JhqXDds58YGoMEQuuyMdQj7X",
    "amount": 50,
    "category": "receive",
    "confirmations": 0,
    "time": 1454270237,
    "timereceived": 1454270237,
    "txid": "647a664a1b8c01d27ba7b9bbe619c1413b83abd4928ff798d40dfa3a353e6bdb",
    "vout": 1,
    "walletconflicts": []
  },

**Comment by jrick** [comment]
Looks like a bug, I'll see what I can do.

**Comment by jcvernaleo** [comment]
This is resolved with the commit from upstream in the latest master.
