### ISSUE TITLE
getbalance showing errorneously between lockedbytickets, votingauthority and total.

### ISSUE THREAD

**Issue by gravityz3r0** [decred/dcrwallet#821]
*Using dcrwallet 1.0.3/1.0.5*

I think this issue has been created somewhere but i thought of submitting some data output in assisting the bug squashing.

I'm doing PoS via "VPS hot voting wallet" and also "Pool mining". These are my getbalance output :

On VPS:  
{
     "accountname": "default",
     "immaturecoinbaserewards": 0,
     "immaturestakegeneration": 0,
     "lockedbytickets": 0,
     "spendable": 0,
     "total": 8590.25381921,
     "votingauthority": 8620.83221921
   },

On my main wallet which i imported script from the pool :
 {
     "accountname": "imported",
     "immaturecoinbaserewards": 0,
     "immaturestakegeneration": 0,
     "lockedbytickets": 2175.57874403,
     "spendable": 0,
     "total": 2174.24083072,
     "votingauthority": 2179.08828322
   }

**My observation:**

1. On both cases, my voting authority is not the same as my total. 
2. In addtion, my "lockbytickets" on the pool also differs from "total"
3. Running --rescanwallet does not fix the problem
4. I remember that these number used to tally with each other in the past. It only start appearing from 1.0.3 onwards.
5. Running dcrctl --wallet listunspent and adding up all the numbers manually confirmed that only the "Total" shows the correct figure.

**Comment by dajohi** [comment]
Does dcrctl --wallet listunspent on both wallets match?

**Comment by gravityz3r0** [comment]
--wallet listunspent value if added up together, matches only the "total" of both wallets.

**Comment by raedah** [comment]
This looks like a variation of https://github.com/decred/dcrwallet/issues/776
