### ISSUE TITLE
Oversized record received with length 

### ISSUE THREAD

**Issue by Terry108** [decred/dcrwallet#829]
I want to disable TLS for the RPC server.
So I started the dcrd with "dcrd --testnet --notls" without tls, then start my wallet "dcrwallet --testnet", one error prompt:"[ERR] CHNS: Connection attempt failed: tls: oversized record received with length 20527".

**Comment by jcvernaleo** [comment]
That error means one piece is using tls and the other is not.  If you use `--notls` with dcrd (which is really only there to allow some legacy software to work) you also need the option `--noclienttls` in dcrwallet.  Generally it is best to use tls though unless you have some other software that cannot handle it (in which case I would run a dcrd instance just for that software.

**Comment by jrick** [comment]
Yes that is correct.  They are speaking different protocols so you will see strange errors like that.  `--noclienttls` is the correct wallet option to have unencrypted dcrwallet <-> dcrd RPC.  There currently isn't a way to turn off TLS for the wallet's RPC server.
