### ISSUE TITLE
Target machine actively refused it

### ISSUE THREAD

**Issue by Terry108** [decred/dcrwallet#832]
I have built a virtual Ubuntu on my host windows system. I install the decrd and dcrwallet on the virtual Ubuntu system, then I start it with "dcrd --testnet" and "dcrwallet --testnet". 
I make a RPC connection follow by the step of client usage(https://github.com/decred/dcrwallet/blob/master/rpc/documentation/clientusage.md) . It works fine on virtual Ubuntu system, but doesn't work when I connect the RPC on my host windows system. Besides, the connection is well between the virtual and host system.
The error as below:
rpc error: code = Unavailable desc = grpc: the connection is unavailable
INFO: 2017/06/30 14:57:23 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp 192.168.120.33:19111: connectex: No connection could be made because the target machine actively refused it."; Reconnecting to {192.168.120.33:19111 <nil>}

I have no idea that the **actively refused** of wallet server gRPC.

**Comment by jrick** [comment]
The RPC servers only listen on loopback interfaces by default (127.0.0.1 and ::1).  You need to change the rpclisten config options to add listeners for your private network.

**Comment by jrick** [comment]
Closing since this is a configuration problem.
