### ISSUE TITLE
Can't Receive Crypto's (Invalid Address)

### ISSUE THREAD

**Issue by FrencisAlreadyInUse** [decred/dcrwallet#834]
I can't receive any coins on my decred wallet.

I tryed both sending from the coinbase app and webplatform. I got both 'Please enter a valid email or Bitcoin address'. 

I both copied and scanned (qr-code) the generated address but failed every single time.

http://i66.tinypic.com/imuu53.jpg (Coinbase App, scanned the Generated Decred QR-code)

http://i64.tinypic.com/107q1a8.jpg (Coinbase Webplatform, copied the Decred Generated Address)

**Comment by jrick** [comment]
So ignoring the fact that you aren't even using the software in this repo and are complaining about some other software we didn't write...

Those errors are correct.  That is not a valid bitcoin address.  Even if it was you wouldn't receive any decred in your wallet.  The addresses are intentionally incompatible to prevent this sort of situation in the first place.

**Comment by FrencisAlreadyInUse** [comment]
Hi sir,

I'm actually using the decred software 100%. It's the decred generated qr-code that I scanned within the coinbase app and the decred generated address I copied from the decredation OS app.

I even tryed the wallet.decred.org and copied the generated address from my wallet as well.

Kind Regards,
Francis De Clercq

**Comment by jrick** [comment]
This is not decrediton.  (Real) decrediton bugs should be reported to https://github.com/decred/decrediton/issues.

My original comment still stands.  You can not use a decred address to receive a bitcoin payment.

**Comment by FrencisAlreadyInUse** [comment]
Oke cool, how can I transfer btc to my decreed wallet then?
