### ISSUE TITLE
dcrwallet should not continue when specified config file is not present

### ISSUE THREAD

**Issue by jcvernaleo** [decred/dcrwallet#835]
```
jcv@triforce ~ $ dcrwallet -C .dcrwallet-main/
10:49:00.519 2017-07-06 [WRN] DCRW: read .dcrwallet-main: is a directory
10:49:00.520 2017-07-06 [INF] DCRW: Version 1.0.4+dev (Go version go1.8.3)
10:49:01.203 2017-07-06 [INF] WLLT: Opened wallet
```

In that example, I incorrectly specified a config file with `-C` and things kept running with the default config which can lead to confusing errors.

**Comment by chappjc** [comment]
https://github.com/decred/dcrwallet/issues/233

Gets me often

**Comment by jrick** [comment]
@chappjc I'm confused, that issue was resolved.  Am i missing something?
