### ISSUE TITLE
getbalance numbers diverge with age of wallet

### ISSUE THREAD

**Issue by raedah** [decred/dcrwallet#850]
This appears related to https://github.com/decred/dcrwallet/issues/776 but am filing as a separate bug since it is looking at a different set of symptoms.

To test this I setup several instances of my wallet, with all instances being voting wallets, and only one instance being a buying wallet. They were all built from seed and used v1.0.5. 
A day later I again rebuilt the main buying wallet from seed, and compared this to the voting wallets. The voting wallets show the following.

"immaturestakegeneration" is the same 
"lockedbytickets" is lower
"spendable" is higher
"total" is slightly lower (difference likely caused by small fees on ticket buys)
"votingauthority" is lower.

Doing a rescanwallet will bring the numbers closer to where they should be, but a large divergence remains unless the wallet is rebuilt from seed. It can be noted that the balance divergence is on voting only wallets, which is opposed to the older theory that it was only a problem on wallets that were running ticketbuyer. None the less, the divergence may be being caused by ticket buys.

**Comment by raedah** [comment]
Just saw this, https://github.com/decred/dcrwallet/pull/843

**Comment by jrick** [comment]
Fixed by #843.
