### ISSUE TITLE
Add new Unconfirmed field to getbalance response

### ISSUE THREAD

**Issue by alexlyp** [decred/dcrwallet#852]
Adding this will hopefully alleviate reported problems from users about 'vanishing' balances upon sending funds or purchasing tickets.

In lieu of changing the getbalance default minconf to 0, we decided that showing the unconfirmed amount would accomplish the same thing.

**Comment by jrick** [comment]
Note that this should always be zero when the minconf parameter was set to zero.  It is just total spendable - unspendable by minconf policy, so when minconf is zero, there is nothing to remove from the balance.
