### ISSUE TITLE
Pid file location 

### ISSUE THREAD

**Issue by mmitech** [decred/dcrwallet#855]
I am trying to set a systemd script for dcrd and dcrwallet, but I can't have this work properly since I don't know where both the daemon and wallet save their .pid files?

**Comment by jrick** [comment]
Neither dcrd nor dcrwallet fork to a background daemon.

We have an example systemd unit file for dcrd [here](https://github.com/decred/dcrd/blob/master/release/services/systemd/dcrd.service) and all it takes is defining the service with the "simple" type.

**Comment by mmitech** [comment]
you are right, that fixed my issues. Thanks
