### ISSUE TITLE
How to change wallet gap limit?

### ISSUE THREAD

**Issue by Crypto2** [decred/dcrwallet#899]
Hello,

We've run into problems it seems with the gap limit, since we have to assign users addresses they may or may not ever use even though they requested it. We did see the options for getnewaddress so we are able to get addresses without limits not but it seems like transactions to these addresses aren't showing up in listtransactions/listsinceblock.

**Comment by jolan** [comment]
You should just be able to manipulate the watched addresses index by using the accountsyncaddressindex RPC.

i.e. if you want to watch the first 10000 addresses of the default account:

```
dcrctl --wallet accountsyncaddressindex default 0 10000
```

This is the solution that https://github.com/decred/dcrstakepool uses to accomplish roughly the same thing.

**Comment by jrick** [comment]
The gap limit can be changed with the --addridxscanlen option (terrible name, I would like to rename it to just --gaplimit), but you found the right options.

There was an issue fixed that is current in the master branch that caused addresses that should have been watched to be missed, and could cause the missing transactions you are seeing.  What version of the software are you running? Latest release or building latest from source?

**Comment by Crypto2** [comment]
Thanks, yeah I agree that option didn't stand out to me when I was trying to figure it out. We're using the latest release fromhttps://github.com/decred/decred-release/releases/tag/v1.0.5

**Comment by jrick** [comment]
Give master a try if you can (build instructions in the README), otherwise we may have a release out in the next week.

**Comment by Crypto2** [comment]
Compiling from latest source seems to have worked, I just set --addridxscanlen and did a rescan of the last few days of blocks and all the missing TXIDs I know of are showing up now. :)
