### ISSUE TITLE
getnewaddress should createnewaccount if it doesn't exist

### ISSUE THREAD

**Issue by richiela** [decred/dcrwallet#9]
query dcrcoin getnewaddress a1c021f5-17ea-46a6-b08e-4ca7a6f0a1e6
-4: account name 'a1c021f5-17ea-46a6-b08e-4ca7a6f0a1e6' not found

I understand that i can call 'createnewaccount' first, but to keep things closer to btc (and to not disrupt current btc workflows) getnewaddress should just check if the account exists... if it doesn't, it should createnewaccount and then getnewaddress.

**Comment by jrick** [comment]
This could be done, but there's a catch.  The wallet has to be unlocked in order to create a new account.  We use BIP0032/44 accounts, which use BIP0032 hardened extended keys, and that means deriving the next account key therefore requires the wallet passphrase.

**Comment by richiela** [comment]
That makes sense... so if getnewaddress is called on an existing account, it should just work as BTC, if the account does not exist, a walletpassphrase being required makes sense.

**Comment by jrick** [comment]
Going to close this and require account creation to be an explicit process instead, due to the requirement of needing the wallet unlocked for this to work.
