### ISSUE TITLE
improve UI for rescan button

### ISSUE THREAD

**Issue by mmquimby** [decred/dcrwallet#914]
Please add an "Are you sure?" with description of function, or something similar, to the Rescan button in the wallet.

I'm a new user and just waited overnight for blockchain to load up. Then I did a test transfer into the wallet. Waited a moment, and then saw this juicy button labeled "Rescan". I thought it might scan for current transactions so I clicked it. Horrified that it started full blockchain scan again. Wish it had warned me or been clearer. Even just renaming button "Rescan Entire Blockchain" would be an improvement, though overly long.

**Comment by jrick** [comment]
dcrwallet has no GUI.  Did you mean to report this to Decrediton instead?

**Comment by mmquimby** [comment]
Yes. Can ticket be transferred? And is Decrediton built by the core
decredit team or is it 3rd party?

**Comment by jrick** [comment]
We're the same team but GitHub doesn't let us transfer issues between the different projects.  I'll let the Decrediton lead know about the issue and you can reopen a new issues in that repo if you'd like.

**Comment by mmquimby** [comment]
OK I will. Thanks.
