### ISSUE TITLE
Import Airdrop Wallet 

### ISSUE THREAD

**Issue by klaveren** [decred/dcrwallet#926]
I participated in the beginning of the Decred project, and I would like to activate my wallet
of AIRDROP, but I'm not finding clear information on how to activate this wallet.
I have the data:
 
First address:
Extended public key:
Sure the password.

Any idea?

**Comment by alexlyp** [comment]
Download a wallet, then create a new wallet using your 33 word seed.  Come to slack.decred.org if you need any further assistance.

Closing since this is not an issue.
