### ISSUE TITLE
Advise user to use --promptpublicpass

### ISSUE THREAD

**Issue by Chocanto** [decred/dcrwallet#930]
**Issue** : 
When user try to open a secured wallet (with a public password) without using `--walletpass` or `--promptpublicpass`, dcrwallet respond with :
```
[ERR] DCRW: Open failed: invalid passphrase for master public key
```

In this case, the user know there is a problem related to a "master public key" but do not know how to solve it.

**Proposed solution** : 
Advise user to use either `--promptpublicpass` or `--walletpass`.
```
[INF] DCRW: Try again with --promptpublicpass
```

**Comment by rvacek** [comment]
Anyone working on this?

**Comment by Chocanto** [comment]
Nobody it seems, I can work on it if everyone is ok with it
