### ISSUE TITLE
Removing split transactions for some ticket buying cases

### ISSUE THREAD

**Issue by raedah** [decred/dcrwallet#933]
Since the new sdiff algo was activated with efficient pricing to stabilize the ticket price, the market is no longer filling all ticket purchase slots in the blocks. A split transaction that happens before the sstx ticket purchase was originally implemented in April 2016 in https://github.com/decred/dcrwallet/pull/183 . Its purpose was so that change for a large user balance wouldn't be stuck in limbo for ticket purchase transactions that were not getting confirmed. Split transactions solved the change problem, but increased increased overall fee cost and block chain usage by adding an additional transaction to the process. The additional transaction also makes a ticket purchase take an additional block since the split tx must confirm first. 

The proposal is to make split transaction an option that can be disabled, and that it is disabled by default in order to keep a lot of unnecessary transactions off the blockchain and lower user cost. With split txs turned off, the sstx transaction size would be slightly larger since it will include a change output, but less size overall then using the additional split tx.

Work has been started on this issue and current progress is here:
https://github.com/shweini/dcrwallet/tree/SplitTransaction

**Comment by jrick** [comment]
I don't think that was the only reason why it was done that way.  I'd have to check code again but I thought that the change output of a ticket also had a maturity period, because it is in the regular tx tree while the ticket output is in the stake tree.

**Comment by alexlyp** [comment]
@jrick is exactly right here.  This was done due to the UX of having to wait for sstxchange to mature sucks.

**Comment by alexlyp** [comment]
I'm ok with having an option to disable it, but that feature would need to be turned off by default.  If we truly want to do away with split tx this would need to be handled in consensus handling of SSTXCHANGE outputs.  What that fix would entail... who knows.  And it should go without saying, but that would require a DCP and CV to change the rules.  I believe @jrick and @davecgh have kicked around a couple ideas to handle them better.

**Comment by raedah** [comment]
If a user sends an sstx and it gets confirmed in the next block (as it actually does with the new sdiff) then they would get their change back in the next block. This is the same amount of wait time as sending a split tx in order to get change in the next block. The only behaviour I observed of change taking longer with sstx is when they are not getting included in blocks due to ticket purchase slots being filled. But what I think you guys are saying is that you believe maturity time is longer? How long? Can we empirically verify this?

**Comment by AhmedMSedeek** [comment]
Tried
dcrctl --wallet purchaseticket "default" 100 1 "" 1 "" 0 0 "" true
on testnet and it also creates split transaction

**Comment by raedah** [comment]
Sorry @AhmedMSedeek, that option param made it in too early and is not active yet. I believe it will be ready for the next release.

**Comment by AhmedMSedeek** [comment]
Thanks for replying @raedah

**Comment by raedah** [comment]
Split transactions on ticket purchases were implemented for reasons that primarily had to do with the behavior of the sdiff algo at the time. Purchasing tickets during high fee cycles would mean that a sstxchange could get stuck in the mempool for a long time, potentially making all of a users funds unavailable. This no longer occurs with the current sdiff algo. SStxChangeMaturity is 1 block, so a user can get their change back quickly as long as the tx is not created with an expiry. Doing the ticket purchase without a split transaction would reduce unnecessary transactions on chain, and save users cost in tx fees.

Rather then having it be an option, I now believe there is no useful purpose for it in most cases and dcrwallet would just use the optimal behavior.

**Comment by jrick** [comment]
Closing due to lack of interest.

**Comment by xaur** [comment]
I suggest to revisit this discussion for two reasons.

First is UX: when I buy tix, I wait them to be mined. It is annoying to wait extra blocks for the split tx to be mined too.

Second is privacy: say I buy 10 tix at once, the split tx is generated that takes a bunch of inputs and generates a bunch of ticket outputs in a single tx. It ties together a bunch of inputs and outputs that could have been unrelated, thus facilitating chain analysis.
