### ISSUE TITLE
Ensure that tickets can not be bought with voting rights for another solo voter. 

### ISSUE THREAD

**Issue by jrick** [decred/dcrwallet#972]
jz made the point on slack that an "interesting attack" would be for ticket buyers to buy tickets with voting rights delegated to a solo voter.  While stakepools run checks that they will only vote on tickets that have a high enough pool fee commitment, this is not something that a solo voter is able to check.  We need to make sure that votes can not be delegated to a commonly-online voter in hopes of piggy-backing off their infrastructure to vote whenever the ticket is picked.

**Comment by chappjc** [comment]
A proper solution would be nice, since this little abuse has been whispered about for far too long, but in the meantime, here is a solution for solo stakers to generate an arbitrarily long list of voting addresses: https://github.com/chappjc/hdaddy

**Comment by jrick** [comment]
Duplicate of #221.
