### ISSUE TITLE
Add or modify gRPC call to get all transaction outputs

### ISSUE THREAD

**Issue by matheusd** [decred/dcrwallet#973]
In order to fix [decrediton issue 683 (show voting info on transaction details)](https://github.com/decred/decrediton/issues/683) there are three alternatives:

1. The transactionDetails structure must be modified to include all transaction outputs 
2. The transactionDetails structure must be modified to include a "voteInfo" substructure
3. A new gRPC endpoint must be created to return the full transaction info.

I'd lean towards the third option (new endpoint) but I'd like to get a feel for what the other devs think. If possible, I'd like to also try and tackle this issue.

**Comment by jrick** [comment]
superseded by #979
