### ISSUE TITLE
Users are not informed if they pay the wrong ticket pool fee.

### ISSUE THREAD

**Issue by rvacek** [decred/dcrwallet#978]
If a user pays the wrong ticket pool fee the tx still 'processes' but tickets arnt put in the voting pool.  Rather they are marked 'invalid'.  User is still unaware of this process and cannot learn what happened to missing DCR till logging onto their stake pool sites.  Here they educated and learn from: 

_Alert! Tickets appearing here did not pay the correct pool fee. You will either need to vote these tickets yourself or contact your stake pool administrator to have them add the ticket to the pool manually._

Rather then feeling dismay or loosing out on ROI user should be warned when purchasing tickets that don't have an acceptable fees.

**Comment by jrick** [comment]
we can't do anything about misconfigured software. the wallet will just do what it is told to do. there's no sidechannel connection to the pool like decrediton has so the correct fee can't be queried.
