### ISSUE TITLE
Support creating a wallet from a non-extended key

### ISSUE THREAD

**Issue by chappjc** [decred/dcrwallet#98]
It should be possible to create a wallet from a non-extended private key (i.e. the output of `dcraddrgen --noseed)`.  Requires support for a creation method that accepts only a key, not a seed.  Requires wallet operation that does not involve generating deterministically-generated key pairs from a seed.  Does this also require the public key or a derived address during creation?

Ref: https://forum.decred.org/threads/finally-made-my-decred-address.109/page-3#post-1813

EDIT:  This doesn't have to be a full-fledged (and deprecated in bitcoin) [loose-key wallet](https://bitcoin.org/en/developer-guide#loose-key-wallets) (a.k.a. JBOK), just one private key.

**Comment by cjepson** [comment]
A wallet requires a default account to derive change addresses, etc from. importprivkey works fine as it is. I think it's best to discourage key reuse by not allowing a single key wallet.

The biggest issue is that the imported account doesn't quite work right now. That's being corrected. You can still signrawtransaction with imported keys in the meantime.

**Comment by chappjc** [comment]
OK, I'm not familiar with the workflow for importprivkey, but it sounds like it does the job but with a default account created with a seed.  Is there an issue for the trouble with imported account you described, @cjepson, or should I leave this opened for that?

**Comment by cjepson** [comment]
You can leave this open, fixing accounts will fix this and about 4 other issues. It's coming along this week, it's just a lot of code to write.

**Comment by cjepson** [comment]
Imported account and spending from it fixed in #104.
