### ISSUE TITLE
Cannot cancel wallet creation

### ISSUE THREAD

**Issue by matheusd** [decred/dcrwallet#984]
After starting wallet creation with `dcrwallet --create`, I cannot cancel it with a CTRL+C (SIGINT) only with a CTRL+\ (SIGQUIT) or higher. 

A SIGINT starts the wallet shutdown process, but if wallet setup is at the stage of reading user prompts they are not canceled. Plus, if the current prompt is a password prompt, echo to the terminal is not restored by ending the wallet process with a SIGQUIT.

**Comment by jrick** [comment]
#974 #982
