### ISSUE TITLE
Allow quick command to reset dcrwallet.  

### ISSUE THREAD

**Issue by rvacek** [decred/dcrwallet#993]
Users should be able to reset wallet quickly rather then having to navigate through directories.  Wallet resets are done by deleting wallet.db 

Proposed Solution: 

 A simple `./dcrwallet --reset` command could work with a extra barrier such as when you must type `OK` when obtaining a new seed at wallet creation.

**Comment by brandonblock** [comment]
Interested in taking this one on

**Comment by jrick** [comment]
I think this is unneeded and i don't feel like deleting a wallet, even if it has been emptied, is wise.  If we want to make a new wallet, we can already do this without disturbing the old one by setting a new --appdata option.  This will cause the wallet to use a different relative default location for the wallet database, the logs, and the RPC cert/key.

**Comment by jrick** [comment]
Closing due to aforementioned comment.
